### ISSUE TITLE
Animated webp files will not load

### ISSUE THREAD

**Issue by marcreichman-pfi** [haraldk/TwelveMonkeys#1074]
Good day @haraldk, thank you for all your work on this excellent suite of plugins!

I have a set of webp files (they originally came with an inaccurate extension of `.jpg` but I believe they are animated webp files. ExifTool calls them "Extended WEBP". My browsers can open them and they do animate. My impression is that the TwelveMonkeys libraries should be able to extract at least an initial frame, but I may be mistaken.

**Version information**
1. The version of the TwelveMonkeys ImageIO library in use.
`3.12.0`

2. The *exact* output of `java --version` (or `java -version` for older Java releases). 
```
java version "21.0.1" 2023-10-17 LTS
Java(TM) SE Runtime Environment (build 21.0.1+12-LTS-29)
Java HotSpot(TM) 64-Bit Server VM (build 21.0.1+12-LTS-29, mixed mode, sharing)
```

This is a version I'm testing on for this ticket, but in general this has been seen on JDK 21 on Linux and Windows, various minor versions and usually the oracle release.

3. Extra information about OS version, server version, standalone program or web application packaging, executable wrapper, etc. Please state exact version numbers where applicable.

This has been observed primarily inside a jetty-based service application, typically running on Linux inside docker. I have reproduced with some of the included files (see the attached zip for samples) in a standalone unit test.

**To Reproduce**

Use either the basic or advanced patterns from your [Readme](https://github.com/haraldk/TwelveMonkeys?tab=readme-ov-file#basic-usage). The basic example returns null, and the advanced example returns an empty Iterator.

**Expected behavior**
At least one frame from the file would be read into the `BufferedImage`

**Sample file(s)**
A zip is attached.

**Stack trace**
No trace, just the null / empty iterator mentioned above.

**Additional context**
I probably have more samples if you need! Thanks again for your time.
[webp-animated-files.zip](https://github.com/user-attachments/files/18184300/webp-animated-files.zip)

**Comment by haraldk** [comment]
Hi Marc,

The WebP plugin does support the extended WebP format. It allows reading both the initial frame and frames (as stored). It will not render full frames based on delta frames and meta information of the frame in question. If the frames are full independent frames, you should get all the information.

I am not able to reproduce the problem with the information given here. However, given that you see a `null` value and empty iterator, instead of an exception, along with:

> This has been observed primarily inside a jetty-based service application

I suspect the problem is that the plugin is not properly registered/installed, rather than not being able to read. 

Remember that you need to use the `IIOProviderContextListener` for web applications to support loading plugins from `WEB-INF/lib` as described in the README.

Strange that it still won't work in a standalone test though... How does your test work with this sample [animated-webp-supported.webp](https://github.com/haraldk/TwelveMonkeys/blob/master/imageio/imageio-webp/src/test/resources/webp/animated-webp-supported.webp)? Maybe you are missing the runtime dependencies in you test?

**Comment by haraldk** [comment]
No worries! Good to hear you figured it out!

PS: Note that using `scanForPlugins()` only, will detect new plugins but not remove them when the web application is unloaded, causing resource leaks and may result in unpredictable behavior if ImageIO tries to use classes that is no longer available. So I really recommend using the `IIOProviderContextListener` or installing the plugins manually in the server application's shared class path.  😀
