### ISSUE TITLE
ImageIO.read() returns null on JPEG fle

### ISSUE THREAD

**Issue by THausherr** [haraldk/TwelveMonkeys#132]
![1430258221574](https://cloud.githubusercontent.com/assets/6665575/7381527/868206ea-ee04-11e4-9e13-4a8b4b17c046.jpg)

The file can't be read with ImageIO.read(), but it is displayed by IrfanView.

**Comment by haraldk** [comment]
Hi Tilman,

The attached file has a first byte 0x0A before the JPEG SOI marker (0xFFD8). This means it's technically not a JPEG, and most software will never recognise it as such... Could be an alignment bug, or broken PDF creator software? If I remove that first byte, it's a valid JFIF JPEG, and the image reads fine in all software I've tested (including the standard Java JPEGImageReader).

As I've never come across such files in the wild, it might be better if you could handle this, i.e. removing the byte(s) before the SOI, in your image extraction handling. Would that be possible for you?

If you know in advance that the image is a JPEG, you should be able to just skip every byte until you find a 0xFF (or 0xFFD8 sequence). I can't put such logic into the JPEG plugin, because it's handed all kinds of files (I don't know in advance what file type) and must be able to determine quickly if it's a valid JPEG.


Best regards,

-- 
Harald K

**Comment by THausherr** [comment]
Hi, 
you're absolutely right. This is a pdfbox problem only. You can close the issue. Sorry!
Tilman 

Am 29. April 2015 10:05:31 MESZ, schrieb Harald Kuhr <notifications@github.com>:
>Hi Tilman,
>
>The attached file has a first byte 0x0A before the JPEG SOI marker
>(0xFFD8). This means it's technically not a JPEG, and most software
>will never recognise it as such... Could be an alignment bug, or broken
>PDF creator software? If I remove that first byte, it's a valid JFIF
>JPEG, and the image reads fine in all software I've tested (including
>the standard Java JPEGImageReader).
>
>As I've never come across such files in the wild, it might be better if
>you could handle this, i.e. removing the byte(s) before the SOI, in
>your image extraction handling. Would that be possible for you?
>
>If you know in advance that the image is a JPEG, you should be able to
>just skip every byte until you find a 0xFF (or 0xFFD8 sequence). I
>can't put such logic into the JPEG plugin, because it's handed all
>kinds of files (I don't know in advance what file type) and must be
>able to determine quickly if it's a valid JPEG.
>
>
>Best regards,
>
>-- 
>Harald K
>
>
>
>---
>Reply to this email directly or view it on GitHub:
>https://github.com/haraldk/TwelveMonkeys/issues/132#issuecomment-97340565

-- 
Diese Nachricht wurde von meinem Android-Mobiltelefon mit K-9 Mail gesendet.

**Comment by haraldk** [comment]
No problem! :-)

-- 
Harald K
