### ISSUE TITLE
DateUtil Testcases are failing

### ISSUE THREAD

**Issue by sanatmastan** [haraldk/TwelveMonkeys#138]
HI Harald,

I am seeting following test case got failed due to timezone in DateUtilTest

    @Test
    public void testCurrentTimeHour() {
        Calendar calendar = getCalendar(DateUtil.currentTimeHour());

        assertEquals(0, calendar.get(Calendar.MILLISECOND));
        assertEquals(0, calendar.get(Calendar.SECOND));
        assertEquals(0, calendar.get(Calendar.MINUTE));
    }

I am staying in india in IST TimeZone India Time Zone (UTC+05:30) ,i am always getting 30 for calendar.get(Calendar.MINUTE), which is causing the failure of the testcase.

I have seen a comment in your code for sub hour in the timezone,  

    /**
     * Rounds the given time down to the closest hour, using the default timezone.
     *
     * @param pTime time
     * @return the time rounded to the closest hour.
     */
    public static long roundToHour(long pTime) {
        // TODO: What if timezone offset is sub hour? Are there any? I think so...
        return ((pTime / HOUR) * HOUR);
    }

**Comment by haraldk** [comment]
Hi Sanat,

Thanks for reporting! This seems to be a bug indeed. You are the first to experience it, bad luck I guess. 

The `DateUtil` class is mostly in there for legacy reasons, and isn't used by any of the ImageIO plugins. It will go away in future versions of the library, thus fixing it isn't high on my priority list.

Feel free to submit a pull request, if you like. :-)

Otherwise, I suggest you just ignore (`@Ignore`) this test for now, if you prefer building yourself.


Regards,

-- 
Harald K

**Comment by haraldk** [comment]
Never mind. :-)

I think I fixed this quite easily in the latest commit https://github.com/haraldk/TwelveMonkeys/commit/203b330c9964ba23aa855d3f65cb8da687ec9ad7

-- 
Harald K

**Comment by haraldk** [comment]
Released in [3.1.1](https://github.com/haraldk/TwelveMonkeys/releases/tag/twelvemonkeys-3.1.1) (bugfix release).
