### ISSUE TITLE
java.security.AccessControlException attempting to read ColorSync profiles

### ISSUE THREAD

**Issue by trejkaz** [haraldk/TwelveMonkeys#154]
We restrict access to global system files as an attempt to get most reproducible results across different machines running the same OS.

I found that this library is attempting to access my ColorSync profiles:

    java.security.AccessControlException: access denied ("java.io.FilePermission" "/System/Library/ColorSync/Profiles/Generic CMYK Profile.icc" "read")
       at java.security.AccessControlContext.checkPermission(AccessControlContext.java:457)
       at java.security.AccessController.checkPermission(AccessController.java:884)
       at java.lang.SecurityManager.checkPermission(SecurityManager.java:549)
       at java.lang.SecurityManager.checkRead(SecurityManager.java:888)
       at java.io.File.isFile(File.java:877)
       at java.awt.color.ICC_Profile.getProfileFile(ICC_Profile.java:1825)
       at java.awt.color.ICC_Profile.getInstance(ICC_Profile.java:974)
       at com.twelvemonkeys.imageio.color.ColorSpaces.readProfileFromPath(Unknown Source)
       at com.twelvemonkeys.imageio.color.ColorSpaces.getColorSpace(Unknown Source)
       at com.twelvemonkeys.imageio.plugins.jpeg.JPEGImageReader.getImageTypes(Unknown Source)
       at com.twelvemonkeys.imageio.plugins.jpeg.JPEGImageReader.readImageAsRasterAndReplaceColorProfile(Unknown Source)
       at com.twelvemonkeys.imageio.plugins.jpeg.JPEGImageReader.read(Unknown Source)

This causes any attempt to read images using this library to fail as there doesn't appear to be any fallback occurring when the profile cannot be read.

Is there a reason these profile files have to be read from the system and can't be included with the library? I worry about whether this library can produce consistent results across platforms if it's relying on files only present on OSX.

**Comment by haraldk** [comment]
Hi,

Thank you for your interest in the TwelveMonkeys library!

Last questions first: The color profile in question is only used as a fallback, for CMYK images that does not contain their own, embedded ICC color profile. For such images, consistent results is less of a concern, as there's no way for the library to know what the original profile was. We can only hope to reconstruct something that looks like the original. Using `ColorConvertOp` and a generic CMYK profile (like the "Generic CMYK" on OS X) usually creates a more pleasing result than using a simple linear conversion, and is also quite fast (there is actually a fallback to such a linear conversion for platforms that doesn't have a proper profile installed).

The reason why I don't include the profile with the library, is that I don't know of a CMYK ICC profile with a suitable license and a reasonable size (there are some, but they are 3 MB+, the Apple profile has a good size, but obviously can't be redistributed). If you know of one, please let me know! :-)

Because of this lack of a bundled profile, the `ColorSpaces` class uses a default property-file per platform (OS X, Windows and Linux), to locate the profiles in known locations. Now, this isn't a well documented feature, but anyway: It's also possible to override these locations, by putting a properties-file on class path: `com/twelvemonkeys/imageio/color/icc_profiles.properties`. The following properties are looked up: `GENERIC_CMYK` and `ADOBE_RGB_1998` (see [icc_profiles_osx.properties](https://github.com/haraldk/TwelveMonkeys/blob/master/imageio/imageio-core/src/main/resources/com/twelvemonkeys/imageio/color/icc_profiles_osx.properties) for an example). Additional profiles can be downloaded from Adobe and others.

I think you should be able to use empty values (ie. `GENERIC_CMYK=`), to avoid the security exception use the builtin linear fallback conversion for now.

In any case, I think it makes sense to actually catch the `AccessControlException` if the profile loading fails, and use the fallback without extra configuration. I'll include this in the next version.


Best regards,

-- 
Harald K

**Comment by haraldk** [comment]
Fixed in 4eb742659687258b245dc2966445f94292785f4d.

-- 
Harald K
