### ISSUE TITLE
error in gwt project

### ISSUE THREAD

**Issue by mbaturov** [haraldk/TwelveMonkeys#186]
if you try to compile a gwt project where use image resources in css bundles like:
    
    public interface Csses extends ClientBundle {
    @Source("images/busy.gif")
    ImageResource busy();

and you have twelvemonkeys in classpath (via maven or other ways) you'll get an error like this

  ...client.resources.Csses.headerBackground'
[INFO]                   [ERROR] Unable to read image resource
[INFO] javax.imageio.IIOException: Not a JPEG file: starts with 0xff 0xd9
[INFO] 	at com.sun.imageio.plugins.jpeg.JPEGImageReader.readImageHeader(Native Method)
[INFO] 	at com.sun.imageio.plugins.jpeg.JPEGImageReader.readNativeHeader(JPEGImageReader.java:609)
[INFO] 	at com.sun.imageio.plugins.jpeg.JPEGImageReader.checkTablesOnly(JPEGImageReader.java:347)
[INFO] 	at com.sun.imageio.plugins.jpeg.JPEGImageReader.getNumImagesOnThread(JPEGImageReader.java:411)
[INFO] 	at com.sun.imageio.plugins.jpeg.JPEGImageReader.getNumImages(JPEGImageReader.java:389)
[INFO] 	at com.google.gwt.resources.rg.ImageBundleBuilder.addImage(ImageBundleBuilder.java:707)
[INFO] 	at com.google.gwt.resources.rg.ImageBundleBuilder.assimilate(ImageBundleBuilder.java:646)
[INFO] 	at com.google.gwt.resources.rg.ImageResourceGenerator$BundledImage.addImage(ImageResourceGenerator.java:92)
[INFO] 	at com.google.gwt.resources.rg.ImageResourceGenerator.prepare(ImageResourceGenerator.java:557)
[INFO] 	at com.google.gwt.resources.rebind.context.AbstractClientBundleGenerator.initAndPrepare(AbstractClientBundleGenerator.java:1013)

**Comment by haraldk** [comment]
Hi,

I'm afraid I'm not very familiar with the inner workings of GWT.

And I really don't understand what is the issue here. You seem to include a GIF resource, yet the error message is from the (standard Sun/Oracle) `JPEGImageReader` complaining this is not a JPEG...

A JPEG must start with a SOI (Start of Image) marker, which is `0xFF 0xD8`, your file seems to start with `0xFF 0xF9`... Which is neither a GIF nor a JPEG. 

Unfortunately, I can't say much more from the information you have provided. 

I can't see why this should be a TwelveMonkeys issue, as there's none of our classes present in the stack trace. More likely it is a GWT bug (I think they forget to reset the `ImageInputStream` before retrying with a different `ImageReader` instance [here](https://code.google.com/p/google-web-toolkit/source/browse/releases/2.0/user/src/com/google/gwt/resources/rg/ImageBundleBuilder.java?r=7428)). But I you really think this is a TwelveMonkeys issue, then please create either a failing test case, or a minimal GWT project that exposes the problem.


Best regards,

-- 
Harald K

**Comment by haraldk** [comment]
PS: I reported the issue to the GWT team. Hoping they'll follow it up. :-)

-- 
Harald K

**Comment by haraldk** [comment]
Closing for now. Feel free to reopen if you have further input!

Best regards,

-- 
Harald K
