### ISSUE TITLE
twelvemonkey TIFFImageReaderSPI not found

### ISSUE THREAD

**Issue by Ssoli** [haraldk/TwelveMonkeys#201]
I am using following dependency to find corrupted tif-files in a list o files:
```xml
		<dependency>
			<groupId>com.twelvemonkeys.imageio</groupId>
			<artifactId>imageio-tiff</artifactId>
			<version>3.2</version>
		</dependency>
```
The code is compiled by java 7.
I can build and everything looks fine until I run my application. 
Get the following error:
```
	at java.lang.Thread.run(Thread.java:662) [na:1.6.0_29]
Caused by: sun.misc.ServiceConfigurationError: javax.imageio.spi.ImageReaderSpi: Provider com.twelvemonkeys.imageio.plugins.tiff.TIFFImageReaderSpi not found
	at sun.misc.Service.fail(Service.java:129) ~[na:1.6.0_29]
	at sun.misc.Service.access$000(Service.java:111) ~[na:1.6.0_29]
	at sun.misc.Service$LazyIterator.next(Service.java:273) ~[na:1.6.0_29]
	at javax.imageio.spi.IIORegistry.registerApplicationClasspathSpis(IIORegistry.java:190) ~[na:1.6.0_29]
	at javax.imageio.spi.IIORegistry.<init>(IIORegistry.java:122) ~[na:1.6.0_29]
	at javax.imageio.spi.IIORegistry.getDefaultInstance(IIORegistry.java:142) ~[na:1.6.0_29]


```
I tried to register the ReaderSpi without any success. Do you have any clue why I get the mentioned error? Please let me know if you need more information in details.

```java
				import com.twelvemonkeys.imageio.plugins.tiff.TIFFImageReaderSpi;
				import com.twelvemonkeys.imageio.plugins.tiff.TIFFImageWriterSpi;
				import javax.imageio.ImageIO;
				import javax.imageio.spi.IIORegistry;
				import java.awt.image.BufferedImage;
				import java.io.BufferedReader;
				import java.io.File;
				....
				File tiff = getSomeFile();
				IIORegistry registry = IIORegistry.getDefaultInstance();
				registry.registerServiceProvider(new TIFFImageReaderSpi());
				registry.registerServiceProvider(new TIFFImageWriterSpi());
				ImageIO.scanForPlugins();
				BufferedImage img = ImageIO.read(tiff);

```

**Comment by haraldk** [comment]
Hi,

There should be no need to "manually" register the Spi classes, or invoke `scanForPlugins()`. Actually, the code seem to crash before it gets there, because Spis are registered when the `IIORegistry` class is instantiated. The exception message indicates that the `com.twelvemonkeys.imageio.plugins.tiff.TIFFImageReaderSpi` class is not found, but the both the Spi class and the `/META-INF/services/javax.imageio.spi.ImageReaderSpi` entry that causes it to be registered in the first place, are contained in the same JAR, so this does not normally make sense.

Most likely there's something in your environment causing this. How do you run/deploy/package your code (ie. servlet container, custom class loading, custom re-packaging/obfuscation, etc.)?

Can you create a standalone app that exposes this problem?


Best regards,

-- 
Harald K

**Comment by haraldk** [comment]
Looking at your stack traces again, it seems you are trying to run the above code using a Java VM version 1.6. This is not supported. Java 7 is needed, both for compiling and at runtime. 

-- 
Harald K

**Comment by Ssoli** [comment]
Thank you for your quick reply. My hope was jvm at runtime could be 6.
Unfortunately I cannot change it since it is a big company. Any other
option to solve it?
Happy New Year
Best regards,
Sheri

**Comment by haraldk** [comment]
See #198 

You might try to contact the guy from that issue, and see if you can work on a common solution. :-)

I still highly recommend upgrading to a more recent Java version though. Being a big company is not an excuse. 

Happy new year & good luck!

-- 
Harald K
