### ISSUE TITLE
Release plan for 3.3?

### ISSUE THREAD

**Issue by im-fredde** [haraldk/TwelveMonkeys#210]
Hi,
I wonder if there is any release planned for version 3.3 in the near future. 
I got a issue in my current project when I include image-batik (3.2.1) due to the dependency of xerces.

**Comment by haraldk** [comment]
Hi Fredde,

There's not a lot of new stuff at the moment. Generally, I try to create a release every quarter. But if the Batik dependencies is a big issue, I guess we could push the release a little.

As a workaround, I guess you could use the [Maven exclude functionality](https://maven.apache.org/guides/introduction/introduction-to-optional-and-excludes-dependencies.html) to exclude the Xerces dependencies from your project for now.


PS: Sorry about the mess. The Batik version change was due to a possible security issue. But somehow the Batik dependencies changed completely from 1.6.0 to 1.6.1 I think (hope) from 1.8 they will be more stable.


Best regards,

-- 
Harald K

**Comment by im-fredde** [comment]
Hi Harald,
First of all. Great work with Twelvemonkeys!

I have a workaround planned if there wasn't any release planned in the nearest future (week) :-).
I'll switch when the release is made.

**Comment by haraldk** [comment]
Ok! 

Good stuff! :-)

-- 
Harald K
