### ISSUE TITLE
EXIFEntry contructor is not public

### ISSUE THREAD

**Issue by avnbs** [haraldk/TwelveMonkeys#219]
Hi,

I am trying to implement EXIFWriter. I see that  EXIFEntry is package-private. The EXIFWriterTest class has

`entries.add(new EXIFEntry(TIFF.TAG_ORIENTATION, 1, TIFF.TYPE_SHORT));`

which seems to work as EXIFWriterTest is defined in the same package as EXIFEntry. 
Is this intentional? 

If so, what is the recommended way to create EXIFTags? 

Thanks

-Suresh

**Comment by haraldk** [comment]
Hi Suresh,

The current API wasn't really designed for this kind of use, which is why things are a little awkward at the moment. 

There are ongoing efforts to fix this, see #204 Refactor Exif metadata module to a TIFF and Exif module. After this task is done, there will be a public `TIFFEntry` class (as Exif is just TIFF metadata) for such use.

In the mean time, there's no need to use `EXIFEntry`, you can use any `Entry` subclass. The easiest is to just subclass `AbstractEntry`, see `TIFFUtilities.TIFFEntry` in the new `contrib` module for an example.


Best regards,

-- 
Harald K

**Comment by avnbs** [comment]
Thanks for the response. I can handle it by subclassing it. I will check #204 and see if I can help with some of the refactoring.

**Comment by haraldk** [comment]
Good stuff!

Closing for now.

-- 
Harald K
