### ISSUE TITLE
Image looks darker after combining two images

### ISSUE THREAD

**Issue by leolux** [haraldk/TwelveMonkeys#222]
I have two tiff images which contain the same ICC profile FOGRA 39. When I combine both images together than the resulting image looks a bit darker. Maybe it works as expected but I am not sure...

I have created a reproducer [1] for this which contains two additional sub-issues:
- ImageIO.setUseCache(false); doesn't prevent "_tmp1.tiff" to be persisted on the disk
- ArrayIndexOutOfBoundsException occurs when combining the images more than once

[1] https://github.com/leolux/tmonkeys-issue-02

**Comment by haraldk** [comment]
Hi,

Thanks thanks for reporting and creating test cases, I'll look into it!

Just some quick notes:
 - According to my tools, your input images does not contain the same ICC profile, one is "Coated FOGRA39 (ISO 12647-2:2004)" (color.tiff), the other is "U.S. Web Coated (SWOP) v2" (dina4.tiff). They are both CMYK profiles, but this may explain why the colors are slightly off.
 - `ImageIO.setUseCache(false)` alone *will not* prevent any file to be persisted on disk. It's just a flag to disable disk *caching* for the `ImageInputStream/ImageOutputStream` implementations. It is not used by the `ImageReader/ImageWriter`s. If you want to avoid writing the image to disk, use an in-memory structure, like a byte array, a `ByteArrayOutputStream` or similar.

The AAIOBE looks really strange though, I need to look into it a little more.


Best regards,

-- 
Harald K

**Comment by haraldk** [comment]
Ok,

I re-ran your test using 3.3-SNAPSHOT, and the `ArrayIndexOutOfBoundsException` is gone. So I guess this is just another manifestation of the previous bug you found. All the outputs look the same now, no exceptions. :-)

For the darker colors in the output, this is more likely to be a Java2D issue than a bug in the TIFF plugin, but I'll do some more digging. Can you try again using the exact same CMYK ICC profile and see if that helps?

-- 
Harald K

**Comment by leolux** [comment]
Your are right. I have just updated the dina4-fogra39.tiff to use the same icc profile. Thanks for your support!

**Comment by leolux** [comment]
Is there a maven repository that contains the version 3.3-SNAPSHOT?

**Comment by haraldk** [comment]
Ok,

I'm pretty sure that's a Java2D issue then, as I don't think I touch the colors in any way. Could be that Java2D composing happens in sRGB space even though both source and destination have a different (non-sRGB space). I'm not 100% sure about this though. 

SNAPSHOTs are not deployed to any repo, no. But you can clone the project and build yourself, until the release is out.

-- 
Harald K

**Comment by haraldk** [comment]
I tried displaying the image (color.tiff) right after loading, and then the combined image before saving and the colors are already different. So in my mind, that proves that the colors are correct after loading.

The greenish shade is displayed as:
#DBDD45 sRGB values from color.tiff as displayed by OS X preview

#DCDF25 sRGB values from color.tiff as displayed by Java 8 on OS X (visually very close)
#D4D632 sRGB values from the composed result as displayed by Java 8 on OS X (quite a bit darker)...

The difference between native and Java is probably because of different CMSes (Color Management Systems). Java uses the open source LittleCMS, while native OS X uses Apple's proprietary CMS to convert to sRGB, so minor differences are to be expected. 

The difference between color.tiff loaded directly and the composed result is more unexpected. Consider reporting as a Java2D bug to Oracle/OpneJDK (but don't expect it to be fixed in before the next decade or so.. :-P ).


Best regards,

-- 
Harald K

**Comment by leolux** [comment]
Alright, thanks!

Do you think that the switch to the older kodac CMS may change the color difference?

**Comment by haraldk** [comment]
It's worth giving KCMS a shot. It might produce a different result in this case. But I think most of the time it is slightly faster, but quality is... maybe not worse, but further off from what you'll expect (ie. Adobe or Apple's CMSes).

-- 
Harald K
