### ISSUE TITLE
Convert complex PSD to JPG rendering issue

### ISSUE THREAD

**Issue by scottialex** [haraldk/TwelveMonkeys#238]
Harald, first off great job! Thank you :-)

I am able to read a simple PSD file and write it to JPG but when the PSD is complex I get weird image rendering. I have attached the image of the PSD file with the Layer palette structure and the JPG version with rendering issues.

My code:
(removed image path for simplicity)

File file = new File( "final_logo_sm.psd" );
BufferedImage image = ImageIO.read( file );
ImageIO.write(image, "jpg", new File("final_logo_sm.jpg"));

Here's a link to download the sample PSD file for local testing:
https://drive.google.com/file/d/0B8rwnalEoCXnelJsUmllMXlZUmc/view?usp=sharing

Google drive in Chrome converts this exact PSD to a PNG blob into an HTML image object for previewing without issues and it does it very quickly. We are looking to accomplish the exact same result; that is: convert PSD to JPG/PNG --> Save to DB --> reuse it for client-side preview.

Thank you very much for all your help!

![final_logo_sm](https://cloud.githubusercontent.com/assets/6372395/15079941/7c577f14-1389-11e6-9df7-a988cffa8191.jpg)

![screen shot 2016-05-06 at 12 49 20 pm](https://cloud.githubusercontent.com/assets/6372395/15079886/2734a836-1389-11e6-8872-1e9deb1409b8.png)

**Comment by haraldk** [comment]
Hi Alejandro,

Thanks! 

Looking at your JPEG output, my first reaction is that this is likely a JPEG writing issue, rather than a PSD reading issue, because a lot of JPEG software does not fully support 4 channel RGBA JPEG data (it's often misinterpreted as CMYK or PhotoYCCA, which is why you get completely weird colors). I also suspect the default Java `JPEGImageWriter` not adhering to the conventions for writing RGBA data...

Anyway, can you try writing the result as PNG rather than JPEG, and attach the output of that conversion? Does it look the same, or is it okay?

If it looks the same, I'll look into it as soon as possible! But I won't be able to do that before monday I'm afraid.


Best regards,

-- 
Harald K

**Comment by scottialex** [comment]
Oh wow you're right! PNG did it perfectly :-)

You da man. I can totally use PNG so this case for me is closed unless you want me to try something else.

Have a great weekend! and thank you.
