### ISSUE TITLE
additional Apache licencing

### ISSUE THREAD

**Issue by THausherr** [haraldk/TwelveMonkeys#242]
We at PDFBox have been testing CCITTFaxDecoderStream (and related files) because it fixes a longtime bug, see
https://issues.apache.org/jira/browse/PDFBOX-3338

We won't use the full product, because the original product doesn't export that class, and because it is really just that file and another, slightly modified to support byte alignment. (We might still use twelvemonkeys as a whole at a later time for the JPEG decoding, see PDFBOX-2694)

There are two alternatives (see discussion at the bottom of the link)
- you accept an additional apache license of your files
- you don't, so we'd keep your header intact per https://www.apache.org/legal/src-headers.html#3party and also add your license to the LICENSE file(s) of us that have all the licenses.

So, what would the authors of that file prefer?

I would also add the version and the date, so that it is easier to detect further changes on your side.

**Comment by Schmidor** [comment]
I would like to let Harald decide that.

But to the byte align:
CCITT RLE always aligns to bytes for new lines, CCITT T.4 never.
For CCITT T.3 there is an option TIFFExtension.GROUP3OPT_FILLBITS, which controls the line alignments. But this is only relevant for our Encoder, as the Decoder is able to just skip over the fillbits.

**Comment by THausherr** [comment]
Re byte align, the CCITT used in TIFF is not 100% the same as the one used in PDF, i.e. some options are available in PDF that are not used in TIFF.

**Comment by Schmidor** [comment]
This is interesting, do you have sample file with G3 and encodedByteAlign?

For G4 maybe it just needs an conditional "resetBuffer()" at the beginning of "decodeRowType6()".
For G3 the CCITT Spec says that the EOL code should be prepended by zeros so that it ends at a byte boundary. If encodedByteAlign diverges from that, you have to ensure that the EOL is read at the line end instead of when the next line should be read as on the current implementation.

**Comment by THausherr** [comment]
I don't have a sample file, only raw streams. G4 has already been adapted by Petr, I'm now working on RLE, and there the "todo" is the opposite, i.e. optionally not skip to the next byte, at the top of decodeRowType2(). Another thing I'm working on is to stop reading when a predefined row count has been reached (we have a case where there's trash).

**Comment by haraldk** [comment]
Hi guys,

This is actually quite funny, as I originally wanted to use a similar class for CCITT decoding from another Apache project (I think it was Batik), but I was unable to due to conflicting licenses, so I just wrote my own (I only wrote the basic Huffman RLE stuff, Olliver added the difficult stuff later). ;-)

My only concern if we choose to accept the Apache license, what would happen if someone provides a bugfix or, say a huge 4x speed optimization to PDFBox under ASF license? Would it be a problem merging such patches back and maintain (only) BSD license?

If you choose to use more of the TwelveMonkeys library at a later time, I'm sure we could expose these classes as public, in a separate module and package, if that would be helpful to PDFBox.

Other than that, seems you are a long way into sorting out the technical details. :-)

Re. sample files, wouldn't a raw stream serve as a sample, as we are testing the decoder alone?



-- 
Harald K

**Comment by lehmi** [comment]
WRT to to the license questions:

IANAL but IMHO both licenses (BSD and AL2.0) are compatible and it shouldn't be a problem to exchange parts of the source as long as all conditions of redistribution are followed.

@haraldk What issue do/did you see, maybe I'm overseeing something?

**Comment by haraldk** [comment]
I think the issue lies exactly in "as long as all conditions of redistribution are followed". Isn't a condition for derivative works of AL2.0 that the derivate works is also under AL2.0? Or am I missing something? 

Don't get me wrong, I don't want to cause trouble for you guys, I just want to fully understand the consequences. I'm all for letting you use this code, as more usage means more testing and that usually means better quality software. :-)

-- 
Harald K

**Comment by lehmi** [comment]
AFAIU the license you don't have to. Here is the relevant part of the license:

> You may add Your own copyright statement to Your modifications and may provide additional or different license terms and conditions for use, reproduction, or distribution of Your modifications, or for any such Derivative Works as a whole, provided Your use, reproduction, and distribution of the Work otherwise complies with the conditions stated in this License.

**Comment by haraldk** [comment]
Thanks, but I fail to see how this is addressing my concern. I.e. I don't want to add anything. I (potentially) want to *remove* the AL2.0 that you want to add, if someone supplies a patch directly to you. I don't think that could "otherwise compl[y] with the conditions stated" (esp. 4a). 

I understand this is probably not a big deal, as the copyright holder/submitter would still be able to supply the same patch to me. It would just be nice if we could agree wether or not this is a real issue and have a mitigation strategy, should it ever arise.


Best regards,

-- 
Harald K

**Comment by haraldk** [comment]
@THausherr @lehmi Sorry if I completely misunderstood your last comment... 

Would it be acceptable that you add an Apache License to the files, with an additional clause stating:

"Any derivate work of this file must be released under BSD license."

?


-- 
Harald K

**Comment by lehmi** [comment]
Sorry for answering that late ...

@haraldk We can't add such a clause. We might stop this discussion here and now if you are not comfortable with licensing that file under the apache license to us. We are fine with that, no need to worry.
We are going to add the file with the origin license as described above. We should try to route all improvements/fixes directly to you and simply replace the file within our repository including those improvements/fixes from time to time to keep all license questions simple.

**Comment by haraldk** [comment]
Ok,

Thanks! We'll go with option 2 for now then, if that's alright with you. 

-- 
Harald K

**Comment by THausherr** [comment]
FYI, we are now using the TIFF encoder too, thanks :-)
https://issues.apache.org/jira/browse/PDFBOX-3069

**Comment by haraldk** [comment]
Hey, cool!

Your issue tracker seems to be down or having issues on its own. Can't access it at the moment... Will check back later.

Anyway, nice to see you are switching to the TwelveMonkeys TIFF plugin! Expecting bug reports en masse from now on then.. There are known issues in the TIFF encoder. ;-)
But don't worry, we are working on them.


Best regards,

-- 
Harald K

**Comment by haraldk** [comment]
Oh, never mind.

I see you are using only the CCITT parts, the known issues I mentioned above does not affect them. Looks good, then! :-)

-- 
Harald K
