### ISSUE TITLE
ImageUtilTestCase fails with 8u60+

### ISSUE THREAD

**Issue by ankon** [haraldk/TwelveMonkeys#249]
When building master (723632addfdb9fa637f29de56bb8a24c94fd4136) with Oracle JDK 1.8.0_60 and higher on Linux/x64:
~~~~
Running com.twelvemonkeys.image.ImageUtilTestCase
Tests run: 10, Failures: 1, Errors: 0, Skipped: 0, Time elapsed: 0.842 sec <<< FAILURE! - in com.twelvemonkeys.image.ImageUtilTestCase
testToBufferedImage(com.twelvemonkeys.image.ImageUtilTestCase)  Time elapsed: 0.007 sec  <<< FAILURE!
java.lang.AssertionError: 
	at org.junit.Assert.fail(Assert.java:91)
	at org.junit.Assert.assertTrue(Assert.java:43)
	at org.junit.Assert.assertTrue(Assert.java:54)
	at com.twelvemonkeys.image.ImageUtilTestCase.testToBufferedImage(ImageUtilTestCase.java:108)
~~~~

The build passes with 8u51.

**Comment by haraldk** [comment]
Hi Andreas,

Thanks for reporting! 

The assertion on that line seems a little bogus.. I think you can safely remove line 108-110, but I'll look into it.

Would be interesting to know what JRE/JDK changes that causes the test to fail though...


Regards,

-- 
Harald K

**Comment by haraldk** [comment]
Did some testing and I don't find any reason to include the part of the test that fails. Should work now.

Actually, the bug seems to be caused by a long time bug that was fixed, `BufferedImage.getPropertyNames()` used to unconditionally return `null`. Now it returns the names of the properties that are indeed set.

-- 
Harald K
