### ISSUE TITLE
Support for PNG images

### ISSUE THREAD

**Issue by roborobo2** [haraldk/TwelveMonkeys#273]
I cannot make to work your plugin with png images. For JPEG works fine.
Can You help me? maybe is this png image broken because after processing is in PINK colors
![lol boost](https://cloud.githubusercontent.com/assets/2378631/16961154/92da2456-4dec-11e6-9789-85ae71431ce2.png)

(sorry for issue but I don't find any other option to contact you)

**Comment by haraldk** [comment]
Hi Robo,

Opening an issue is the correct way to contact the project regarding problems with the library. So don't worry. :-)

However, the library does not currently have a PNG plugin, so there's not much I can do to help you... I did try reading the image using standard ImageIO and the built-in PNG plugin, and it works fine for me (it looks just like it does in the browser, with a transparent background). 

For general programming problems like this, I suggest using StackOverflow. If your problem is converting the transparent PNG to JPEG, see for example [this StackOverflow Q/A](http://stackoverflow.com/questions/36030307/stripping-alpha-channel-from-images), otherwise post a new question. And, remember posting the code you have problem with. :-)


Best regards,

-- 
Harald K

**Comment by Lonzak** [comment]
I just wanted to integrate twelvemonkeys however then realized that it doesn't support PNG.
Maybe the integration of pngj (https://github.com/leonbloy/pngj) is possible to support writing PNG files?
