### ISSUE TITLE
Infinite loop while getting ImageReaders

### ISSUE THREAD

**Issue by Ph3n1x** [haraldk/TwelveMonkeys#275]
I downloaded [this favicon](http://www.citrus.ua/img/favicon.ico) (which is a SVG, not an ICO) and loaded it into a byte[]. Then I am trying to get the ImageReaders like this
```
try (ImageInputStream inputStream =
                   ImageIO.createImageInputStream(new ByteArrayInputStream(imageBytes))) {
    Iterator<ImageReader> iter = ImageIO.getImageReaders(inputStream));
    // it never gets past 
}
```

The method never returns and ends in an infinite loop in SVGImageReaderSpi.java in line 140
```
while (pInput.read() != '<') {
    // Skip over, until next begin tag
}
```

**Comment by haraldk** [comment]
Hi,

Thanks for reporting!

@Ph3n1x  Can you send me (zip it, and attach the zip to this issue) the favicon you downloaded as SVG? If I download the one from your link above, I do indeed get an ICO file, which loads fine and doesn't reproduce the problem here.

However, I see there is a problem in the code you have quoted, that is if EOF is reached before a start of a tag (`'<'`), then `pInput.read()` will return `-1` (for ever) and we will have an infinite loop. I believe that is the case you run into. I'll try create a fix for that, but I need some time to put together a solid test case.


Best regards,

-- 
Harald K

**Comment by Ph3n1x** [comment]
Oh, sorry, you are right... It was [this](http://www.citrus.ua/favicon.ico) icon. I now see, that this is not an icon, bu a bad configured php server :D But nevertheless, the infinite loop should not happen.

And yes, you are right, that is exactly the case I run into.

**Comment by haraldk** [comment]
Fixed in latest master.

-- 
Harald K
