### ISSUE TITLE
How to  read CMYK image  without  convert to RGB

### ISSUE THREAD

**Issue by BedunkevichE** [haraldk/TwelveMonkeys#281]
Hi!
in manual is written thatit can read CMYK without convert to RGB.
how to do it?
use TwelveMonkeys lib and  by default  my CMYK images after reading,  are all converted to RGB.

thanks

**Comment by haraldk** [comment]
Hi Eugene,

Yes, by default the images are converted to RGB, as this is faster/more compatible.
If you prefer the CMYK variant, you need to pass an `ImageReadParam` to the `JPEGImageReader` with the destination set to one of the CMYK types obtained from the reader's `getImageTypes(index)` method.

Something like:

    ImageInputStream stream = ...
    ImageReader reader = ImageIO.getImageReaders(stream).next(); // assumes a valid JPEG input
    reader.setInput(stream);
    
    ImageTypeSpecifier cmykType = null;

    for (ImageTypeSpecifier type : reader.getImageTypes(0)) {
        if (type.getColorModel().getColorSpace().getType() == ColorSpace.TYPE_CMYK) {
            cmykType = type;
            break;
        }
    }

    if (cmykType != null) {
        ImageReadParam param = reader.getDefaultReadParam();
        param.setDestinationType(cmykType);
    }

    BufferedImage cmykImage = reader.read(0, param);

Hope that helps!


Best regards,


-- 
Harald K

**Comment by BedunkevichE** [comment]
thanks, it works.

and have 1 more goal.
after getting buffered image from CMYK, i try via ImageIO.write(BufferedImage, "jpg", ByteArrayOutpuStream) get the   byteArrayOutputStream of this bufferedImage (want to get  byte[] from bufferedImage)
and got the exception 
javax.imageio.IIOException: Invalid argument to native writeImage
	at com.sun.imageio.plugins.jpeg.JPEGImageWriter.writeImage(Native Method)
	at com.sun.imageio.plugins.jpeg.JPEGImageWriter.writeOnThread(JPEGImageWriter.java:1067)
	at com.sun.imageio.plugins.jpeg.JPEGImageWriter.write(JPEGImageWriter.java:363)
	at javax.imageio.ImageWriter.write(ImageWriter.java:615)
	at com.twelvemonkeys.imageio.plugins.jpeg.JPEGImageWriter.write(JPEGImageWriter.java:160)
	at javax.imageio.ImageIO.doWrite(ImageIO.java:1612)
	at javax.imageio.ImageIO.write(ImageIO.java:1578)


have any suggestions how to solve it?

thanks

**Comment by haraldk** [comment]
Unfortunately, CMYK JPEG writing isn't fully supported yet, see issue #25 (and the various other issues linked from that issue). 

It is probably possible, but you need to do it "the hard way", by using the `ImageWriter` directly, and passing a `Raster` rather than a `BufferedImage` in the `IIOImage`. This means you need to convert (invert) the raster data for CMYK or convert to YCCK. 

Then you need to somehow massage the metadata to make the resulting JPEG file being interpreted as CMYK (encoded as either CMYK or YCCK). For instance, the writer will reject any Adobe App14 segment with YCCK, but you can pass an "unknown" marker containing a valid Adobe App14 segment with YCCK transform. For CMYK, you need to name the component ids C, M, Y and K respectively.

It's usually a good idea to write an ICC_PROFILE App2 segment using the CMYK colorspace from your image, otherwise the colors will look "off".

Good luck! 


Best regards,

-- 
Harald K

**Comment by BedunkevichE** [comment]
Thanks a lot!

**Comment by haraldk** [comment]
Closing for now!

**Comment by bernstein82** [comment]
hi there

anyone got this to work? basically i'd like to use this in conjunction with apache pdfbox. that is to  create PdfXImageObject's in CMYK with ISO Coated v2 300% ICC Profile (the only one currently supported by pdfbox) from resulting byte-array.

it would speed up my workflow tremendously (currently i'm creating a pdf with rgb images. then using adobe acrobat for conversion. however to preserve image quality one has to convert to jp2000 pdf, then to cmyk jp2000 pdf, then to cmyk jpg pdf then to pdf/x). which for a 2GB pdf takes acrobat hours...

thanks
