### ISSUE TITLE
Inconsistent metadata read from stream

### ISSUE THREAD

**Issue by FelixA** [haraldk/TwelveMonkeys#300]
Hi,

I'm getting an error thrown when trying to read specific tiffs with JPEG compression:

Exception in thread "main" javax.imageio.IIOException: Inconsistent metadata read from stream
	at com.sun.imageio.plugins.jpeg.JPEGMetadata.<init>(JPEGMetadata.java:362)
	at com.sun.imageio.plugins.jpeg.JPEGImageReader.getImageMetadata(JPEGImageReader.java:1023)
	at com.twelvemonkeys.imageio.plugins.tiff.TIFFImageReader.read(TIFFImageReader.java:1149)
	at javax.imageio.ImageIO.read(ImageIO.java:1448)
	at javax.imageio.ImageIO.read(ImageIO.java:1352)

I'm not quite sure how to on bug-tracking with this issue. Let me know if you need the original file to dive into this issue.

Thanks a lot!

**Comment by haraldk** [comment]
Hi Felix,

Thanks for reporting! 

If you can provide the version of the library you are using, and the file you have trouble reading, I'll be able to look into it.

You may need to rename the file to .JPG or compress it in a ZIP to be able to attach the file to the issue (the issue tracker is a little picky about what files it allows, but it can easily be fooled). 

-- 
Harald K

**Comment by FelixA** [comment]
[S500003979.zip](https://github.com/haraldk/TwelveMonkeys/files/613545/S500003979.zip)

Hello Harald,

the file is attached as a .zip. I actually managed to get some data about the file.
It is compressed as an old_style_jpeg. So apparently it is really just a Container for a .jpg Image. 

My Workaround to work with it now is to find the Offset from which the .jpg Begins, read it as an Input stream and cut off all the metadata of the .tif Container.

I'm using the following library:

<dependency>
	<groupId>com.twelvemonkeys.imageio</groupId>
	<artifactId>imageio-tiff</artifactId>
	<version>3.3</version>
</dependency>

Is this the current one?

Best regards

**Comment by haraldk** [comment]
That is the current one.

"Old style" JPEG isn't always that simple, but in this case it seems that the data contains a full JIF/JPEG stream. There are bogus `JPEGQTables` and `JPEGDCTables/JPEGACTables` pointing to the DQT/DHT segments *inside* the JIF structure, pointed to by the `JPEGInterchangeFormat` tag (though the TIFF spec says such things should never happen...).

Not entirely sure what's wrong here, but at least the JIF structure contains *something* the `JPEGImageReader` chokes on. I'm using the built-in (`com.sun....JPEGImageReader`) in the `TIFFImageReader` as it's theoretically faster than mine and JPEG-in-TIFF is usually well-formed. I might need to revisit that decision, at least for "old style" JPEG.

2 possible quick-fixes: 

1. In the `createJPEGDelegate()` method in the `TIFFImageReader` comment out all the lines before:

        // If we can't get the standard reader, fall back to the default (first) reader
        Iterator<ImageReader> readers = ImageIO.getImageReadersByFormatName("JPEG");
        if (!readers.hasNext()) {
            throw new IIOException("Could not instantiate JPEGImageReader");
        }

        return readers.next();

2. Wrap the `getImageMetadata(0)` invocation in a `try/catch` by creating a new method:

        private IIOMetadata getJPEGMetadataSafe(ImageReader jpegReader) throws IOException {
            try {
                return jpegReader.getImageMetadata(0);
            }
            catch (IIOException e) {
                return null;
            }
        }

 ... and replace all invocations of `needsCSConversion(..)` with the following:

    needsCSConversion = needsCSConversion(interpretation, getJPEGMetadataSafe(jpegReader));

You should then see a (very red) form in german, with a barcode. :-)


-- 
Harald K

**Comment by FelixA** [comment]
Hello Harald,

thanks for your extremely fast reply. I do not fully understand your first comment except that the given tif file seems to be quite far away from the actual spec. 

I tried out your first solution and your Default Reader works perfectly fine. I didn't test the reading Speed, but I don't feel any significant Speed loss.

I will try to find a timeframe to test your second solution as well and give you Feedback on that!

One Thing that is a bit strange for me tho is: 
When I tried to convert the tif to a jpg by cutting off the tif Container, I ended up with a jpg with 705 kb size.
But reading it and writing it out as a jpg using your library I end up with a 667 kb document. Just by guessing, do you delete any additional metadata about the document? I didn't try out comparing the Pixels yet, but it at least feels like there hasn't been any Quality loss.

Anyways, thanks a lot for your Response!

**Comment by haraldk** [comment]
You're welcome! :-)

No worries, the "old style" JPEG in TIFF spec was never well defined/understood. That's why it was replaced by the new JPEG in TIFF standard...

I'll try to implement a permanent fix for your issue soon.

About the conversion and file sizes: It depends on your code... If you use the simplest form `ImageIO.read()/ImageIO.write()`, any metadata is lost, as a `BufferedImage` doesn't carry metadata.  It could also be a slight quality loss, as the default quality setting for JPEG is `0.75f` I think (aka "75 %").

If you instead use the `ImageReader/ImageWriter` directly, and use the `readAll()` method that returns an `IIOImage` and write using the `write()` mehtod that takes an `IIOImage` as parameter, you should be able to preserve the metadata at least. It may be possible to also re-use the quantization tables, in this case the conversion should be as close to lossless as possible (theoretically it can be, if you don't alter the pixels), but I haven't investigated this thoroughly. 

If you need lossless, your best bet is probably to skip the entire decoding/encoding cycle, and just extract the JPEG at the stream-level (as you already did). You might want to look at the code from the `TIFFImageReader` to see some of the different possible ways JPEGs can be stored in a TIFF (single stream, striped/tiled, with/without separate tables, etc).


Good luck,

-- 
Harald K

**Comment by haraldk** [comment]
Fixed in latest master (forgot to close).

-- 
Harald K
