### ISSUE TITLE
Add read support for custom PIXTIFF ZIP compression in TIFF plugin

### ISSUE THREAD

**Issue by Priyalks** [haraldk/TwelveMonkeys#307]
Hi,

we are planning to use twelve monkeys in our project for reading and rotating tiff files.
However, we see that when we try to read JBIG/ZIP compressed tiff files, we get Unsupported TIFF Compression exception.
Are there plans to support these two compression formats? if so any timeline?

**Comment by haraldk** [comment]
Hi Priyalks,

ZIP (or "Deflate") compressed TIFFs should already be supported (both compression values 32946 and 8). There might be legacy ZIP compressed TIFFs that uses a different compression scheme that can't be read, though. If you have such files that can't be read, please send them to me by attaching them to this issue, so that I can inspect them, and possibly add support for them in the future. 

JBIG compression is not supported at the moment. However, as there are known 3rd-party plugins that can read JBIG format, adding support for it should be possible and and implementation could work similar to how JPEG in TIFF works (by delegating to a dedicated JBIGImageReader). Again, if you have some sample files, please attach them to this issue, and I will look into it.


Best regards,

-- 
Harald K

**Comment by Priyalks** [comment]
Hi,
I have renamed the tiff to .png and attached them . Attached both JBIG and ZIP files







![22 tiff binary zip](https://cloud.githubusercontent.com/assets/12161296/21650239/527e1242-d2ca-11e6-8655-5b876be4340e.png)
![40 tiff 8 bit gray zip](https://cloud.githubusercontent.com/assets/12161296/21650260/6536a96c-d2ca-11e6-85e7-4761e6b6ded3.png)
![44 tiff 4 bit palette zip](https://cloud.githubusercontent.com/assets/12161296/21650262/65385a78-d2ca-11e6-8abb-af0e09b56a7c.png)
![48 tiff 8 bit palette zip](https://cloud.githubusercontent.com/assets/12161296/21650261/6537c086-d2ca-11e6-81db-a3fdcc97c109.png)
![56 tiff 24 bit color zip](https://cloud.githubusercontent.com/assets/12161296/21650263/655a593e-d2ca-11e6-89c1-04c35793793a.png)
![33 tiff 4 bit gray zip](https://cloud.githubusercontent.com/assets/12161296/21650264/656c1782-d2ca-11e6-8d36-40e415d72367.png)
![20 tiff binary enhanced jbig](https://cloud.githubusercontent.com/assets/12161296/21650274/6ad92b42-d2ca-11e6-9f72-5d6aaddadb79.png)
![19 tiff binary jbig](https://cloud.githubusercontent.com/assets/12161296/21650273/6ad65e58-d2ca-11e6-8bca-0221f88fb97c.png)

**Comment by haraldk** [comment]
Excellent, thank you!

Well, the issue with the "ZIP compressed" TIFF files is that they are written using a PIXTIFF proprietary compression value: 50013. This is not one of the standard TIFF ZLib/Deflate compression values (8 or 32946). The only [documentation](https://community.emc.com/thread/113771?tstart=0) I could find on this compression is rather sparse in details, but also lists a bunch of other (seemingly redundant) compression values in the 50000+ range. 

The good news though, is that the files looks otherwise all good, and if I just handle these files exactly as any other ZLib/Deflate compressed TIFF, they can be read by the plugin just fine. I think I'll add support for this compression quite soon.

I need some more work to be able to add JBIG support, but should also be doable. I'll start by doing some test with open source JBIG decoders, and see if they are interchangeable or if special support for each is required. 

PS: As I develop this library as a hobby, and on my spare time, I can't make any promises about time frame. If you need these features sooner, we might be able to make a deal somehow though. :-) 


Best regards,

-- 
Harald K

**Comment by haraldk** [comment]
Hi again,

Do you happen to have links to any specification on how the JBIG data is stored inside the TIFF strip/tiles?

I made a quick test trying to add support using [this JBIG2 plugin](https://github.com/levigo/jbig2-imageio) (als tried [this one](https://github.com/Borisvl/JBIG2-Image-Decoder)), but no luck. Could be that these decoders can't handle JBIG ("JBIG1"), but as I can't find much documentation, it's hard to say...


Best regards,

-- 
Harald K

**Comment by Priyalks** [comment]
Hi ,
No we dont have any info regarding that

Thanks,
Priya

**Comment by haraldk** [comment]
Ok,

Thanks. I realise that the data is most likely JBIG (JBIG1), and I haven't yet found a JBIG decoder in Java. But I'll keep looking. I might split this issue in two though, so we can add support for ZIP and JBIG independently.

-- 
Harald K

**Comment by haraldk** [comment]
Support for the PIXTIFF ZIP compression is now added in 9199083. Closing this issue.

JBIG support is still pending, please see #309 for progress.

-- 
Harald K

**Comment by roytam1** [comment]
> I made a quick test trying to add support using [this JBIG2 plugin](https://github.com/levigo/jbig2-imageio) (als tried [this one](https://github.com/Borisvl/JBIG2-Image-Decoder)), but no luck. Could be that these decoders can't handle JBIG ("JBIG1"), but as I can't find much documentation, it's hard to say...

JBIG2 is different from JBIG1. BTW is there any sample TIFF that has Compression Type = 34715 for JBIG2?
