### ISSUE TITLE
RGB TIFF with 5 samples/pixel (2 extra samples) not read correctly

### ISSUE THREAD

**Issue by jond02** [haraldk/TwelveMonkeys#317]
Hi Harald,

Hoping you can help troubleshoot an issue I'm having converting certain tifs to png previews. Here are the two images:

https://drive.google.com/drive/folders/0B8FrShLAYpOEVGFXdmxRcmNZSzQ?usp=sharing

You'll notice preview.png is filled with noise. It appears to be caused from the mask channels, but I'm not sure how to account for this so a proper png is created. My conversion code:

    <dependency>
            <groupId>com.twelvemonkeys.imageio</groupId>
            <artifactId>imageio-tiff</artifactId>
            <version>3.3.1</version>
        </dependency>

    createPreview("path/to/tif.tif", "path/to/png.png", BufferedImage.TYPE_INT_ARGB, "PNG");

    public static boolean createPreview(String tiffFile, String pngFile, int type, String format){

        try {
            File file = new File(tiffFile);
            BufferedImage image = ImageIO.read(file);
            BufferedImage newImage = image;

            if (image.getWidth() > 1000 || image.getHeight() > 1000){
                newImage = updateImage(image, type, image.getWidth() / 4, image.getHeight() / 4);
            }
            ImageIO.write(newImage, format, new File(pngFile));
            return true;
        } catch (IOException e) {
            e.printStackTrace();
            return false;
        }
    }

    private static BufferedImage updateImage(BufferedImage originalImage, int type, int width, int height) {

        BufferedImage image = new BufferedImage(width, height, type);
        Graphics2D g = image.createGraphics();
        if (type == BufferedImage.TYPE_INT_RGB){
            g.drawImage(originalImage, 0, 0, width, height, Color.WHITE, null);
        } else {
            g.drawImage(originalImage, 0, 0, width, height, null);
        }
        g.dispose();
        return image;
    }

Also a general question if you don't mind, but if this isn't the right place no worries. I've been looking for Java image processing training materials, but they seem hard to find, besides on Graphics2D from many years ago. How would you recommend learning about Java image processing.

**Comment by haraldk** [comment]
Hi Jonathan,

The issue seems to be that the sample TIFF is RGB, but has 5 samples per pixel (interleaved), where the last two are "extra samples".  The first is the alpha channel (premultiplied), the second is undefined (could be a mask, another alpha, elevation, could be anything). 

Unfortunately, the TIFFImageReader does not currently support reading such images (it doesn't crash, but the image is decoded incorrectly, as you see in your PNG). The extra channel is mixed in with the "real" image data. There's nothing you can do to work around this as far as I can I see. 

I'll look into this, and see if I can add support for it at some point.

Re: Image processing, it's a very wide topic. What aspects of image processing are you interested in? I co-authored [Java Image Processing Survival Guide](https://github.com/sgoeschl/java-image-processing-survival-guide) with Siegfried Goeschl (which eventually turned into a series of talks held at conferences around Europe). It covers some basics, but is mainly focused on various image file formats and how to process them in Java. The Java2D tutorials is quite good as well, I think. But it really depends on what kind of processing you want to do.

Best regards,

-- 
Harald K

**Comment by jond02** [comment]
Hi Harald,

Thanks for looking into it and the info, appreciate it.

I have a copy of the Survival Guide, thanks for creating that, it helped validate why I was running into so many issues! Are your conference talks available online?

I'm interested in learning the details of general image processing for use on the web: resizing, format conversion, working with metadata, how the different formats of images structure their data, and an understanding of ImageIO and Graphics2D.

For example, to be able to troubleshoot an issue like this one, I wouldn't know to check the samples per pixel. 

The books I have found so far are:

The Art of Image Processing with Java (2010)
https://books.google.com/books?id=AKzMBQAAQBAJ

Java 2D Graphics (1999)
http://shop.oreilly.com/product/9781565924840.do

They aren't recent, and I'm not sure how much the API has changed over the years. Any recommendations?

**Comment by haraldk** [comment]
I don't read many books nowadays, so I can't really recommend any. I do think the [Java2D Tutorial](https://docs.oracle.com/javase/tutorial/2d/) online is a good starting point for learning Java2D though. The API has not changed much in recent years (since Java 1.4 or so).

I do own a hard copy of [Computer Graphics: Principles and Practice](https://www.amazon.com/Computer-Graphics-Principles-Practice-3rd/dp/0321399528). It's a little old, but still relevant I guess, to learn the basics. You can find parts of it [online as a PDF](http://ptgmedia.pearsoncmg.com/images/9780321399526/samplepages/0321399528.pdf).

Usually I find it easiest to just Google the stuff I need when I need it. It's often details buried deep down in a spec or so. 😉

Talks are available online. The original from DevFest Vienna 2014: https://www.youtube.com/watch?v=yZGQR_ho36Q and the updated one from JavaZone 2015: https://2015.javazone.no/details.html?talk=9ed5444182c191fa43e5ef6a3dfe968cfcef9d5327b500f305aaf689a2be5a77

I haven't watched any of them through as I can't stand listen to myself talking.. 😉


-- 
Harald K

**Comment by jond02** [comment]
Thanks! I'll check out the Java2D tutorial and videos to get started.

**Comment by haraldk** [comment]
Fixed in latest master.
