### ISSUE TITLE
Plugins "not detected"

### ISSUE THREAD

**Issue by Nadahar** [haraldk/TwelveMonkeys#327]
Hi, and thank you for a great library 👍 

I'm using most of you plugins in a PR I'm working on for our application (Universal Media Server) and it's working great for me. However, there is one of our team members that has a strange issue. It simply looks like the TwelveMonkeys plugins isn't there on his computer. We've obviously verified that they are, we're using Maven and he can build the application without error. I've studied our log file and I can find no ```Exception``` being thrown or nothing else that can give me a clue as to what is going wrong.

What happens is that we can see that the "Sun" plugins are chosen instead where they exist, and for formats where no other plugin is available ImageIO simply fails to read the file. It doesn't look like there's a priority problem in other words, it seems like they simply never register.

It's not uncommon that things that normally work fail to work on his computer, he has a somewhat antiquated computer running WinXP 32bit. His CPU is a Athlon 1700+ that doesn't have MMX support. Both the 32 bit OS and the lack of SSE2 support have shown itself to cause problems some times, but generally our application works on his computer as well. He is running Java 7.

Is there anyway I can troubleshoot/debug the (plugin) registration process to get some more information about what is actually going on?

**Comment by Sami32** [comment]
![capture_02222017_170833](https://cloud.githubusercontent.com/assets/18471069/23218303/3bd6406e-f91c-11e6-8ba4-037edcadfcbd.jpg)

**Comment by Nadahar** [comment]
Ah, ok - was it SSE2 that was missing then?

**Comment by haraldk** [comment]
Hi Nadar,

Sorry about the late reply, have been away from the keyboard a couple of days. ;-) 

I really doubt that the CPU has anything to do with it, as all the TwelveMonkeys ImageIO plugins are Java only, and as long as you can run Java 7 you should be good. But are you running the standard Oracle JRE?

I think you are right about the plugins not being registered. There can be multiple reasons for this, and it usually depends on the way you are deploying your application. What kind of application is this? Is it a stand-alone ("desktop") Java app, command line tool, web app (.war) or other kind of app? Does your app use custom thread groups, or custom class loading? For normal registration of the plugins, it's crucial that all the needed JARs are on class path, at the time the `ImageIO` class is initialized. If your app is a web app, make sure you read [this](https://github.com/haraldk/TwelveMonkeys#deploying-the-plugins-in-a-web-app). Otherwise, adding `ImageIO.scanForPlugins()` might help.

To help debugging, try printing `ImageIO.getReaderFormatNames()` to the console or log file. You can also try `IIORegistry.getDefaultInstance().getServiceProviders(ImageReaderSpi.class, true)`, to see if exactly what plugins are available. 


Best regards,

-- 
Harald K

**Comment by Nadahar** [comment]
@haraldk Thank you for your answer :)

The application is [Universal Media Server](https://github.com/UniversalMediaServer/UniversalMediaServer), and it's a desktop application. It's a Maven project, so every dependency is packed into one JAR before being distributed. This problem has (so far) only been detected on one computer from one in our team, which is running WinXP 32-bit with this ancient CPU. 

I have a WinXP 32-bit VM running on ESXi which has no such issues, so it's not the OS. I have Java 7 on the VM, so it shouldn't be the Java version. We have tried to increase available memory without any change, so it shouldn't be a memory issue. We have also tried reinstalling Java 7 (latest version) without any change. I have built a JAR that is working for me, that doesn't work at his computer (that is, everything except the TwelveMonkeys plugins seems to work). 

That is why it's so strange and I want to try to find out exactly what is going wrong. Issues on this computer because of the lack of CPU features is well known, he has to compile a lot of C/C++ code himself to get it running. The problem is that SSE2 has been with us since the Pentium 4 was released, and AMD followed in 2003 with support in it's CPU's. That's 14 years now, so I suspect that most developers take for granted that it is available. My theory is that some parts of the JRE might use functions that depend on SSE2 - and it's impossible to know from the Java code if we ask the JVM to do such things. I might be completely wrong though.

My worries aren't first and foremost this particular computer. While it's boring that it doesn't work for one of our team members, it's not a crisis. What I'm afraid of is that it *isn't* because of the odd CPU but some other circumstances that we haven't figured out - and that it can happen for a lot of our regular users as well when this code is released. That's why I'd really like to get to the bottom of this and figure out exactly what is going wrong.

Even stranger, later tests has revealed that your plugins is in use in some circumstances on this computer, while the Sun plugins is in use in other, so I'm really confused as to what to think right now.

I know about the servlet issues, they aren't relevant for us. Would ```scanForPlugins()``` still be worthwhile to do during startup? Do you know at which stage this is triggered "naturally"? Is it some static initialization done when ```ImageIO``` is first called, or is it initialized when the application starts?

I'll try to debug with the methods above, thank you.

**Comment by haraldk** [comment]
Hi again,

I've never before come across issues like you describe due to special CPUs in a "pure" Java application (Random crashes: yes. Random errors: yes. Silently ignoring certain code: no). So while it may still be possible, I don't think this is (directly) related to the CPU or system architecture. 

It could perhaps be that an old, slow processor would trigger threading issues (code being executed out of normal order) though, that could cause such an issue for this user only. But this means you could also experience this on other systems, in situations with heavy load, limited resources, etc.

If you are on a standard Oracle JRE (or, I guess, any OpenJDK derivative as well) the plugins are discovered by `ImageIO` through the `IIORegistry` constructor, invoked from a static initializer in the `ImageIO` class:

````java
    private static final IIORegistry theRegistry =
        IIORegistry.getDefaultInstance(); 
````

The `IIORegistry` constructor invokes `IIORegistry.registerApplicationClasspathSpis()`, which is the same method that is delegated to by `ImageIO.scanForPlugins()`. 

If possible, you could use a debugger, set a breakpoint here and step through the initialization process, to see exactly what happens.

Using `ImageIO.scanForPlugins()` in the application, is only useful if the plugins are not available from the standard class path, at the time of `ImageIO` class initalization. This is typical for apps that uses custom class loaders for plugins, for instance. Forgive me for not being too familiar with Universal Media Server, but as it seems to be plugin-based, this may very well be the case. In any case it won't hurt (except for wasting some CPU time, if all plugins are already registered). 

> every dependency is packed into one JAR before being distributed

One quite common issue with this way of distributing dependencies, is that one often forget to merge entries found in `META-INF/services/` in the various JARs. If not, the various plugins will overwrite each others entries, and you end up with only a single plugin being registered. But I guess you have this figured out, if it works on most other computers. Anyway, might be worth double-checking, just to be sure.

PS: About the nick, I usually check peoples' GitHub page before answering, and it certainly says [Nadar](https://github.com/Nadahar) (above Nadahar). ;-)


Best regards,

-- 
Harald K

**Comment by Nadahar** [comment]
@haraldk Thanks a lot, I suspect it would have taken a long time before I figured this out without your help (if at all).

The services registration mechanism was completely unknown to me. Actually, we've been "using" some of your plugins for a long time, I've just added more of them now, so I've just added entries in the POM and started using them. This means that this issue has been there for a long time without anyone figuring it out, only one reader class and one writer class has been registered (now it was the BMP/CUR/ICO reader and the IFF writer).

I haven't been developing Java that long, and to be honest the whole classloader paradigm is somewhat of an enigma to me.

Both debug logging of the registered classes and manual inspection of the JAR's ```META-INF``` confirmes that this is the problem. When I think about it, I've been running every test I've done both on my development computer and on VMs from Eclipse, because I like to have the debugger available when testing. It turns out that I've never actually run the JAR. Eclipse/M2E figures this out so that it works when run from Eclipse.

I'm still trying to figure out how to get Maven to play nice and use my "manual" service files for ImageIO while keeping it's automatic gathering for other services, but now I know what the problem is - and as I feared it would have been a big problem if released as-is.

Thanks again 👍

**Comment by haraldk** [comment]
Excellent! 

I'm not sure if using the Maven Assembly plugin is the best option for creating the "fat" JAR, as this seems to be a common issue many people face.

I know that [Maven Shade plugin](https://maven.apache.org/plugins/maven-shade-plugin/) has support for [filtering services](https://maven.apache.org/plugins/maven-shade-plugin/examples/resource-transformers.html#ServicesResourceTransformer), and might be a better fit. I know other projects have used it with success.

There's also [onejar Maven plugin](https://code.google.com/archive/p/onejar-maven-plugin/) that claims to do much of the same, but I'm not familiar with it. 


-- 
Harald K

**Comment by Nadahar** [comment]
In case it's useful to someone else, I solved it using ```maven-assembly-plugin``` by putting the manually merged files in a folder outside the "normal Maven structure". I used ```/src/main/external-resources/META-INF/services/``` since we already have other things that doesn't fit anywhere there.

In addition I edited the ```assembly``` file like this:

```xml
<assembly
	xmlns="http://maven.apache.org/plugins/maven-assembly-plugin/assembly/1.1.2"
	xmlns:xsi="http://www.w3.org/2001/XMLSchema-instance"
	xsi:schemaLocation="http://maven.apache.org/plugins/maven-assembly-plugin/assembly/1.1.2 http://maven.apache.org/xsd/assembly-1.1.2.xsd">
	
	<id>jar-with-dependencies</id>
	<formats>
		<format>jar</format>
	</formats>
	<includeBaseDirectory>false</includeBaseDirectory>

	<dependencySets>
		<dependencySet>
			<outputDirectory>/</outputDirectory>
			<useProjectArtifact>true</useProjectArtifact>
			<unpack>true</unpack>
            <unpackOptions>
				<excludes>
					<exclude>META-INF/services/javax.imageio.spi.ImageReaderSpi</exclude>
					<exclude>META-INF/services/javax.imageio.spi.ImageWriterSpi</exclude>
				</excludes>
			</unpackOptions>
			<scope>runtime</scope>
		</dependencySet>
	</dependencySets>
	<files>
		<file>
			<source>${project.basedir}/src/main/external-resources/META-INF/services/javax.imageio.spi.ImageReaderSpi</source>
			<outputDirectory>META-INF/services</outputDirectory>
		</file>
		<file>
			<source>${project.basedir}/src/main/external-resources/META-INF/services/javax.imageio.spi.ImageWriterSpi</source>
			<outputDirectory>META-INF/services</outputDirectory>
		</file>
	</files>
</assembly>
```
