### ISSUE TITLE
BMP subsampling corrupts image

### ISSUE THREAD

**Issue by bdaum** [haraldk/TwelveMonkeys#335]
Hi Harald,
there seem to be some problems with horizontal subsampling in the BMP reader. Instead of sampling complete pixels single bytes are sampled resulting in the corruption of the image. The Sun BMP reader works well for the attached image.

The invoking code was:

````java
ImageReader reader = readers.next();
try {
    reader.setInput(input);
    ImageReadParam param = reader.getDefaultReadParam();
    param.setSourceSubsampling(2, 2, 0, 0);
    BufferedImage bImage = reader.read(0, param);
} finally {
     reader.dispose();
}
````
I did a quick fix for the 24-bit case in BMPImageReader:readRowByte():

````java
// // Subsample horizontal
// if (xSub != 1) {
// for (int x = 0; x < srcRegion.width / xSub; x++) {
// rowDataByte[srcRegion.x + x] = rowDataByte[srcRegion.x + x * xSub];
// }
// }

// Subsample horizontal  //bd
if (xSub != 1) {
    int sampleSize = rowDataByte.length / srcRegion.width;
    for (int i = 0, m = sampleSize * srcRegion.x, n = srcRegion.x * sampleSize / xSub; i < srcRegion.width
					/ xSub; i++, m += sampleSize * xSub, n += sampleSize) {
        for (int b = 0; b < sampleSize; b++)
            rowDataByte[n + b] = rowDataByte[m + b];
        }
    }
````

This code is not perfect, too. It does not recognize band layouts supplied as parameters. I also have not looked yet at readRowUShort() and readRowInt() but they probably have similar isssues.

Cheers
Berthold
[tatesol.zip](https://github.com/haraldk/TwelveMonkeys/files/869967/tatesol.zip)
Zipped BMP file - GitHub does not accept BMP

**Comment by haraldk** [comment]
Hi Berthold,

Thanks for the suggested fix! I took the liberty to reformat your code. 

This is a known issue (see #289). Unfortunately, the fix is a little more complex, because BMPs can have pixels shorter than one byte (2, 4 and 6 bit palette) in addition to multi-byte (24 or 32 bit) pixels. BMPs are also usually stored "bottom-up" in contrast to most other formats, so we might need to take that into consideration for vertical subsampling. My plan is to fix this before releasing version 3.4.

In the mean time, you can either build a local patched version with your proposed fix, or just continue using the standard Sun/Oracle BMP plugins (the TM plugins only adds support for some very uncommon BMP flavors, so you may not need it at all).

Best regards,

-- 
Harald K
