### ISSUE TITLE
PSD Layer Offset

### ISSUE THREAD

**Issue by JamzTheMan** [haraldk/TwelveMonkeys#336]
First, Thanks for the imageio-psd plugin!

I'm not sure if I'm missing a layer attribute or something but when extracting layer images, they don't seem to retain their offset?

Example: PSD has 2 layers. Layer 1 is a 400x400 image. Layer 2 is a 390x390 image, centered over Layer 1 (with transparent pixels surrounding it).

When I get the image from Layer 2, it returns an image 390x390, but now I've lost it's position in relation to Layer 1? Shouldn't it return an image 400x400 which is the over all size of the PSD canvas? If now, is there a layer "offset" that says where Layer 2 is set at?

**Comment by haraldk** [comment]
Hi Jamz,

The layers contain only the bitmap data that is actually stored. This is by design (and the most natural thing, given how Photoshop actually stores the values). 

The offsets of the layers are available from the `PSDMetadata` which you can acquire using `imageReader.getImageMetadata(0)`. The native metadata format name is `"com_twelvemonkeys_imageio_psd_image_1.0"`. From the native tree, get the `"Layers"` node, which contains a list of `"LayerInfo"` nodes (one for each layer, in the same sequence as the layers exists in the file). The LayerInfo nodes has attributes for `name`, `blendMode`, `opacity` etc, in addition to the offsets you are looking for. The offset attributes are named `top`, `left`, `bottom` and `right`, and contains the offset in pixels (you typically need only top/left, but I guess you can use bottom/right for sanity check).

In code:

````java
ImageReader reader = ...; // Assuming PSDImageReader with proper input etc..

IIOMetadata metadata = reader.getImageMetadata(0);
IIOMetadataNode root = (IIOMetadataNode) metadata.getAsTree("com_twelvemonkeys_imageio_psd_image_1.0");

NodeList layerInfos = root.getElementsByTagName("LayerInfo");
for (int i = 0; i < layerInfos.getLength(); i++) {
    // Layer index corresponds to imageIndex - 1 in the reader, 
    // as imageIndex 0 is the "merged" or "composite layer"
    IIOMetadataNode layerInfo = (IIOMetadataNode) layerInfos.item(i);
    
    // Get layer offsets
    int top = Integer.parseInt(layerInfo.getAttribute("top"));
    int left = Integer.parseInt(layerInfo.getAttribute("left"));
    int bottom = Integer.parseInt(layerInfo.getAttribute("bottom"));
    int right = Integer.parseInt(layerInfo.getAttribute("right"));   
    
    //...store offsets for later use, or process as you like
}
````

Hope that helps,

-- 
Harald K

**Comment by JamzTheMan** [comment]
Ah, Thanks! I had found the top/left attributes yesterday but I did not account for the layer index off by 1 (was using same index I used for the image index).

Works perfectly now, thanks. We can close this issue out as pilot error.

**Comment by JamzTheMan** [comment]
I know this is closed but I seem to be having the issue again...
attributes top, and left are reporting 0 even though an image starts at 21x21 (surrounded by 20 transparent pixels on all sides). I attached a simple sample PSD where the first layer is 191x191 but it only returns an image 169x169 with top & left attributes 0 so I have no idea how much transparency is actually surrounding that layer?

[Frame_transparent Test Good.zip](https://github.com/haraldk/TwelveMonkeys/files/1423543/Frame_transparent.Test.Good.zip)
