### ISSUE TITLE
Is it possible to support Android?

### ISSUE THREAD

**Issue by multidisplayad** [haraldk/TwelveMonkeys#337]
Because on Android, there is not javax.ImageIO package.
So it could not run on.

Could you support it?

**Comment by haraldk** [comment]
While it's certainly technically possible to port some of the plugins to Android (ie. `Bitmap` and `BitmapFactory`-like APIs), this is no small task. Fist of all  because the `javax.imageio` package isn't available, but also as none of the Java2D APIs that we rely on internally are available either.

So, for this project, Android support is clearly out of scope. 


Best regards,

-- 
Harald K
