### ISSUE TITLE
Plugins not detected in standalone JAR but works in Eclipse

### ISSUE THREAD

**Issue by samgrz** [haraldk/TwelveMonkeys#349]
hello
- using latest version 3.3.2
- eclipse neon.2 (4.6.2)
in eclipse, the additional extensions are detected correctly (tif, psd , tga...)
when i export to an executable jar (i made sure all the dependencies are there, and they are in the
generated .jar indeed)
and when i run the app with java -jar app.jar
plugins are not detected (only native jpeg and bmp..)
any clues pls

**Comment by samgrz** [comment]
![eclipse_jar](https://cloud.githubusercontent.com/assets/28727612/26099416/8284c066-3a22-11e7-9c41-0c18ad4d4020.PNG)

in fact when the jars are packaged it works, they do not load if they are extracted separately
look at picture pls, ty

**Comment by haraldk** [comment]
Hi,

Most likely, the problem is that when you extract all the provided JAR files, they will overwrite each others `META-INF/services` entries, which are needed for proper plugin detection. You need to merge these entries somehow, if you extract and package everything as a "flat" JAR. See #327 for a similar issue. 

Best regards,

-- 
Harald K

**Comment by samgrz** [comment]
Hello,
Thank you for prompt reply, nice :)
it turned out that was it.
Thank you very much

Sam

**Comment by haraldk** [comment]
Excellent!

-- 
Harald K
