### ISSUE TITLE
Zero bytes written when converting tiff to jpeg

### ISSUE THREAD

**Issue by mcantrell** [haraldk/TwelveMonkeys#375]
I have some problem tiff images that won't convert to jpeg. It seems most of them were created with image magick. I'm attaching a [full test case](https://github.com/haraldk/TwelveMonkeys/files/1263611/imageio-unknown-type.zip) but here's a snippet of the test which fails:

    @Test
    public void convertTiffToJpeg() throws Exception {
        try (InputStream content = this.getClass().getResourceAsStream("/test.tiff")) {
            BufferedImage source = ImageIO.read(content);
            ByteArrayOutputStream out = new ByteArrayOutputStream();
            ImageIO.write(source, "jpg", out);

            byte[] bytes = out.toByteArray();
            assertTrue("no output bytes were written", bytes.length > 0);

            BufferedImage target = ImageIO.read(new ByteArrayInputStream(bytes));
            assertEquals(source.getHeight(), target.getHeight());
            assertEquals(source.getWidth(), target.getWidth());
            assertEquals(source.getColorModel().getColorSpace().getType(), target.getColorModel().getColorSpace().getType());
        }
    }

The test should fail with "no output bytes were written". I poked around at the source BufferedImage and it looks like the type is 0 (Custom). I wonder if this is the cause.

**Comment by haraldk** [comment]
Hi Mike,

Most likely, your input TIFF files have a bit depth higher than 8 bits/sample (typically, 12, 14 or 16 bits/sample). The one in your attached zip, has 2 channels (gray + alpha), and 16 bits/sample. This is perfectly legal for a TIFF file. But as Java, or the `BufferedImage` class really, doesn't have special support for gray + alpha images, the image type becomes `TYPE_CUSTOM` (or 0) . 

This isn't a problem in itself, but unfortunately, the JPEG plugin doesn't support more than 8 bits/sample (ie. `JPEGImageWriterSpi.canEncodeImage` returns `false`). This is probably because the native `libjpeg` that the JDK uses to write JPEG doesn't support higher bit depths either. When no plugin for the requested format is able to encode the image, no data is written (as you have seen). Also, `ImageIO.write(...)` will return `false` in this case. 

To fix (or rather, work around) this problem, convert the image to a `BufferedImage` representation that has only 8 bits/sample. `TYPE_3BYTE_BGR` or `TYPE_BYTE_GRAY` should work fine, but you'll lose the alpha channel. Alternatively, you can use  `ImageTypeSpecifiers.createGrayscale(8, DataBuffer.TYPE_BYTE, false).createBufferedImage(source.getWidth(), source.getHeight())` method, to create a suitable `TYPE_CUSTOM` image, with gray + alpha. But I'm not sure if the latter will be as compatible with other software as writing without alpha.


Hope that helps,

-- 
Harald K

**Comment by mcantrell** [comment]
Hey Harold,

Thanks for the in-depth explanation. That makes sense.. I'll work around it by converting the image and drop the alpha channel. We won't need it for our processing.
