### ISSUE TITLE
Large TIFF file throws OutOfMemoryError when rotating

### ISSUE THREAD

**Issue by jansohn** [haraldk/TwelveMonkeys#376]
I'm not sure if this is a bug or not. Still wanted to ask if this is normal behavior.

I'm trying to rotate a large TIFF file (13244x18722px, 400dpi, CCITT T.6 compression) by 90° with a 32bit Java on Windows 10. I'm using the latest release `v3.3.2` of TwelveMonkeys.

    BufferedImage rotatedImage = TIFFUtilities.applyOrientation(bufImage, TIFFExtension.ORIENTATION_RIGHTTOP);

And here's the stack trace:

    java.lang.OutOfMemoryError: Java heap space
            at java.awt.image.DataBufferInt.<init>(DataBufferInt.java:75)
            at java.awt.image.Raster.createPackedRaster(Raster.java:467)
            at java.awt.image.DirectColorModel.createCompatibleWritableRaster(DirectColorModel.java:1032)
            at java.awt.image.BufferedImage.<init>(BufferedImage.java:324)
            at sun.java2d.pipe.DrawImage.makeBufferedImage(DrawImage.java:348)
            at sun.java2d.pipe.DrawImage.renderImageXform(DrawImage.java:462)
            at sun.java2d.pipe.DrawImage.transformImage(DrawImage.java:264)
            at sun.java2d.pipe.DrawImage.transformImage(DrawImage.java:210)
            at sun.java2d.pipe.DrawImage.transformImage(DrawImage.java:1085)
            at sun.java2d.pipe.ValidatePipe.transformImage(ValidatePipe.java:230)
            at sun.java2d.SunGraphics2D.drawImage(SunGraphics2D.java:3461)
            at com.twelvemonkeys.image.AffineTransformOp.filter(AffineTransformOp.java:105)
            at com.twelvemonkeys.contrib.tiff.TIFFUtilities.applyOrientation(TIFFUtilities.java:307)

It works when I use a 64bit Java, taking about 2GB of heap space. Anything we could do to reduce the amount of heap space used?

**Comment by haraldk** [comment]
Hi,

I was just about to close this one, as normally, an `OutOfMemoryError` due to a large image isn't usually something we can do anything about... 

However, you shouldn't need 2GB of data for your image, as far as I can see, as 13244x18722 @ 1bit/pixel (I assume this, given the CCITT compression), is only about 30 MB  ... 

It seems several unfortunate events happens here... 

First the native code of `java.awt.image.AffineTransformOp` is unable to rotate the image, and throws an `ImagingOpException`. Not sure why, but could be that it can't process such large images, or perhaps it just runs out of memory too. Or maybe it can't handle black/white images...

Then, the code enters a fallback mechanism we implemented, that uses the standard Java2D pipeline (ie. `Graphics2D` and friends). But for some reason this pipeline creates a temporary image in `TYPE_INT_RGB`, and at the same image dimensions, this is 945 MB...

Not sure if it's fixable, but at least it would be interesting to run it through the debugger, and see if there's anything that can be done. 

Also, technically, if the TIFF is striped or tiled, it could be possible to process one strip/tile at a time, and rewrite the image as a tiled image. But there's no support for this in the current code. 


Best regards,
 
-- 
Harald K

**Comment by jansohn** [comment]
Hi Harald,
thanks for the first analysis! Is there anything I can do to help with this?

Thanks,
Robin

**Comment by haraldk** [comment]
Hi again Robin,

I have some trouble reproducing this problem. Can you send me a sample file you use to create this problem? Rename it to .PNG or link it from dropbox or similar, if you can't attach it to this issue. The following naive approach worked without problems for me:

````java
        BufferedImage image = new BufferedImage(13244, 18722, BufferedImage.TYPE_BYTE_BINARY);
        BufferedImage rotatedImage = TIFFUtilities.applyOrientation(image, TIFFExtension.ORIENTATION_RIGHTTOP);
````

Also, let me know what Java version/vendor you use, and on what platform. The output of:

    $ java -version

...will do.


-- 
Harald K

**Comment by jansohn** [comment]
Hi Harald,
unfortunately I only have confidential TIFF images at the moment. Is there any easy way to make those undecipherable? But I'm not sure that's even necessary since I also experience the same problem with your naive approach mentioned above.

Just to make it clear: with a 64bit Java it doesn't enter the fallback code in my code either but the Java heap space exceeds 2000MB for a short time (observed in the task manager). I'm using a JUnit test case to run my code but it shouldn't make any difference (I'll try nonetheless).

Output of `java -version`
java version "1.8.0_131"
Java(TM) SE Runtime Environment (build 1.8.0_131-b11)
Java HotSpot(TM) 64-Bit Server VM (build 25.131-b11, mixed mode)

**Comment by jansohn** [comment]
OK, this seems to be a simple display error in the Windows 10 task manager. Below is a graph from JVisualVM while rotating the image with a 64bit Java and no additional VM options.

![image](https://user-images.githubusercontent.com/7804514/30117812-9bffedd8-9321-11e7-9fd0-d40101df1ab5.png)

**Comment by haraldk** [comment]
Yes,

I think memory usage for Java processes in Windows task manager being inaccurate is a known issue.

It may be that Java allocates a lot of native memory outside heap for a short period as well. But that's hardly a bug. 

-- 
Harald K

**Comment by Schmidor** [comment]
I believe the "native" case allocates memory outside of Java Heap. This might be the reason why the native case has failed in my tests and why I needed the Graphics2D approach.

Maybe we just need to override AffineTransformOp.createCompatibleDestImage if this method currently always generates TYPE_INT_RGB?

Regards,
Oliver

**Comment by haraldk** [comment]
@Schmidor It creates a new image that has the same color model and raster type as the input, unless a special case: 

````java
if (interpolationType != TYPE_NEAREST_NEIGHBOR &&
     (cm instanceof IndexColorModel || cm.getTransparency() == Transparency.OPAQUE)) {
    image = new BufferedImage(w, h, BufferedImage.TYPE_INT_ARGB);
}
````
