### ISSUE TITLE
OutOfMemory error on TIFF image with corrupt ICC header

### ISSUE THREAD

**Issue by bdaum** [haraldk/TwelveMonkeys#393]
A corrupt ICC header may cause java.awt.color.ICC_Profile to allocate a huge read buffer resulting in an OutOfMemory exception. You may want to catch this in the TIFFImageReader.getICCProfile() like this: 

 catch (CMMException | IllegalArgumentException | **OutOfMemoryError** ignore) { 
        processWarningOccurred("Ignoring broken/incompatible ICC profile: " + ignore.getMessage());
 }

**Comment by haraldk** [comment]
Hi bdaum,

Thanks for reporting! That is actually a good idea. In a container format, like TIFF or JPEG, we already know up-front how large the ICC profile can be. So we could possibly validate that before attempting to decode it, by testing size of the serialized ICC profile (value length in case of TIFF or chunk size(s) in case of JPEG) against the size encoded in the profile itself (first four bytes). 

PS: Do you have a TIFF file with such a profile? Otherwise I guess I could create one. 

-- 
Harald K

**Comment by bdaum** [comment]
That was the culprit: 

https://www.dropbox.com/s/51ihf7r2bvbse5s/20080526-PICT0015.tif?dl=0

**Comment by haraldk** [comment]
Thanks!

I'll have a look.

-- 
Harald K

**Comment by haraldk** [comment]
Issue should be fixed now in latest master.
