### ISSUE TITLE
Support WebP

### ISSUE THREAD

**Issue by FranklinYu** [haraldk/TwelveMonkeys#395]
So far there is no Java implementation of rendering WebP. The only thing available is JNI through the Google library.

**Comment by haraldk** [comment]
Hi Franklin,

Thanks for your interest in TwelveMonkeys ImageIO the library! It would certainly be nice to have support for WebP as well. Unfortunately, it's not a small task to implement. Is this something you or your company would like to help with, either through sponsoring, funding or contributing? 


Best regards,

-- 
Harald K

**Comment by haraldk** [comment]
Hi again, 

Just did a quick test of the [Java VP8 Decoder](https://sourceforge.net/p/javavp8decoder/) I suggested on Softwarerecs.SE. It's a good starting point, but it's a bit rough around the edges. 

We could perhaps talk to the author and see if he's interested in re-licensing to BSD. Or perhaps just fork out the parts we need and keep it under GPL as a separate project. 

-- 
Harald K

**Comment by franklinyu** [comment]
Thank you. The question (for future reference):

[*WebP library for Java?* - Software Recommendations Stack Exchange](https://softwarerecs.stackexchange.com/questions/47212/webp-library-for-java)

**Comment by haraldk** [comment]
Ok.

I asked the author directly for re-licenseing to BSD, as I can't have (L)GPL in the project. We'll see. 

-- 
Harald K

**Comment by darkyellow** [comment]
How about this FreeBSD licensed library ?

https://github.com/jcodec/jcodec/tree/master/src/main/java/org/jcodec/codecs/vpx

**Comment by haraldk** [comment]
@franklinyu Yes, that is exactly the one I suggested above. :-)

.k

**Comment by haraldk** [comment]
@darkyellow Yes, that is exactly the one I suggested above. :-)

.k

**Comment by haraldk** [comment]
Okay,

I've started some work on this, to see how well the Java VP8 decoder would integrate to the project. I'll try to make it available as soon as possible. But a new bugfix release has priority right now.

-- 
Harald K

**Comment by Sami32** [comment]
Nice:+1:

**Comment by Sami32** [comment]
As a news sharing, all the main browsers are now supporting WebP format, when Firefox 65 will be release.

**Comment by FranklinYu** [comment]
I don't think the "Java VP8 Decoder" replied to @haraldk, so JCodec seems to be best bet. Unfortunately I cannot find enough time to work on this currently.

**Comment by haraldk** [comment]
@FranklinYu As I said above, I have received the source code for the Java VP8 decoder, and have started work on this. 

I should probably have stated that, yes, **I have received his permission to re-distribute the Java VP8 decoder under BSD** (JCodec isn't that well suited from my perspective). 

Since then, I have done some more work, and I can now decode "plain" WebP using ImageIO. I will try to push this as a separate branch, as it's fully usable. However, WebP also supports a lossless mode (and alpha channel uses this lossless encoding), and I haven't had the time to fully implement this. As usual, the thing that stops me, is the lack of spare time.


Best regards,

-- 
Harald K

**Comment by davideanderson** [comment]
@haraldk My company may be interested in Sponsoring this feature.  How do we go about discussing that possibility?

**Comment by haraldk** [comment]
@davideanderson That would be great! 

Please email me directly, and we'll see if we can work out the details.

Best regards,

-- 
Harald K

**Comment by haraldk** [comment]
@davideanderson I haven't heard from you... Let me know if you have any trouble reaching me! 

-- 
Harald K

**Comment by davideanderson** [comment]
@heraldk I guess I don't know how to email you, as I don't know how to find your email address.  I tried to reply to the github notification, but that obviously didn't work.  Email me at twelvemonkeys_webp@bulbapp.com

**Comment by FranklinYu** [comment]
@davideanderson His email is included in every commit, such as https://github.com/haraldk/TwelveMonkeys/commit/61bac979333de1245505489d52dd7d85ce607dc9.patch

**Comment by Heraldk** [comment]
@davideanderson You've tagged the wrong person two comments ago. I'm someone else. :)

**Comment by haraldk** [comment]
Don't worry. No need to tag me, I get email notifications anyway...

My email should be in most of the source files too.. No place to hide, I guess.

-- 
Harald K (yes, two a's no e or o ;-)

**Comment by oloflarsson** [comment]
How is this ticket coming along? Support for WebP would be really great 👍.

**Comment by haraldk** [comment]
@oloflarsson It certainly would! :-)

While I really enjoy working on the TwelveMonkeys libraries, I don't have much time to work on it at the moment. And I haven't heard back from anyone wanting to sponsor such development, so I'm uncertain the demand is really there... 

-- 
Harald K

**Comment by oloflarsson** [comment]
@haraldk - What would you consider to be a reasonable donation amount?

I think the demand is absolutely there. I've been searching for an easy to use high performance WebP encoder/decoder to no avail. The best option I have found so far is https://bitbucket.org/luciad/webp-imageio but you have to compile the natives yourself, distribute them, and it lacks an easy to use Maven repository.

How long time do you think it would take for you to build support for both reading and writing WebP in both lossy and lossless formats? What do you want in USD for it? 😄

Would you code it in Java in such case? Or would you use JNI/JNA/JNR together with the Google libwebp natives?

**Comment by haraldk** [comment]
@oloflarsson Reasonable: Depends on a lot of factors, like features, dev. time, usage, etc. But as a minimum I need compensation equal to the amount I bill during my day job, otherwise I won't have enough time to finish it for a while.

This issue mainly covers read support. Write support may come in the future too, but I don't have any plans for it.

Finally, this project has always been about implementing ImageIO plugins in pure Java. This may change when we have Project Panama/JEP-191. But it comes down to the not having too much hassle with native compilations, extra dependencies, missing native dependencies, security issues etc.

-- 
Harald K

**Comment by gotson** [comment]
I would also be happy with a reader only ImageIO plugin for webp ! :)

**Comment by haraldk** [comment]
Fixed via 01a4e551850eabeacd8053f675047ec4169bb985.
