### ISSUE TITLE
OSGi compatibility + SVGProviderInfo classloader lookup

### ISSUE THREAD

**Issue by NMichas** [haraldk/TwelveMonkeys#405]
Although TwelveMonkey is not OSGi-ready, it is relatively easy to port it to OSGi by SPI-fying it using an approach similar to what demonstrated in: https://github.com/Maurice-Betzel/twelvemonkeys-osgi.

However, the call to `isClassAvailable` on https://github.com/haraldk/TwelveMonkeys/blob/633e5cc6a2c0637e508ab334b629b24470071724/imageio/imageio-batik/src/main/java/com/twelvemonkeys/imageio/plugins/svg/SVGProviderInfo.java#L42 prevents OSGi from finding SVG reader (as it returns false). Removing line 42 makes SVG reader available and SVG parsing works fine.

So, is this classloader lookup absolutely necessary, if not could it be removed in a future version?

Thanks.

**Comment by haraldk** [comment]
Hi Nassos,

Thanks for reporting this!

I'm not an OSGi user myself, so I don't know the full implications... Would it help if the line was changed to include the base class for the lookup? This way we make sure we'll use the same class loader that loaded the SPI (which I think was the intention anyway), instead of the current context classloader. Like this:

````java
final static boolean SVG_READER_AVAILABLE = SystemUtil.isClassAvailable("com.twelvemonkeys.imageio.plugins.svg.SVGImageReader", SVGProviderInfo.class);
````
Or is a classloader lookup problematic in itself?

The reason for the lookup of this class, is just a quick check to see if the Batik runtime-dependecies are there. If not, the SPI just logs a message and de-registers itself.



-- 
Harald K

**Comment by haraldk** [comment]
@NMichas Have you had a chance to test my proposed fix yet? 

I see you have already created a patch, but unfortunately, that can't go into the library, as it obviously re-introduces the issue the `SVG_READER_AVAILABLE` variable is supposed to fix.

If the proposed fix don't work for OSGi, I do have an alternative fix that will still solve the original problem and surely work with OSGi, but at a slightly higher run-time cost. 


Best regards,

-- 
Harald K

**Comment by NMichas** [comment]
Hi Harald, didn't know GitHub could detect a comment in another project's commit  and cross-post back to the original project/issue being mentioned :) The patch was for our own project in which we needed a solution immediately, I understand it's not a solution in general for TM. 

I still intend to test your proposal, it sounds like it could solve the problem. Give me a couple of days and I'll get back to this.

**Comment by haraldk** [comment]
@NMichas Have you had a chance to look at this?

If not, I'll implement the suggested fix, and close the issue.

-- 
Harald K

**Comment by haraldk** [comment]
Implemented. Feel free to reopen the case, should you test and find it does *not* solve the issue. 

-- 
Harald K
