### ISSUE TITLE
How to create CMYK format JPEG from RGB BufferedImage

### ISSUE THREAD

**Issue by wangshengyuan2018** [haraldk/TwelveMonkeys#411]
I'm from chinese.
please give me a example,thanks.

**Comment by haraldk** [comment]
Hi,

The TwelveMonkeys `JPEGImageWriter` will automatically write a CMYK `BufferedImage` to a CMYK JPEG. It should be as easy as:

    BufferedImage cmykImage = ...; 
    File cmykJPEGFile = new File(...);

    if (!ImageIO.write(cmykImage, "JPEG", cmykJPEGFile)) {
        System.err.println("CMYK JPEG support not installed");
    }

PS: CMYK JPEG write support is currently unreleased, so you need to build your own version from the current master branch. It will be included in the next (3.4) release.


Best regards,

-- 
Harald K

**Comment by wangshengyuan2018** [comment]
I have make a newest version from the github by using tortoisegit tool and maven tool.I'm very sorry to  interrupting you.
but how can I get a CMYK BufferedImage.If I need to change from the RGB format or I need to replace the BufferedImage file?

**Comment by wangshengyuan2018** [comment]
final String imageFile = "/tmp/page0.png";

    final BufferedImage pngImage = ImageIO.read(new File(imageFile));

    // convert PNG to JPEG
    // http://www.mkyong.com/java/convert-png-to-jpeg-image-file-in-java/
    final BufferedImage rgbImage = new BufferedImage(pngImage.getWidth(), pngImage.getHeight(), BufferedImage.TYPE_3BYTE_BGR);
    rgbImage.createGraphics().drawImage(pngImage, 0, 0, Color.WHITE, null);

    // RGB to CMYK using ColorConvertOp
    // http://stackoverflow.com/questions/380678/how-to-set-icc-color-profile-in-java-and-change-colorspace/2804370#2804370
    final ICC_Profile ip = ICC_Profile.getInstance("icc/USWebUncoated.icc");

    final ColorConvertOp cco = new ColorConvertOp(rgbImage.getColorModel().getColorSpace(), new ICC_ColorSpace(ip), null);

    final BufferedImage cmykImage = new BufferedImage(pngImage.getWidth(), pngImage.getHeight(), BufferedImage.TYPE_3BYTE_BGR);

    cco.filter(rgbImage, cmykImage);

    // Write the result into an bytearray
    final ByteArrayOutputStream baos = new ByteArrayOutputStream();
    ImageIO.write(cmykImage, "JPEG", baos);
    baos.flush();
}
from https://stackoverflow.com/questions/22298328/convert-rgb-png-to-cmyk-jpeg-using-icc-color-profiles
 
the result cmyk jpeg file is blur.If the original picture is 100 ,the cmyk jpeg file is 80. espically the text in the picture is blur.

**Comment by haraldk** [comment]
As I wrote in the comment on that answer:

>  your JPEG is not a CMYK JPEG, it's a normal YCbCr 4:2:2 subsampled JFIF (without embedded ICC profile)

and 

> the 3 channel RGB image cmykImage doesn't even have enough channels to hold CMYK data

That code doesn't really work, if your goal is a CMYK JPEG, as the target image is explicitly created as a 3 channel RGB image. You obviously need 4 channels for CMYK.

Instead of:

````java
BufferedImage cmykImage = new BufferedImage(pngImage.getWidth(), pngImage.getHeight(), BufferedImage.TYPE_3BYTE_BGR);
cco.filter(rgbImage, cmykImage);
````

Try simply:

````java
BufferedImage cmykImage = cco.filter(rgbImage, null);
````
    
**I'm not sure if it works**. If it doesn't, I suggest you ask on StackOverflow, as this isn't really directly related to the library. You might also find inspiration looking at the project's test cases. 

I'm not sure what you mean about blur? JPEG artifacts?

And what is 100 or 80? If you talk about JPEG "quality" setting, the default is 0.75 (75%). If you want to specify a different setting, you need to use the more verbose version of writing, as described in the [readme](https://github.com/haraldk/TwelveMonkeys#advanced-usage). 

Use:

````java
param.setCompressionMode(MODE_EXPLICIT);
param.setCompressionQuality(1f);
````

Best regards,

-- 
Harald K
