### ISSUE TITLE
TIFFImageWriter ignores custom TIFF tags

### ISSUE THREAD

**Issue by matthieu-labas** [haraldk/TwelveMonkeys#416]
Custom TIFF tags (i.e. not in "baseline" or "extended") are ignored in TIFFWriter.

	BufferedImage bi = new BufferedImage(64, 64, BufferedImage.TYPE_BYTE_GRAY);
	byte[] raster = ((DataBufferByte)image.getRaster().getDataBuffer()).getData();
	Arrays.fill(raster, (byte)0xaa);
	TIFFImageWriter writer = (TIFFImageWriter)ImageIO.getImageWritersByFormatName("TIFF").next();
	try (ImageOutputStream os = ImageIO.createImageOutputStream("/tmp/test.tiff")) {
		writer.setOutput(os);
		List<Entry> head = new ArrayList<>();
		head.add(new TIFFEntry(TIFF.TAG_PHOTOMETRIC_INTERPRETATION, TIFF.TYPE_SHORT, 0));
		head.add(new TIFFEntry(1000, TIFF.TYPE_ASCII, "Toto")); // <<-- Custom tag
		TIFFImageMetadata header = new TIFFImageMetadata(head);
		TIFFImageWriteParam param = (TIFFImageWriteParam)writer.getDefaultWriteParam();
		IIOImage image = new IIOImage(bi, null, header);
		writer.write(null, image, param);
	} finally {
		writer.dispose();
	}

A TIFF dump (or hex file dump) shows no `"Toto"` in the resulting file.

**Comment by matthieu-labas** [comment]
In `TIFFImageWriter`, the `entries` map is populated with TIFF fields *queried* from the image metadata (correcting them if needed).

It works if we initialize that map with the initial IFD after creating the map (`TIFFImageWriter.java:180`):

    Map<Integer, Entry> entries = new LinkedHashMap<>();
    for (Iterator<Entry> iter = metadata.getIFD().iterator(); iter.hasNext(); ) {
    	Entry ent = iter.next();
    	entries.put((Integer)ent.getIdentifier(), ent);
    }

**Comment by haraldk** [comment]
Hi Matthieu,

Thanks for reporting! 

I'm aware of the issue (this is basically the same issue as #412), only a specific subset of TIFF tags are carried over into the resulting TIFF file.

The fix is to not create the `entries` map at all, and instead correct the entries related to image/pixel layout in the `convertImageMetadata/getDefaultImageMetadata` methods (probably via the `initMeta` method). Instead of the entries map, we should just use the IFD in the metadata, and write that.

As said in #412, I don't have time to fix it before 3.5, unless someone wants to buy me some time.

In the mean time, feel free to have a go at it. :-)


Best regards,

-- 
Harald K

**Comment by matthieu-labas** [comment]
Ha,sorry I went too quickly through the open issues and didn't check the content.

Anyway, thanks for the hints (I also thought about the `initMeta` method), I'll try to go through what you proposed and see if I can submit you a pull request :)

And thank you, again, for that wonderful piece of software! :)

Matthieu

**Comment by haraldk** [comment]
Should be fixed now, as part of #490.
