### ISSUE TITLE
Some images inside of ICNS are returned as blank

### ISSUE THREAD

**Issue by j-p-sequeira** [haraldk/TwelveMonkeys#418]
Hi there,

First, I want to say that I'm not sure if this is really a problem with TwelveMonkeys. But I'd like to hear your opinion about an issue I'm experiencing with ICNS files.

When reading the ICNS format, the page containing the 256x256 image (usually in the last or first page) always returns a blank (fully transparent) 256x256 image. The ICNS I can find don't seem to go beyond 5 pages and 256x256 pixels, so this may affect other sizes.

When this happens, the `IIOReadWarningListener` receives the following warning:

`2018-04-05 09:01:56 WARNING: [at com.twelvemonkeys.imageio.plugins.icns.ICNSImageReader@3fe9d6ca]: Cannot read JPEG 2000 format in type 'ic08' icon (no reader; installed: [BMP, CUR, DCX, GIF, HDR, ICNS, ICO, IFF, JPEG, JPG, PAM, PBM, PCT, PCX, PFM, PGM, PICT, PNG, PNM, PPM, PSD, RGBE, SGI, SVG, TARGA, TGA, THUMBS, THUMBS DB, TIF, TIFF, WBMP, WMF]) [@meew.FileEntryManager warningOccurred]`

Now, I know that JPEG2000 is not supported. I also know that the `ic08` is for a 256×256 icon, stored  in JPEG2000 or PNG format. I'm just wondering, why would only that page be in JPEG2000? Even thought I know it is entirely possible to be that way (I have no means to check), are the images really in JPEG2000 or when the plugin finds a `ic08` defaults to think it is a JPEG2000?

It would be nice if TwelveMonkeys supported JPEG2000. But while it does not, wouldn't it be better to throw an exception than passing a blank image? What do you think about this?

PS: I've included two ICNS (all the ICNS I can find/generate seem to have the same problem).

[icns-examples.zip](https://github.com/haraldk/TwelveMonkeys/files/1879068/icns-examples.zip)

**Comment by haraldk** [comment]
Hi again,

Yes, the transparent images (with log warning) is a known issue and a deliberate choice. I could have thrown an exception too in this case, which would arguably be more "correct". The rationale is simply  that a blank image would be more useful in the cases where you actually needed an icon, than an exception.

The `ICNSImageReader` inspects the data stream, and should correctly determine the image format based on that (either JPEG 2000 or PNG), when applicable. See [Wikipedia: Apple Icon Image format](https://en.wikipedia.org/wiki/Apple_Icon_Image_format) for more info on the internal formats/sizes used in the format. It's quite different from a Microsoft ICO if you know that format. Quite a few sizes may be in "JPEG 2000 or PNG" format.

PS: Note that if you actually install a JPEG 2000 ImageIO plugin (or are on ~~OS X~~ macOS and have the `sips` command line tool), the `ICNSReader` will correctly read these icons too.


Best regards,

-- 
Harald K

**Comment by haraldk** [comment]
The "current" (unreleased, but it does exist) TwelveMonkeys ImageIO JPEG 2000 plugin is in limbo at the moment, due to the weird license/patent issues of the original JJ2000 code its based on, and lack of anyone to contact to work things out. I've been trying for a while, but basically, I've given up. The code is also quite slow and inefficient, so it's maybe not such a great loss. 

The other option is to write one form scratch. And to be honest, that is not a small task. While I really enjoy working with the library, it doesn't pay my rent... So, it won't happen until either: I happen to work for a project that needs JPEG 2000 support in my day job (unlikely at the moment),  I find  unlimited amounts of spare time (with two kids, *extremely* unlikely) or someone actually pays me to do it or donates working code (it does actually happen sometimes).


Best regards,

-- 
Harald K

**Comment by haraldk** [comment]
Closing for now.

-- 
Harald K
