### ISSUE TITLE
QuickDraw (PICT) Support for Glider Pro images

### ISSUE THREAD

**Issue by lbordowitz** [haraldk/TwelveMonkeys#423]
I'm trying to remake an old Macintosh game called Glider Pro, and this tool has already been invaluable. Using the normal "Read/Write Buffered Image" pattern, I've translated QuickDraw images from [this folder](https://github.com/lbordowitz/glider_pro/tree/7cbcec1b6a349f819e25b2b4f286ceab39d34a45/_raw_Sprites) into PNG images in [this folder](https://github.com/lbordowitz/glider_pro/tree/7cbcec1b6a349f819e25b2b4f286ceab39d34a45/Sprites). Thank you!

I do have a couple problematic images. On a Mac, you can open PICT images in the "Preview" program. You'll notice subtle differences (a [transparent sun in this picture](https://github.com/lbordowitz/glider_pro/blob/7cbcec1b6a349f819e25b2b4f286ceab39d34a45/Sprites/1000.PICT.png) where the corresponding picture has it white), to complete failures in rendering ([this sprite selection](https://github.com/lbordowitz/glider_pro/blob/7cbcec1b6a349f819e25b2b4f286ceab39d34a45/Sprites/1011.PICT.png) is particularly egregious), to Java exceptions in conversion (for instance, `150.PICT` and `151.PICT` threw exceptions, though I don't really need those images).

These pictures come from the [resource file](https://github.com/softdorothy/glider_pro/blob/master/Glider%20PRO.r) provided in the [open sourced Glider Pro](https://github.com/softdorothy/glider_pro) repository, where the hex provided in each resource is extracted into raw bytes as separate files.

The goal of this issue is to improve PICT parsing with these images as a test bed. If they render the same, or even similar, to the way they do on a Mac's Preview, that would constitute "done". This is a large issue; it ought to be broken down into fixing each image, or maybe opcodes functionality missing/maligned to render the images properly.

I know some Java development, and I am able to build and use the SNAPSHOT version of `imageio-pict`. Point me to some resources, and I can try to send you some PRs.

Caveat: The project is licensed under GPL; including them as test cases in this repository might affect the open source licensing.

**Comment by lbordowitz** [comment]
Update:

If we change [this line](https://github.com/haraldk/TwelveMonkeys/blob/4839c61f5c57f9b611198c0f30580df37beaa3ed/imageio/imageio-pict/src/main/java/com/twelvemonkeys/imageio/plugins/pict/PICTUtil.java#L267):

```colors[index] = color.getRGB();```

And change it to use the loop's index `i`:

```colors[i] = color.getRGB();```

then the image `1011.PICT` renders beautifully! It looks like the color table sets the index to `0` for every color, instead of incrementing it color-by-color. I haven't the foggiest why this should be the case, but this fixes the blacked-out screen. It also helps explain why there are small white colors here and there; those are using colors from index `0`, which is the last color stored when using this code.

My only concern is that this may stymie backwards compatibility. In the rare case that the indexes of the color table are not stored consecutively, maybe it would be better if the logic went something like "use consecutive indices if the given index has already been written to / the index is zero."

**Comment by haraldk** [comment]
Hi Larry,

Thanks! 

Seems you have found some very good test images for the reader! The PICT format seems to be very closely related to the QuickDraw API from older Macintosh OSes. The reader is originally based on some old code (Java 1.2, `Image` API) that was donated to the project long time ago. The original code implemented only a limited set of features of the PICT format. Because of this, I started implementing a complete Java QuickDraw API (`QuickDrawContext`) and rewrite the reader to use this API, but it never got fully done, due to the time needed and the limited value (most PICTs only use one of the bitmap copy functions and can be read by the current reader anyway). Feel free to continue this work! I'll try to help if I can.

And thanks for looking into some of issues! I think you have found a bug in the index color reading, and by re-reading the spec it seems that "index or other value" really should be an index into some pre-defined color table. Seems we can just ignore it, at least as long as there is an RGB value in the "true color" field.

Unfortunately, the documentation that I used for writing the API seems to have vanished from Apple's support pages (it's an old outdated API, so it makes sense). It might be possible to contact Apple and ask for it, otherwise we'll have to stick with what we have and otherwise try to reverse-engineer.  

About the licensing issue, I think we can use a couple of the images for test cases under "fair use". But it's always nice to ask the license holders for permission.  :-)


Best regards,

-- 
Harald K

**Comment by haraldk** [comment]
Hi again,

I just pushed a fix that corrects some of the issues:

1. The index issue you found, that messed up the index color model (no test image was harmed by ignoring the index from the stream, so I just applied your fix).
2. Another bug in the same method, creating a color model with transparent color at index 1, instead of an opaque one (the transparent sun).
3. The EOFException in 150/151.PICT

There are still some images that can't be read:
1003.PICT (EOFException)
3968.PICT (IIOException: Found unknown opcode: 0xcccc)
3969.PICT (IIOException: Found unknown opcode: 0xcccc)
3995.PICT  (EOFException)

As far as I can tell, the rendering otherwise looks good for the remaining images (but I haven't compared all images side-by-side). 


-- 
Harald K

**Comment by haraldk** [comment]
Ok,

I have now implemented some missing opcodes, and  everything seems to *read* fine without exceptions. 😀

There are still some minor rendering issues (translation problem, regarding context frame vs source and destination rect I think), as seen 4999.PICT, where the bottom part of the image overwrites the top, instead of being appended at the bottom. There are some TODOs in the code regarding this, which you might want to look into. 

There may be more rendering issues as I still haven't compared all images side-by-side, you should probably to that, and report back.


-- 
Harald K

**Comment by haraldk** [comment]
PS: Found a good resource, an [archived version of the old Apple documentation for QuickDraw](http://mirror.informatimago.com/next/developer.apple.com/documentation/mac/QuickDraw/QuickDraw-2.html).

**Comment by lbordowitz** [comment]
So 4999.PICT is the bitmask for the glider sprites, found in 3999.PICT (and 3976, 3974). Prior to this most recent change which fixed every other image, this render worked. In fact, if you look closely, you'll notice that the bitmasks for "left-facing on fire" state are written to the top of the image, instead of towards the bottom like they're supposed to be.

You can close this issue any time you would like. I've gotten all the sprite resources I need, and then some! Thank you for all your help.

**Comment by haraldk** [comment]
Excellent! 

I fixed the last offset/translation issue as well, now everything seems to work fine. 😀
Thank you for reporting and providing feedback along the way! 

-- 
Harald K
