### ISSUE TITLE
Samsung camera image triggers javax.imageio.IIOException with TwelveMonkeys installed

### ISSUE THREAD

**Issue by davidekholm** [haraldk/TwelveMonkeys#428]
Once I have the TwelveMonkeys libs in my classpath (v3.3.2) I cannot load this JPEG panoramic JPEG image anymore (created with a Samsung camera):

https://testing.jalbum.net/testimages/20180407_161928.jpg

Both the TwelveMonkeys reader and the standard reader now crashes with the following error:

javax.imageio.IIOException: Not a JPEG file: starts with 0x5a 0x17

Without TwelveMonkeys libraries in the classpath, the standard ImageIO JPEG reader reads the image fine.

**Comment by haraldk** [comment]
Hi David,

These panoramic Samsung "JPEG" images are unfortunately a bit problematic... 

See https://forums.adobe.com/thread/2131432, https://us.community.samsung.com/t5/Galaxy-S-Phones/Popular-software-unable-to-open-S7-panoramic-images/td-p/52788, etc. 

They are not really JPEGs, as they are breaking some rather fundamental parts of the JPEG specification ("byte-stuffing", inserting a 0-byte after a 0xFF within the entropy coded data), causing rather random decoding errors, due to decoders misinterpreting the entropy data with JPEG stream markers. I've come across some that don't read using the standard reader, but works in TwelveMonkeys, some that works in both, some in none, and now this one that only works using the standard reader. 

In my testing, using the standard reader with the linked image, produces a warning: "Invalid SOS parameters for sequential JPEG" (+ an exception "javax.imageio.IIOException: JFIF APP0 must be first marker after SOI" trying to read the thumbnail).

The latest TwelveMonkeys 3.4-SNAPSHOT gives the same warning, then fails with "javax.imageio.IIOException: Unsupported JPEG process: SOF type 0xcd". 

It actually fails *after* fully decoding the image, so it's possible to read it like this:

    int width = reader.getWidth(imageNo);
    int height = reader.getHeight(imageNo);
    Iterator<ImageTypeSpecifier> types = reader.getImageTypes(imageNo);
    BufferedImage image = types.next().createBufferedImage(width, height);
    param.setDestination(image);
    try {
        reader.read(imageNo, param);
    }
    catch (IOException ignore) {
        // Log warning?
    } 

Not sure if this is practical for you though... 

I might look into it in more depth at some time, to see if this is fixable in a reliable way. Until then, the best solution is that Samsung fixes their encoder, and stops creating these malformed JPEGs.


Best regards,

-- 
Harald K

**Comment by davidekholm** [comment]
Thanks for replying so quickly Harald!
The thing is, if I don't have the TwelveMonkey's libraries loaded, I can use the ordinary JPEG reader to read this image fine, like this: BufferedImage bi = ImageIO.read(pathToBrokenImage);
but once the TwelveMonkey's libraries are loaded, the standard JPEG reader fails too (with the error you described). If you can at least work out that aspect, the we can use the standard reader for these broken images.

**Comment by haraldk** [comment]
When you say "the standard JPEG reader fails too", when the TwelveMonkeys JARs are on class path, do you mean that

    BufferedImage bi = ImageIO.read(pathToBrokenImage);

fails? This is expected, because we make sure the TwelveMonkeys JPEG reader is ordered before the standard one (otherwise, installing the plugin would have had no effect in most cases). 

If you want a different behaviour (ie. using the standard reader instead), you need to reset the order of the readers. 

If you mean something else, please specify/show the code you use. 😀


-- 
Harald K

**Comment by davidekholm** [comment]
No, I actually iterate through the readers in the order they appear, but it fails when attempting to load the image straight from the Oracle/Sun reader too:
// Pseudo code:
Iterate reader in readers
   BufferedImage bi = reader.read(0, param);

**Comment by haraldk** [comment]
Do you properly reposition or re-open the input between each attempt? Without more code, I can only guess... But if the first plugin fails to read an image, it will leave the input in an undefined state (ie. you can't know how much data has been read), so that is a likely problem.

I find it hard to believe that installing the TwelveMonkeys JPEG plugin should otherwise interfere with the standard plugin. But I will of course have to, if you send me a failing test case or other self contained code sample that shows this behaviour. 😉 

The following code works for me:

```java
public class SamsungBug {
    public static void main(String[] args) throws IOException {
        BufferedImage image = readWithFallback(new File(args[0]));
        System.err.println("image: " + image);
    }

    private static BufferedImage readWithFallback(File file) throws IOException {
        try (ImageInputStream input = ImageIO.createImageInputStream(file)) {
            Iterator<ImageReader> readers = ImageIO.getImageReaders(input);

            ImageInputStream stream = input;

            while (readers.hasNext()) {
                try {
                    ImageReader reader = readers.next();

                    System.out.println("Trying " + reader.getClass());

                    reader.setInput(stream);

                    return reader.read(0, reader.getDefaultReadParam());
                }
                catch (IOException e) {
                    System.err.println("ERROR: " + e.getMessage());

                    // A read error occurred, need to reposition stream
                    try {
                        stream.seek(0);
                    }
                    catch (IndexOutOfBoundsException | IOException ignore) {
                        // A somewhat clunky fallback, in case the reader did flush the stream
                        // causing the seek to fail. 
                        // We'll close the stream (if it's not the original stream),
                        // and create a new one for the next iteration.
                        if (stream != input) {
                            stream.close();
                        }

                        stream = ImageIO.createImageInputStream(file);
                    }
                }
            }
        }

        return null;
    }
}
```

Best regards,

-- 
Harald K

**Comment by haraldk** [comment]
Hi David,

Did the above proposed solution work for you?

-- 
Harald K

**Comment by davidekholm** [comment]
Thanks Harald, it did! It's embarrassing that I forgot that seek(0) call before attempting the next reader. I'm all fine now :-)

**Comment by haraldk** [comment]
Excellent! No worries. :-)

-- 
Harald K
