### ISSUE TITLE
Could not initialize class com.twelvemonkeys.imageio.color.ColorSpaces

### ISSUE THREAD

**Issue by boris-petrov** [haraldk/TwelveMonkeys#437]
Ever since upgrading to 3.4, I keep getting sporadic exceptions during the initialization of our software. This is the stacktrace:

```
Could not initialize class com.twelvemonkeys.imageio.color.ColorSpaces
java.lang.ExceptionInInitializerError
        at com.twelvemonkeys.imageio.color.YCbCrConverter.buildYCCtoRGBtable(YCbCrConverter.java:57)
        at com.twelvemonkeys.imageio.color.YCbCrConverter.<clinit>(YCbCrConverter.java:77)
        at com.twelvemonkeys.imageio.plugins.jpeg.JPEGImageReader.convertYCbCr2RGB(JPEGImageReader.java:1276)
        at com.twelvemonkeys.imageio.plugins.jpeg.JPEGImageReader.readImageAsRasterAndReplaceColorProfile(JPEGImageReader.java:502)
        at com.twelvemonkeys.imageio.plugins.jpeg.JPEGImageReader.read(JPEGImageReader.java:388)
        at java.desktop/javax.imageio.ImageIO.read(ImageIO.java:1468)
        ...
Caused by: java.lang.NullPointerException
        at java.desktop/sun.java2d.cmm.lcms.LCMS.getProfileSize(LCMS.java:67)
        at java.desktop/java.awt.color.ICC_Profile.getData(ICC_Profile.java:1332)
        at com.twelvemonkeys.imageio.color.ColorSpaces.<clinit>(ColorSpaces.java:105)
        ... 18 more
```

This doesn't happen every time, it's pretty sporadic. Any ideas? I'm on Linux if that matters. Please tell me if you need any more information.

**Comment by haraldk** [comment]
Hi Boris,

Thanks for reporting!

That is actually very annoying. :-/

In 3.4 I added a static initializer block to try to work around [JDK-6986863](https://bugs.openjdk.java.net/browse/JDK-6986863). All it does is:

````java
ICC_Profile.getInstance(ColorSpace.CS_sRGB).getData();
```` 

I was under the impression that this was safe, as some users have reported back that it successfully made the JDK bug go away. But apparently, it doesn't work always, and instead trigger a different JDK bug.

Can you tell me the full version of the Java JRE you are on? At least that's interesting to know. 
You should probably also file a bug report to Oracle/OpenJDK, if you haven't already done so. 

A quick-fix would probably be to just wrap the above in a `try/catch`, but in the case of an exception, that means that the initial JDK-6986863 is still there...


Best regards,

-- 
Harald K

**Comment by haraldk** [comment]
Possibly related: [JDK-8058973](https://bugs.openjdk.java.net/browse/JDK-8058973).

**Comment by boris-petrov** [comment]
Hi, thanks for the support! That's my Java version:

```
%  java --version
java 10.0.2 2018-07-17
Java(TM) SE Runtime Environment 18.3 (build 10.0.2+13)
Java HotSpot(TM) 64-Bit Server VM 18.3 (build 10.0.2+13, mixed mode)
```

I haven't filed a bug to JDK... should I? No one else has encountered this bug since this workaround that you've mentioned?

**Comment by haraldk** [comment]
Thanks,

Yes, I think you should. It may be a duplicate, but at least it's good for the JDK team to see that people still run into problems with the LCMS implementation.

There hasn't been reported any bugs for the 3.4 version so far, so I guess not. But it's likely that more people will in the near future. 

I'll make a fix soon. 

-- 
Harald K

**Comment by boris-petrov** [comment]
But why didn't this happen in `3.3.2`?

**Comment by boris-petrov** [comment]
I see, thanks. I saw that you committed workarounds, any plans for a "quick" release?

**Comment by haraldk** [comment]
@boris-petrov  I'll see what I can do. I have one more thing I'd like to provide a patch for, and then I'll make a 3.4.1 bugfix release.

-- 
Harald K

**Comment by haraldk** [comment]
@boris-petrov Bugfix release (3.4.1) is out. Should be in Maven Central sometime soon.

-- 
Harald K

**Comment by boris-petrov** [comment]
Thanks, seems to work fine for now! Thank you for the support!

**Comment by sghpjuikit** [comment]
I am still using this workaround:
```
        ICC_Profile.getInstance(ColorSpace.CS_sRGB).data
        ICC_Profile.getInstance(ColorSpace.CS_PYCC).data
        ICC_Profile.getInstance(ColorSpace.CS_GRAY).data
        ICC_Profile.getInstance(ColorSpace.CS_CIEXYZ).data
        ICC_Profile.getInstance(ColorSpace.CS_LINEAR_RGB).data
```
Code is called when application starts and fixes the issue because the problem originates from color profiles being lazily loaded and subsequent concurrent modification error in multithreaded environment. As far as I understand this, the triggers color profile initialization and can be put in a safe single-threaded place to avoid potential issues.

I'm also triggerring all color spaces, because I think all of them are lazy loaded.

**Comment by boris-petrov** [comment]
@sghpjuikit - thanks for the suggestion! I guess the `.data` in the end is a typo? There is no such field.

**Comment by haraldk** [comment]
@boris-petrov Different language, I guess. In Java, you would write `.getData();`.

.k

**Comment by sghpjuikit** [comment]
@boris-petrov 

Ah, my bad, I ignorantly posted Kotlin code. haraldk is correct.

**Comment by thhart** [comment]
I had this problem in 3.4.2 recently for the first image being encoded. The initializer workaround fixes it. I only want to note this here, since I am not sure if the Twelvemonkeys should cover this or not.

**Comment by haraldk** [comment]
@thhart I believe that if you still get this issue with versions 3.4.1 and later, you should also see some debug information printed to the console, referring to JDK-6986863.

In any case, using the initializer workaround is probably your safest option, as you can write that into your application startup logic and handle it safely there. TwelveMonkeys is a library, and I have no control over when the application starts or when a profile is accessed for the first time.

-- 
Harald K

**Comment by momomo** [comment]
I have to say @sghpjuikit suggestion seems to work for us. We are also in a highly concurrent environment when this starts being used. Perhaps the static block is executed in one thread, not finishing, and then another thread skips the static block and goes for the action? Is that even possible? Would a static block lock out another thread? If not, @haraldk this would mean the error is indeed yours and could be fixed by approaching this a bit differently or at least wrap the code in the static block in a method preload(); and a) make that code callable (public static method fine)  or b) ensure that code ensures completion ( global wide locks that checks for this and waits (not great)). For the first I think what @sghpjuikit right now is fine for us.

**Comment by haraldk** [comment]
@momomo 

> I have to say @sghpjuikit suggestion seems to work for us.

Yes. Yet, this is basically the same fix that you are complaining about. 😕

Anyway, as I point out above, TwelveMonkeys is a library. And we can't make any guarantees about the *order* you do things in *your* application. And order matters here.

Putting the code block in your application startup is safer because it makes sure it's done before anyone accesses the color profiles. This avoids the inconsistent state that you may otherwise run into (and it seems this happens often in your application). In this case, the static init block in `ColorSpaces` will just execute happily and basically do nothing. 

As I have tried to tell you several times now, that code does not cause or trigger the bug especially, it just *reports* it. 

> Perhaps the static block is executed in one thread, not finishing, and then another thread skips the static block and goes for the action? Is that even possible? Would a static block lock out another thread until static block completion? I expect it to.

You can read about this in detail in [JLS section 12.4. Initialization of Classes and Interfaces](https://docs.oracle.com/javase/specs/jls/se7/html/jls-12.html#jls-12.4). 

But the TL;DR version is: Static initialization is done by a single thread, and no other threads can access the class before it's completed. So, no, that is not possible. And it works as you expect, unless there is a bug in the JVM.

>  could be fixed by approaching this a bit differently or at least wrap the code in the static block in say a method preload(); and a) make that code callable (public static method fine) or b) ensure that code ensures completion ( global wide locks that checks for this and waits (not great)). For the first I think what @sghpjuikit right now is doing right now is fine for us.

Technically, you could probably just do a `Class.forName(..)` somehow reference the `ColorSpaces.class` in your application startup, to force class initialization.  But I would say that `ICC_Profile.getInstance(ColorSpace.CS_sRGB).data()` is better, as it doesn't give you a hard dependency on the TwelveMonkeys library. 

Also, if you have a better fix or workaround for the problem, try it out and let us know! This is open source, after all... 😀 


-- 
Harald K

**Comment by mrserb** [comment]
I suggest trying JDK17 where this problem should be fixed and report any new issues you may found.

**Comment by momomo** [comment]
To us, it seems that the static code block is not actually completing nor blocking any further execution of other methods or constructors occurring in multithreaded environment. 

Static block is only executed once, another thread comes in and possibly gets an instance of that same class, while the static block is still executing. Seems like a JVM issue. 

Perhaps known, i do not know. 

Like If you invoke a static or instance method while the static block is executing are you forced to wait? 

When we initialize the static block manually prior to starting the multithreaded environment it seems to disappear. 

Seems like a JDK issue nonetheless, however, this lib could extract the static block to a static method and allow for it to be executed manually prior.

**Comment by haraldk** [comment]
@momomo 

**I'm sorry, but I find our conversion extremely challenging, as you seem to mostly ignore what I write, and never read the pointers to the documentation that I give (if you did, I would think you would not continue ask the same questions over). 😕**

But I'll try anyway...

> Like If you invoke a static or instance method while the static block is executing are you forced to wait?

If you read the link to the JLS above (or even my short version), it should be clear that the static block is executed before any client code gets access to the class. *No access to the class, members or methods, from any thread, can happen until it is done.*

For JVM issues, this is not the place to discuss or report them (but I doubt that is the case here).

> Seems like a JDK issue nonetheless, however, this lib could extract the static block to a static method and allow for it to be executed manually prior.

Yes, it could. But I made the decision I didn't make this method available as API, as you can easily make the same thing using standard API and no dependencies. And you would have to write some code in any case. Finally, I want to remove this "functionality" at some point, as the bug is fixed. This would be harder if it was API.

But if you really want to have this dependency in your code, there's nothing stopping you from doing something like:

    ColorSpaces.getColorSpace(ColorSpaces.CS_ADOBE_RGB_1998);

or even:

    Class.forName("com.twelvemonkeys.imageio.color.ColorSpaces"): 

Both of these will initialize the class, and run the static initializer block. 


In any case, upgrading to Java 17, as suggested by Sergey would be a better option.


-- 
Harald K

**Comment by momomo** [comment]
_If you read the link to the JLS above (or even my short version), it should be clear that the static initializer block is executed before any client code gets access to the class. No access to the class, members or methods, from any thread, can happen until it is done._

It does not matter what you or they state, since that is the observed behavior. I too am surprised by this and it appears under certain conditions the static block in a concurrent initial access leads to this issue. 

I was not and still not asking any questions. I am merely stating. Since you can not explain it any better than I do, and the static block is constant there is no reason to defend anything that is as flaky as this. The static block is failing at certain times, why? No difference in input, right? In our case, I've noticed that we have several threads attempting the initial access around the same time, and when we decided to stop doing that, we have not encountered this issue anymore. 

Just stating. 

Yes, I could do that but instead we do this in an instance class: 

static { preload(); } public static void preload() {
        ICC_Profile.getInstance(ColorSpace.CS_sRGB).getData();
        ICC_Profile.getInstance(ColorSpace.CS_PYCC).getData();
        ICC_Profile.getInstance(ColorSpace.CS_GRAY).getData();
        ICC_Profile.getInstance(ColorSpace.CS_CIEXYZ).getData();
        ICC_Profile.getInstance(ColorSpace.CS_LINEAR_RGB).getData();
    }

**Comment by haraldk** [comment]
> It does not matter what you or they state, since that is the observed behavior.

Yes, it very much matters. The JLS is the very foundation of how Java works, and If we cannot rely on that being true, hardly anything, even the standard libraries would work correctly. 

I would very much like to have a look at your observations, if you can share them or somehow reproduce the results of multiple threads accessing the static initializer block of a non-initialized class. 

> I was not and still not asking any questions.

Now you are just trolling. 

> Yes, I could do that but instead we do this [...]

Excellent! That is what we have suggested as a workaround for the JDK bug [since the first report of the issue](https://github.com/haraldk/TwelveMonkeys/issues/402#issuecomment-354650122). It's still the only workaround I know of, pre JDK 17.

-- 
Harald K

**Comment by momomo** [comment]
Which is why you should just offer this method in the library, so we don't have to add that logic. 

_public static void preload() {
        ICC_Profile.getInstance(ColorSpace.CS_sRGB).getData();
        ICC_Profile.getInstance(ColorSpace.CS_PYCC).getData();
        ICC_Profile.getInstance(ColorSpace.CS_GRAY).getData();
        ICC_Profile.getInstance(ColorSpace.CS_CIEXYZ).getData();
        ICC_Profile.getInstance(ColorSpace.CS_LINEAR_RGB).getData();
    }_
