### ISSUE TITLE
JPEG - wrong colors (pink)

### ISSUE THREAD

**Issue by leobr29** [haraldk/TwelveMonkeys#448]
Hi,

I am using TwelveMoneys for opening JPEG files (resize when necessary) and rewrite with metadata.

The problem is that some images are pink in output. I have seen that it seem to be a current problem but I do not understand why in my case.

Here is what I do (simplest case without resizing) :
```
reader = ImageIO.getImageReadersBySuffix("jpg").next();
is = ImageIO.createImageInputStream(new File("input.jpeg"));
reader.setInput(is);

BufferedImage originalImage = reader.read(reader.getMinIndex());
			
//read metadata
IIOMetadata metadata = reader.getImageMetadata(reader.getMinIndex());

//get writer
Iterator<ImageWriter> iter = ImageIO.getImageWritersByFormatName("jpeg");
writer = iter.next();

//writer parameters
JPEGImageWriteParam iwParam = (JPEGImageWriteParam) writer.getDefaultWriteParam();
iwParam.setCompressionMode(ImageWriteParam.MODE_COPY_FROM_METADATA);
iwParam.setOptimizeHuffmanTables(true);

FileImageOutputStream ios = new FileImageOutputStream(new File("output.jpeg"));
writer.setOutput(ios);
writer.write(null, new IIOImage(originalImage, null, metadata), iwParam);

//Then close all streams
```

When I try to write output without metadata : `writer.write(null, new IIOImage(originalImage, null, null), iwParam);` the output JPEG are fine (not with pink coloration).

Here is a ZIP file containing 2 JPEG Image [input_files.zip](https://github.com/haraldk/TwelveMonkeys/files/2455658/input_files.zip) (nok.jpg file is pink after rewrite and ok.jpg is fine).

Do you think you can find an explanation to solve my problem ?

Best reguards,
Leo.

**Comment by haraldk** [comment]
Hi Leo,

This is an "interesting" issue... Writing the image without the metadata works fine, but I assume that you want to retain it. So I had a look at the metadata...

The "nok.jpg" sample file does contain a broken Exif segment. For example, the thumbnail IFD contains `37510/UserComment: 6 (SHORT), 37510/UserComment: 72 (RATIONAL), 37510/UserComment: 72 (RATIONAL), 37510/UserComment: 2 (SHORT), 37510/UserComment: 4084 (LONG), 37510/UserComment: 2863 (LONG)`... Duplicate tag ids is not allowed in TIFF, so this is clearly incorrect. It seems that the Tag IDs should be (as in the good sample): `259/Compression: 6 (SHORT), 282/XResolution: 72 (RATIONAL), 283/YResolution: 72 (RATIONAL), 296/ResolutionUnit: 2 (SHORT), 513/JPEGInterchangeFormat: 4084 (LONG), 514/JPEGInterchangeFormatLength: 2863 (LONG)]`. However, removing it didn't help...  So, there seems to be something else strange going on.

I'm still not exactly sure what is wrong with the original metadata, but I managed to write a JPEG that looked okay. I did it by creating a new set of default metadata for the image, then copying the Exif data into that metadata before writing. This seems to work fine for both OS X (Preview) and Windows (File Explorer/Photo Viewer) for displaying both metadata and image. 

A minor issue with this approach is that the images are now no longer Exif JPEGs, but rather JFIF JPEGs (with Exif metadata). Most users won't notice or care, but some applications may behave differently. It's possible to fix this as well, but it requires quite a bit more massaging of the metadata (ie., you must remove the APP0/JFIF segment from the "jpegVariety", make sure the APP1/Exif segment is the first segment in the "markerSequence", and re-add any APP2/ICC_PROFILE segments as "unknown" segments after the Exif), and in most cases you won't need it.

Here's the code:

````java
try (ImageInputStream is = ImageIO.createImageInputStream(new File(args[0]))) {
    ImageReader reader = ImageIO.getImageReaders(is).next();
    System.err.println("reader: " + reader);
    reader.setInput(is);

    BufferedImage originalImage = reader.read(reader.getMinIndex());
    System.err.println("originalImage: " + originalImage);

    // Read metadata
    IIOMetadata metadata = reader.getImageMetadata(reader.getMinIndex());

    // Get writer
    ImageWriter writer = ImageIO.getImageWriter(reader);
    System.err.println("writer: " + writer);

    // Writer parameters
    JPEGImageWriteParam iwParam = (JPEGImageWriteParam) writer.getDefaultWriteParam();
    //iwParam.setCompressionMode(ImageWriteParam.MODE_COPY_FROM_METADATA); // Copy from metadata is the default
    iwParam.setOptimizeHuffmanTables(true);

    // Create new set of default metadata for the image
    IIOMetadata newMetadata = writer.getDefaultImageMetadata(ImageTypeSpecifier.createFromRenderedImage(originalImage), iwParam);

    IIOMetadataNode newRoot = (IIOMetadataNode) newMetadata.getAsTree(newMetadata.getNativeMetadataFormatName());

    Node markerSequence = newRoot.getElementsByTagName("markerSequence").item(0); // Exactly 1
    Node firstChild = markerSequence.getFirstChild();

    IIOMetadataNode originalRoot = (IIOMetadataNode) metadata.getAsTree(metadata.getNativeMetadataFormatName());

    // Move any Exif segments from the original to the new metadata
    NodeList unknowns = originalRoot.getElementsByTagName("unknown");
    for (int i = 0; i < unknowns.getLength(); i++) {
        IIOMetadataNode unknown = (IIOMetadataNode) unknowns.item(i);

        // 225 is APP1, these MAY contain other data than Exif. Inspect the user object, and see if the first bytes are "Exif\0" to be sure.
        if ("225".equals(unknown.getAttribute("MarkerTag"))) {
            unknown.getParentNode().removeChild(unknown);
            markerSequence.insertBefore(unknown, firstChild); // Must be first segment to be valid Exif
        }
    }

    // Update metadata
    newMetadata.mergeTree(metadata.getNativeMetadataFormatName(), newRoot);

    try (ImageOutputStream ios = ImageIO.createImageOutputStream(new File("output.jpg"))) {
        writer.setOutput(ios);
        writer.write(null, new IIOImage(originalImage, null, newMetadata), iwParam);
    }
    //Then close all streams (automatically, using try-with-resource)
}
````


Best regards,

-- 
Harald K

**Comment by leobr29** [comment]
Hi haraldk,

Thanks a lot for your quick fix, you really help me ! I have some other images that turned pink after rewritting metadata, I hope that it is this problem for all of them. 

Is it possible simply identify programatically when this issue will appear and then execute your fix ? Because I have a very large amount of images to process and it is a tiny part that turned pink.

Best regards,
Leo.

**Comment by haraldk** [comment]
Sorry,

I didn't find the real cause of the issue (other than "something about the metadata, outside the Exif"), so so I don't really know how to identify these files (other than a visual inspection; "the colors look strange"). 

But feel free to dig further into this! 

I would suspect you'll find something in the DHT or DQT tables, or their order, that causes the issue.  It seems the tables somehow confuses the native code (the JRE's bundled libjpeg) to write the colors incorrect. The exact same thing happens if you don't use my JPEG plugin, AFAICS. 


Best regards,

-- 
Harald K

**Comment by leobr29** [comment]
Hi haraldk,

I've tried to fix and it works well except I loose IPTC metadata of my images. 

Do you know how to get IPTC metadata (allready defined in some images) and add them to the new set of metadata ?

Best regards,
Leo.

**Comment by haraldk** [comment]
Hi Leo,

Yes, you can use the same approach as outlined above, by copying APPx (unknown) segments from the old to the new markerSequence. IPTC metadata is contained in the APP13/"Photoshop 3.0" segment. 

The above was just provided as a quick PoC. For production code, you probably want to copy over the APP1/XMP segment (identified by "http://ns.adobe.com/xap/1.0/") too. And the APP2/ICC_PROFILE. At least.


Best regards,

-- 
Harald K

**Comment by leobr29** [comment]
Thanks for your help haraldk, 

So if I well understanding : `NodeList unknowns = originalRoot.getElementsByTagName("unknown");` contain APPx segments.

Indeed, it will be interessant to copy other segments. But I do not find how I can known that : `// 225 is APP1` except because you tell me ? 

In my current example, I have another attribut value 237 how do I know what it is ? Just inspecting java object not seem to help me to find this information, is there an documentation or something ? 

Best reguards,
Leo.

**Comment by haraldk** [comment]
Unfortunately, no. 

The metadata format is documented in [JPEG Metadata Format Specification and Usage Notes](https://docs.oracle.com/javase/9/docs/api/javax/imageio/metadata/doc-files/jpeg_metadata.html). So the APP segments are split between `app0JFIF`, `app2ICC`, `app14Adobe` (the important ones for *image decoding*) and `unknown` segments. And not all `unknown` segments are necessarily APPn semgents.

APPn segments are identified by the markers `0xFFE0` (APP0) to `0xFFEF` (APP15). But the above metadata format will only use the last byte in he "MarkerTag" attribute, and encode it as a String containing the unsigned int value (great, huh?). So, 225 == 0xE1, which corresponds to 0xFFE1 which again is the APP1 marker. 237 is 0xED, or APP13 marker, correct. And 226 is APP2. 

Whether or not it is the segment you are looking for, depends on the null-terminated ASCII string at the start of the segment. You can get the contents of the segment as a byte array from the "user object" of the tag (again, as specified above). But most likely, you can just copy over any "unknown" APPn segment ("MarkerTag"s 224-239). 

The `app14Adobe` element can be copied also, I think. The tricky part is the `app0JFIF` (which can only be the first marker) and the `app2ICC` (which is a subelement of `app0JFIF`, but can also be contained in non-JFIF files, and can span multiple segments due to size). This is unfortunately a limitation in the metadata format/implementation, but it can be worked around.

For a more in-depth understanding on how this all works together, you may want to see the JFIF specification, the Exif specification, the ICC specification on embedding ICC profiles in JPEG, the IPTC specification on embedding IPTC in JPEG, the Adobe XMP specification and perhaps the Adobe Photoshop File Formats specification (there *is* more). Unfortunately, the true general solution you seem to be looking for, is quite complex, and is way beyond the scope of the help I can give here. You may have better luck asking on Stack Overflow for example, but I still think it will be hard.

If you like, I can assist you in designing and implementing a solution, as a paid service. If you are interested in this, contact me on my personal email, and we can probably work out the details.


Best regards,

-- 
Harald K

**Comment by leobr29** [comment]
Yeah it's quite complex, anyway thanks for your time.

I may come back to you if I do not solve my issues.

Thanks a lot, I think that you can close the issue.

Best regards,
Leo.

**Comment by haraldk** [comment]
Okay. Good luck! 

Closing the issue for now! :-)

-- 
Harald K
