### ISSUE TITLE
Support for PNG files

### ISSUE THREAD

**Issue by Lonzak** [haraldk/TwelveMonkeys#456]
I just wanted to use TM instead of imageIO however then realized that it doesn't support PNG.
Maybe the integration of pngj (https://github.com/leonbloy/pngj) is possible to support writing PNG files?
Or is there a plan to support PNGs in the future?

**Comment by Schmidor** [comment]
The TwelveMonkeys plugins are only additions to the existing ImageIO plugins, it doesn't overwrite the existing readers/writers. You should still be able to use the default plugin for PNGs using ImageIO.read/write/etc. Althought the default PNG writer isn't compressing very efficiently.

**Comment by haraldk** [comment]
I believe @Schmidor already answered this. PNG support in ImageIO is built-in, and I haven't seen any need to replace it. 

I believe also that the problem with compression speed (the built-in `PNGImageWriter` always uses the highest/slowest compression) has been addressed in a later Java version (fixed in [Java 9](https://bugs.openjdk.java.net/browse/JDK-6488522), with backports seemingly available, see comments). 

Is there anything specific about PNG that you need support for, that isn't already available in the JRE?


Best regards,

-- 
Harald K

**Comment by Lonzak** [comment]
Ah ok I didn't know that TM is (only (not meant in a disrespectful sense)) an addition to the existing imageIO implementation. I somehow pictured it as an alternative implementation like apache imaging and the like.
I just found the backported libs as you mentioned myself so my problem with the speed is somehow solved (even though pngj still offers a 20% performance gain).

**Comment by haraldk** [comment]
@Lonzak No worries! ;-)

I'm not exactly sure what compression setting PNGJ uses, but I think you should get similar performance by using the same compression setting through the `ImageWriteParam`. Try setting the compression mode to `MODE_DISABLED`, **or** setting the compression mode to `MODE_EXPLICIT` and setting the compression quality to `1.0`. 

Anyway, I'm closing this issue for now. 


Best regards,

-- 
Harald K

**Comment by Lonzak** [comment]
I did the tests for every equivalent compression level and for each pngj is 20% faster... There is some description of the lib [here](https://code.google.com/archive/p/pngj).

**Comment by haraldk** [comment]
As they both use the same underlying compression (ie. ZLib through `java.util.zip.Deflater`), that's interesting. It might be worth looking into what the `PNGImageWriter` wastes that 20% time on, and perhaps file a bug/enhancement request or a PR to the OpenJDK project...

PS: That code.google.com link is obsolete, the project is now hosted on Github (as in the initial post).

-- 
Harald K
