### ISSUE TITLE
CMYKA Tiff output

### ISSUE THREAD

**Issue by hvolks** [haraldk/TwelveMonkeys#457]
Hi
I am trying to create a CMYK with Alpha , as a simple test I have an exisiting TIF, read and try and write
read seems fine but on write I get an error.

	 BufferedImage myPicture = ImageIO.read(new File("C:\\Develop\\cmyka.tif"));
		 
		 if (!ImageIO.write(myPicture, "tif", new File("C:\\Develop\\cmyka1.tif"))) {
			   // Handle image not written case
			}

I always get 
Exception in thread "main" java.lang.IllegalArgumentException: Can't determine PhotometricInterpretation for color model: ColorModel: #pixelBits = 40 numComponents = 5 color space = com.sun.media.imageioimpl.common.BogusColorSpace@43301423 transparency = 1 has alpha = false isAlphaPre = false

Am I being to basic with the write command and need the TIFFImageWriterSpi? 
Question is CMYKA Tiff output possible ?

I thought I would start with a sample and work backwards.

Then I have 2 separate image a CMYK and a Mask, I need to combine into a BufferedImage and write this as a CMYKA

**Comment by haraldk** [comment]
You are using a `BufferedImage` with a `BogusColorSpace`, and according to it's [source code](https://github.com/dcm4che/jai-imageio-core/blob/master/src/main/java/com/sun/media/imageioimpl/common/BogusColorSpace.java#L73) it returns an unexpected type (`TYPE_4CLR` or `TYPE_5CLR` I guess, in your case), instead of `TYPE_CMYK`, as the TIFF writer expects/supports. 

If that happens from the code above though, I think that you are using a 3rd party TIFF `ImageReader` (ie. JAI or some fork), as the TwelveMonkeys `TIFFImageReader` will not create images of this kind. 

The following code will write a CMYKA TIFF file:

    public static void main(String[] args) throws IOException {
        ComponentColorModel cmykaCM = new ComponentColorModel(ColorSpaces.getColorSpace(ColorSpaces.CS_GENERIC_CMYK),
                                                              true, false, Transparency.TRANSLUCENT, DataBuffer.TYPE_BYTE);
        BufferedImage image = new BufferedImage(cmykaCM, cmykaCM.createCompatibleWritableRaster(100, 100), cmykaCM.isAlphaPremultiplied(), null);

        Graphics2D g = image.createGraphics();
        try {
            g.setColor(Color.ORANGE);
            g.setRenderingHint(RenderingHints.KEY_ANTIALIASING, RenderingHints.VALUE_ANTIALIAS_ON);
            g.setRenderingHint(RenderingHints.KEY_COLOR_RENDERING, RenderingHints.VALUE_COLOR_RENDER_QUALITY);
            g.fillOval(0, 0, image.getWidth(), image.getHeight());
        }
        finally {
            g.dispose();
        }

        ImageIO.write(image, "TIFF", new File("cmyka.tiff"));
    }

And the following will create a similar image (copy) again;

    public static void main(String[] args) throws IOException {
        BufferedImage image = ImageIO.read(new File("cmyka.tiff"));
        System.err.println("image: " + image);
        ImageIO.write(image, "TIFF", new File("cmyka_copy.tiff"));
    }

All works for me, using only the TwelveMonkeys TIFF plugin. So, I think the above problem is with the class path, and mixing incompatible TIFF plugins. 

--- 

But it might be possible to add support for the `TYPE_nCLR` color spaces in the writer though, if this is important... It will have to be treated as `PhotmetricInterpretation: 5` ("Separated"), without inks, as we don't know what the colors should represent. Perhaps allow specifying it through the metadata.


Best regards,

-- 
Harald K

**Comment by hvolks** [comment]
Thanks all OK now, it was the order of readers..
