### ISSUE TITLE
TIFFImageReaderSpi doesn't correct its SPI order when vendor is Oracle, not Apple

### ISSUE THREAD

**Issue by njorogle** [haraldk/TwelveMonkeys#461]
TIFFImageReaderSpi corrects the lookup order only of the vendor of the existing spi starts with "Apple".  Now that tiffs are natively supported in JRE 9 this pairwise ordering needs to be in place without the "Apple" caveat (like JPEGImageReaderSpi).

I don't know the full history, but I imagine that OSX probably supported TIFFs in older JREs, but it wasn't standard on other OSes which is perhaps why this was added.

My hack to push the Oracle SPIs to the end is pretty ugly:

```
IIORegistry iioRegistry = IIORegistry.getDefaultInstance();
ImageReaderSpi lastGood = null;
List<ImageReaderSpi> oracle = new ArrayList<>();
Iterator<ImageReaderSpi> it = iioRegistry.getServiceProviders(ImageReaderSpi.class, true);
while (it.hasNext()) {
    ImageReaderSpi sp = it.next();
    if (sp.getClass().getName().contains("TIFF")) {
        if (sp.getVendorName().startsWith("Oracle")) {
            oracle.add(sp);
        } else {
            lastGood = sp;
        }
    }
}
if (lastGood != null) {
    for (ImageReaderSpi sp : oracle) {
        iioRegistry.setOrdering(ImageReaderSpi.class, lastGood, sp);
    }
}
```

**Comment by haraldk** [comment]
Hi @njorogle,

This is actually [fixed in the latest master](https://github.com/haraldk/TwelveMonkeys/blob/master/imageio/imageio-tiff/src/main/java/com/twelvemonkeys/imageio/plugins/tiff/TIFFImageReaderSpi.java#L63), and will be part of the next release, along with more Java 9+ compatibility fixes. 

You may want to build your own SNAPSHOT version from master, or backbort those changes in the mean time.


Best regards,

-- 
Harald K

**Comment by njorogle** [comment]
Great to know it's fixed, thanks.  I'm a long way from shipping, so I'll just hack it for now.
