### ISSUE TITLE
PSD/PSB Write Support

### ISSUE THREAD

**Issue by DavidPDP** [haraldk/TwelveMonkeys#483]
Hi.

I'm trying to save an image in PSB format, as follows:

`ImageIO.write(image,"psb",output);`

this same line of code I debugged it with other formats and it works correctly. I searched at the characteristics of the library but doesn't find one that allows writing in this format, is there a specific reason? This is because I'm processing images in PSB format and I want to save them in the same format.

**Comment by haraldk** [comment]
Hi David,

As mentioned in [PSD - Adobe Photoshop Document](https://github.com/haraldk/TwelveMonkeys#psd---adobe-photoshop-document), there is only read support for the PSD format (same goes for PSB or Photoshop "large file format"). 

For software in general, it's the other way around; you implement something for a specific reason (ie. you need it). So that is the reason, no one has ever had a strong enough need to write out `BufferedImage`s in PSD or PSB format. :-)

I would generally advice against PSD or PSB as formats for file interchange, simply because they are proprietary formats. You can keep pretty much any image from a PSD in a TIFF (or perhaps BigTIFF in your case, if the output files are above 4 GB), so I would recommend that.

I could probably add minimal support for PSD/PSB to the library in a day or two. That would include writing only the composite layer, perhaps a thumbnail if provided, and no layer or other fancy Photoshop features that there's no Java support for anyway. Maybe limited metadata support. Would this be enough for your use case?  

If so, and you really need the PSD/PSB support, get in touch and we can try to work out the details.


Best regards,

--
Harald K

**Comment by DavidPDP** [comment]
Hi.
Excuse me, since I do not have much experience in image processing, I didn't know that TIFF was more general and not exclusive. Obviously, for good practice and versatility it's better to keep it as TIFF. Only that I saw that NASA saves its images, of more than 4 GB, in PSB format so I considered it a versatile format. So I don't really need this new feature.
Thanks.

**Comment by haraldk** [comment]
No worries,

PSD and PSB are certainly very versatile formats, and there might be good reasons for using them. I can only guess at NASA's motivation, perhaps that PSB is more standardized than BigTIFF (which is just an unofficial extension proposal to TIFF, with Adobe owning both specifications).

-- 
Harald K

**Comment by davidbrazilparker** [comment]
I found a workaround for this as I had a similar use case.

Kotlin version since that is what I'm using:
```
val photoshopBufferedImage = ImageIO.read(File("/path/to/file/image.psd"))

//Do something to edit my BufferedImage

ImageIO.write(editedBufferedImage,"tiff",File("/path/to/file/updated_image.psd"))
```

This solution allows me to write to PSD file format with an altered version of my original PSD file.

**Comment by haraldk** [comment]
@davidbrazilparker Thanks! 

This is basically what I suggested above, using TIFF as output format. The fact that you write it with a ".psd" file extension does not change the fact that the output will be a TIFF file (it may fool Windows to use Photoshop to open it though :-) ). There is no PSD write support (yet).


Best regards,

-- 
Harald K
