### ISSUE TITLE
Unsupported BitsPerSample for Bi-level/Gray TIFF (expected 1, 2, 4, 8, 16 or 32): 15

### ISSUE THREAD

**Issue by yhorndt** [haraldk/TwelveMonkeys#484]
I am aware that bit is not up to spec. But we encountered some issues when we resized 8-bit grayscale multi-page tiffs to a lower dpi count with imagemagick. The tiffs turned out to have 15-bit depth. While otherwise fine to open and work on, imageIO (twelvemonkeys) gave the error as stated in the title.

I'm aware that the root of the issue is another application, but in the end we still encountered the issue.

**Comment by haraldk** [comment]
Hi,

As the exception message says, the `BitsPerSample` value 15 is simply not supported by the library. There's nothing wrong with anything, it's just not supported. 

However, I don't understand why ImageMagick would change your 8 bit images to 15 bit, just because you changed the DPI. That does not make sense to me. As DPI is just metadata, there's no reason to modify the image data at all Also, 15 bit is a very odd bit depth for grayscale, regardless of any conversion (unless you used some setting to force this)... So I'd look into your ImageMagick commands and see if you could tweak the output there. The best would probably be to keep the 8 bits, second best would be to output 16 bits. 

If you send me a sample TIFF file with the described issue (ie. gray 15 bit), I can look into how much work it would be to add support.


Best regards,

-- 
Harald K

**Comment by yhorndt** [comment]
How it can happen that the bps changed, no idea.
convert -units PixelsPerInch "test.tiff" -resample 72 "test_72dpi.tiff"
This is the command used, so nothing crazy.

I'll try to come up with a sample tiff over the weekend. Unfortunately I cannot send the tiffs involved, as they contain client information.
I can't reproduce it on my local machine, so I'll have to see if it's somehow the combination of an old imagemagick version and centos distro, as it is running on the server.

Thank you for the reply!

**Comment by haraldk** [comment]
Hi,

Despite extensive searching, I've not come across a single 15 bit per sample TIFF file... I'll close this issue for now. Feel free to reopen if you can provide a (small) sample image! I think adding support should be fairly simple after all...


Best regards,

-- 
Harald K
