### ISSUE TITLE
Unable to load PSD and TIFF plugins together in Gradle

### ISSUE THREAD

**Issue by davidbrazilparker** [haraldk/TwelveMonkeys#486]
build.gradle with both plugins:

dependencies {
compile 'com.twelvemonkeys.imageio:imageio-tiff:3.4.1'
compile 'com.twelvemonkeys.imageio:imageio-psd:3.4.1'
}

Available readers (TIFF not shown):
psd
PSD
JPG
jpg
bmp
BMP
gif
GIF
WBMP
png
PNG
JPEG
wbmp
jpeg

-------

build.gradle with only TIFF plugin:

dependencies {
compile 'com.twelvemonkeys.imageio:imageio-tiff:3.4.1'
}

Available readers (TIFF shown):

JPG
jpg
tiff
bmp
BMP
bigtiff
gif
GIF
WBMP
png
PNG
BIGTIFF
JPEG
BigTIFF
tif
TIF
TIFF
wbmp
jpeg

-------

build.gradle with only PSD plugin:

dependencies {
compile 'com.twelvemonkeys.imageio:imageio-psd:3.4.1'
}

Available readers (TIFF not shown):

JPG
jpg
psd
PSD
bmp
BMP
gif
GIF
WBMP
png
PNG
JPEG
wbmp
jpeg

**Comment by haraldk** [comment]
Hi David,

Are you re-packaging the plugin JARs in any way (by creating a common "fat" JAR containing all your applications classes, for instance)? If you are, it is important that you configure the packaging step to merge entries of `META-INF/services/*`, otherwise you'll end up with only one (the last one?) of the plugins registered. This is of course just a guess, based on the symptoms you describe. I don't have much details on either your code or your build here...

Other than that, there's no known issues with using the PSD and TIFF plugins together (I do it all the time), or using Gradle for builds (I use Maven myself, but there shouldn't be a difference). 


Best regards,

-- 
Harald K

**Comment by haraldk** [comment]
@davidbrazilparker , did you solve this problem? 

I'm assuming you did, given your thumbs up and no further comments on the issue. :-)

If not, please re-open and add details about your Gradle build.


Best regards.

-- 
Harald K
