### ISSUE TITLE
Resample filter error resizing BufferedImage of type RGB_555 or RGB_565

### ISSUE THREAD

**Issue by Zardoz89** [haraldk/TwelveMonkeys#501]
Adapting some old code base to use Twelve Monkeys resampling filter (using esampleOp.FILTER_MITCHELL), I found a particular BMP file that throws an error : 

```
java.lang.IllegalArgumentException: Raster IntegerInterleavedRaster: width = 63 height = 32 #Bands = 3 xOff = 0 yOff = 0 dataOffset[0] 0 is incompatible with ColorModel DirectColorModel: rmask=7c00 gmask=3e0 bmask=1f amask=0
	at java.awt.image.BufferedImage.<init>(BufferedImage.java:622)
	at com.twelvemonkeys.image.ResampleOp.createCompatibleDestImage(ResampleOp.java:821)
	at com.twelvemonkeys.image.ResampleOp.filter(ResampleOp.java:574)
```

Debuging, I saw that the BufferedImage generated by Twelve Monkeys BMP ImageIO plugins, is  TYPE_USHORT_555_RGB with DirectColorModel. I suspect that the same problem would rise with a BufferedImage of TYPE_USHORT_565_RGB, but I didn't test it.

I workaround this problem, converting it to TYPE_INT_RGB

I adjunct the BMP 
[bmp_rgb16.zip](https://github.com/haraldk/TwelveMonkeys/files/3682533/bmp_rgb16.zip)

**Comment by haraldk** [comment]
Hi Luis,

Thanks for reporting! 

I don't think the resampling filter is implemented to support `TYPE_USHORT_555_RGB` or `TYPE_USHORT_565_RGB`. Could also be that the problem is the `ImageUtil.createCompatibleWritableRaster`, it might need a special case for this.

If you have some time to dig more into this and perhaps create a PR with a test case, that would be great! Otherwise I'll probably look into it at some point.

In the mean time, using your suggested workaround should be fine, after all it's not a very common type of image. 


Best regards,

-- 
Harald K

**Comment by Zardoz89** [comment]
> In the mean time, using your suggested workaround should be fine, after all it's not a very common type of image. Yeah! It's a weird BMP test case taht I grab from here : http://entropymine.com/jason/bmpsuite/

**Comment by haraldk** [comment]
Okay, 

I think I have found the culprit. Seems to be a JDK bug, where the `ImageTypeSpecifier.Packed` constructor unconditionally sets the number of bits to 32, even if for the `TYPE_USHORT_555_RGB` and `TYPE_USHORT_565_RGB` types, the number of bits are obviously 16...

I'll create a workaround at some point.


Best regards,

-- 
Harald K
