### ISSUE TITLE
Trying to clear the Metadata on an JPEG

### ISSUE THREAD

**Issue by coolboy** [haraldk/TwelveMonkeys#531]
Hi All,

Does any one know how to safely do that?

I am using the 
```
    BufferedImage image = ImageIO.read(...);
    ImageIO.write(image, "jpg", new File("..."));
```

It's working but the output size changes a lot comparing to the original file.

I  just want to remove the Metadata but keeping else the same.

I also tried below
```
    // Create input stream
    ImageInputStream input = ImageIO.createImageInputStream(bais);

    // Get the reader
    Iterator<ImageReader> readers = ImageIO.getImageReaders(input);

    if (!readers.hasNext()) {
      throw new IllegalArgumentException("No reader");
    }

    ImageReader reader = readers.next();

    reader.setInput(input);

    // ImageReadParam param = reader.getDefaultReadParam();

    // Finally read the image, using settings from param
    IIOImage image = reader.readAll(0, null);

    ImageWriter writer = ImageIO.getImageWriter(reader);
    JPEGImageWriteParam wparam = (JPEGImageWriteParam)writer.getDefaultWriteParam();
    wparam.setCompressionMode(MODE_COPY_FROM_METADATA); // This modes ensures closest to original compression
    wparam.setOptimizeHuffmanTables(true);

    // Create output stream
    ImageOutputStream output = ImageIO.createImageOutputStream(new File("..."));

    writer.setOutput(output);
    writer.write(null, image, wparam); // Write image along with original meta data
```

But the output file color is different, see below
![image](https://user-images.githubusercontent.com/404691/75841553-e1952100-5d82-11ea-9019-e35b41704623.png)

Attached is the original and swapped file
![color_wrong](https://user-images.githubusercontent.com/404691/75841618-0ab5b180-5d83-11ea-9705-0c489e4d5613.jpeg)
![org](https://user-images.githubusercontent.com/404691/75841626-1012fc00-5d83-11ea-95e0-354e4e85de5f.jpeg)

Anyone knows why the color changed? Or what's the right way to remove the Metadata but keeping everything else the same?

**Comment by j-p-sequeira** [comment]
Hmm, I believe that `writer.write(null, image, wparam);` will keep the metadata (probably with incorrect Huffman Tables) since the IIOImage carries it. 

You can try this: 
`image.setMetadata(null);` 

or maybe a more drastic: 
`writer.write(null, new IIOImage(image.getRenderedImage(), null, null), wparam);`

But then you won't be able to use `MODE_COPY_FROM_METADATA`. You'll have to read the JPEG quality/compression (I don't know if it is possible) and set it explicitly. I think the problem lies in retaining the JPEG compression and not doing a re-compression of the whole image (even with same compression value, I'm not sure the image will not change, since it is doing a compression over the already compressed image, and setting it to max quality might increase file size and probably change the image anyway).

**Comment by haraldk** [comment]
Hi @coolboy,

First of all, I believe these kinds of questions are better asked on Stack Overflow or similar, as it is not specific to the library, and will reach a broader audience there.

@j-p-sequeira Is correct, using `reader.readAll(..)` will read all the metadata, so that isn't what you need in this case. Or at least you would need to filter out the parts of the meta data you would like to "clear". But in any case, as JPEG is a lossy format, I think it would be better to avoid the decode/encode cycle entirely. After all, you just want to clear the image metadata, and leave the pixel data alone.

I would suggest using something like ExifTool for this, but if you want to do it in Java, you could probably find a Java port of ExifTool (Java wrappers exists too). Or look at the `JPEGSegmentUtil` of the TwelveMonkeys library, to get an idea on how to parse a JFIF stream (it's actually quite straight forward), and filter out the segments you need.


Best regards,

-- 
Harald K

**Comment by coolboy** [comment]
Thanks all for the reply and let me dig deeper of this issue, will update once I find out how to do it

**Comment by haraldk** [comment]
Closing this for now.

-- 
Harald K
