### ISSUE TITLE
Licence detail

### ISSUE THREAD

**Issue by shubham1809** [haraldk/TwelveMonkeys#536]
Can we use this project for a commercial project? does it require any license?

**Comment by haraldk** [comment]
The license is linked from the GitHub project page, but I add a [direct link here](https://github.com/haraldk/TwelveMonkeys/blob/master/LICENSE.txt) as well. This the standard 3-clause BSD open source license, which allows commercial use as long as you otherwise comply with the license. 

-- 
Harald K
