### ISSUE TITLE
Some JPEGs render corrupted

### ISSUE THREAD

**Issue by Queatz** [haraldk/TwelveMonkeys#543]
Trying to figure out what's going on here.  After editing photos taken on my phone on my phone, they seem to render corrupted, especially when using the ResampleOp to downsize. (This was not the case using the standard JPEG writer - I can't use it because it doesn't handle EXIF metadata.)

![-1925998058790547064806027006748534617165911785079979936](https://user-images.githubusercontent.com/540620/82774124-8fa3ea80-9e09-11ea-9e9e-b9c75128731c.jpg)

Edited (corrupted?) and original JPEGs:
https://drive.google.com/open?id=1By24FPq27Dvt4FIwWGEl-18r_2jCTMSc

**Comment by haraldk** [comment]
Hmmm... 

Do you have the code to reproduce the problem you see here? I’ve never seen this kind of corruption happening in my images, so it’s hard to say.. The actual JPEG encoding is still done by the standard writer even if I make some tweaks to make it do the right thing about meta data etc. 

Will investigate when I see the code. 


Best regards,

— 
Harald K

**Comment by Queatz** [comment]
@haraldk This is my code.  Note the usage of "Metadata" in the code here is not the EXIF, it's info about the scaled images stored in a database.

```java
private ImageMetadata getScaledImageMetadata(@NotNull ImageMetadata metadata, Point size) {
        ImageReader reader;
        IIOImage imageWithExif;
        BufferedImage image;

        try {
            reader = this.image(getFileFromName(metadata.file));
            image = this.scale(reader.read(0), size.x, size.y > 0 ? size.y : (int) (size.x / getAspectRatio(metadata)));
            imageWithExif = new IIOImage(image, null, reader.getImageMetadata(0));
        } catch (IOException e) {
            e.printStackTrace();
            return null;
        }

        FileImageOutputStream outputStream = openOutputStream(metadata.path, metadata.name, size);

        try {
            ImageWriter writer = ImageIO.getImageWriters(ImageTypeSpecifier.createFromRenderedImage(image), reader.getFormatName()).next();

            writer.setOutput(outputStream);
            writer.write(imageWithExif);
            outputStream.close();
        } catch (IOException e) {
            e.printStackTrace();
            return null;
        }

        return getImageMetadata(metadata.path, size);
    }

    private ImageReader image(File file) throws IOException {
        ImageInputStream iis = ImageIO.createImageInputStream(file);
        ImageReader reader = ImageIO.getImageReaders(iis).next();
        reader.setInput(iis);
        return reader;
    }

    private BufferedImage scale(@NotNull BufferedImage imageToScale, int requestedWidth, int requestedHeight) {
        if (requestedWidth == 0 || requestedWidth == imageToScale.getWidth()) {
            return imageToScale;
        }

        if (requestedHeight == 0) {
            requestedHeight = imageToScale.getHeight() * (requestedWidth / imageToScale.getWidth());
        }

        return new ResampleOp(requestedWidth, requestedHeight, FILTER_LANCZOS)
                .filter(imageToScale, null);
    }
```

**Comment by Queatz** [comment]
A little more investigation revealed 2 things:

1. Removing the metadata causes the image to render fine.
2. I've noticed this error when running the tests:

```
javax.imageio.IIOException: Missing Huffman code table entry
	at com.sun.imageio.plugins.jpeg.JPEGImageWriter.writeImage(Native Method)
	at com.sun.imageio.plugins.jpeg.JPEGImageWriter.writeOnThread(JPEGImageWriter.java:1067)
	at com.sun.imageio.plugins.jpeg.JPEGImageWriter.write(JPEGImageWriter.java:363)
	at com.twelvemonkeys.imageio.plugins.jpeg.JPEGImageWriter.write(JPEGImageWriter.java:162)
```

Which looks to be a crash in a native method.

**Comment by Queatz** [comment]
I was able to make it work using `JPEGImageWriteParam.setOptimizeHuffmanTables(true)`

Should this maybe be the default? :)  Lots of running around.

**Comment by haraldk** [comment]
Thanks for digging deeper into this on your own time and reporting your findings back! That does help a lot when searching for the root of the problem!

Based on your findings and "cure", it seems like there is something wrong with the huffman tables in the metadata. 

Using `setOptimizeHuffmanTables(true)` will force the writer to generate new huffman tables. The default however, is to use the ones present in the metadata (if it's there), otherwise the writer will supply standard huffman tables. If I'm right, removing the tables from the metadata should also make the image render just fine with no further changes. 

Optimized tables are "better" (ie. will create smaller file size), but take more time to compute, which is probably why the option is disabled by default. It has no effect on image quality.

If this situation is detectable, it would probably be a good idea to make sure the tables are either discarded or replaced with standard ones before passing them on to the encoder, inside the `write` method of the `JPEGImageWriter`. Feel free to dig a little more into this! :-)


Best regards,

-- 
Harald K

**Comment by Queatz** [comment]
It's probably due to reusing the metadata from the original image on a scaled down version of it.  My hunch would be that if the actual size of the image differs from the metadata width / height, then the tables need to be optimized.
