### ISSUE TITLE
 Adding TIFF plugin to Ivy dependencies doesn't download `Core`

### ISSUE THREAD

**Issue by nanthony21** [haraldk/TwelveMonkeys#562]
I have the following line in my Ivy dependencies

```<dependency org="com.twelvemonkeys.imageio" name="imageio-tiff" rev="3.6"/>```

when I use Ivy to fetch dependencies it gets
 - common-lang-3.6.jar
 - common-io-3.6.jar
 - common-image-3.6.jar
 - imageio-metadata-3.6.jar
 - imageio-tiff-3.6.jar

But it doesn't get:
 - imageio-core-3.6.jar

This ultimately results in a `ClassDefNotFoundError`.

Looking at the log from fetching dependencies I don't see any mention of `imageio-core-3.6.jar`

Do I need to add another dependency to Ivy or is there something wrong with the

**Comment by nanthony21** [comment]
I did a bit more testing and found that this also happens for the JPEG plugin. It also happens for older versions.

I don't know much about Maven but one thing that stood out to me is that `imageio-core` is listed as a dependency twice on the website.

https://mvnrepository.com/artifact/com.twelvemonkeys.imageio/imageio-tiff/3.6


Fortunately I can still get everything to download properly by just adding `imageio-core` to my list of dependencies.

**Comment by haraldk** [comment]
Hi Nick,

I have never used Ivy, so I can't help much with that I'm afraid... The dependencies seem to work fine for Maven users. `imageio-core` is also a dependency of `imageio-metadata`, so even it wasn't explicitly declared (which it is), it should still be in the list via transitive dependencies.

The reason imageio-core is listed twice, is because it has two artefacts the TIFF plugin depends on, the JAR (`imageio-core-3.6.jar`) and the test JAR (`imageio-core-3.6-tests.jar`, using `test-jar` classifier). The test JAR should probably also have `test` scope in that page. Not sure why it doesn't...

My guess is that Ivy for some reason does not understand the `test-jar` classifier, and ends up omitting the dependency altogether. But that's just guess. 

-- 
Harald K

**Comment by nanthony21** [comment]
Thanks Harald,

I don't know enough about Ivy to approach fixing this. My work around of adding `core` as it's own dependency seems to be working.
