### ISSUE TITLE
How do you use this library to generate hundreds of megapixels of TIFF image that larger than your computer's memory

### ISSUE THREAD

**Issue by mesmerizeBy** [haraldk/TwelveMonkeys#570]
any idea？

**Comment by haraldk** [comment]
Hi,

**I believe this issue/question is more like multiple feature requests in disguise, some of which are way outside scope of this library.** So I'll close it. But if you would like to look more into specific needs, the use case for this, or provide ideas on how you would like to implement them, we might make it possible one day. :-)

First of all, TIFF the file format can only support files up to 4 GB, due to its unsigned 32 bit file offsets. I believe most computers nowadays have more than 4 GB memory, so one requirement would be to write BigTIFF files (or perhaps some other format, like PSB?). Currently the library "only" supports writing normal TIFF files. Adding support for BigTIFF is probably  doable in a couple of days though, for someone who has the time and skills. 

Second, the ImageIO API that this library provides plug-ins for, is designed around the Java 2D imaging API, which uses `BufferedImage` and various `DataBuffer` implementations. These are all based on in-memory structures. So the requirement to create something larger than the computers memory goes agains that. It is however possible to create memory mapped files and various other creative implementations of `RenderedImage`, like the ones I made in the sandbox module (`MappedBufferImage`, `MappedFileBuffer` etc). See #487 for a related issue.

**So, while it might be possible, I believe for your specific requirements (as I understand them), it would be faster/easier to implement something that can write a (Big)TIFF IFD and then just generate the pixel data (line by line, strip by strip or tile by tile).** 


Best regards,

-- 
Harald K

**Comment by mesmerizeBy** [comment]
**Got it. Thank you very much, that's very helpful!**

Best wishes
