### ISSUE TITLE
ArrayIndexOutOfBoundsException when writing CMYK image.

### ISSUE THREAD

**Issue by morvael** [haraldk/TwelveMonkeys#572]
Tried to follow https://github.com/haraldk/TwelveMonkeys/issues/411 and https://github.com/haraldk/TwelveMonkeys#advanced-usage. My code:
```
  public static void main(String[] args) throws Exception {
    BufferedImage rgbImage = ImageIO.read(new File("c:\\test\\input.png"));
    ICC_Profile ip = ICC_Profile.getInstance(CMYKConvert.class.getResourceAsStream("/ISOcoated_v2_300_eci.icc"));
    ColorConvertOp cco = new ColorConvertOp(rgbImage.getColorModel().getColorSpace(), new ICC_ColorSpace(ip), null);
    BufferedImage cmykImage = cco.filter(rgbImage, null);
    Iterator<ImageWriter> writers = ImageIO.getImageWritersByFormatName("JPEG");
    if (writers.hasNext()) {
      ImageWriter writer = writers.next();
      try {
        System.out.println(writer.getClass().getName());
        try (ImageOutputStream output = ImageIO.createImageOutputStream(new File("c:\\test\\output.jpeg"))) {
          writer.setOutput(output);
          ImageWriteParam param = writer.getDefaultWriteParam();
          param.setCompressionMode(MODE_EXPLICIT);
          param.setCompressionQuality(1f);
          writer.write(null, new IIOImage(cmykImage, null, null), param);
        }
      } finally {
        writer.dispose();
      }
    }
  }
```
and all I get is this:
```
com.twelvemonkeys.imageio.plugins.jpeg.JPEGImageWriter
Exception in thread "main" java.lang.ArrayIndexOutOfBoundsException: Index 4 out of bounds for length 4
	at java.desktop/com.sun.imageio.plugins.jpeg.SOFMarkerSegment.<init>(SOFMarkerSegment.java:70)
	at java.desktop/com.sun.imageio.plugins.jpeg.JPEGMetadata.<init>(JPEGMetadata.java:609)
	at java.desktop/com.sun.imageio.plugins.jpeg.JPEGImageWriter.getDefaultImageMetadata(JPEGImageWriter.java:230)
	at com.twelvemonkeys.imageio.plugins.jpeg.JPEGImageWriter.writeCMYK(JPEGImageWriter.java:192)
	at com.twelvemonkeys.imageio.plugins.jpeg.JPEGImageWriter.write(JPEGImageWriter.java:159)
	at test.CMYKConvert.main(CMYKConvert.java:37)
```
Using default ImageIO.write method results in empty output file as well, but the exception is silenced. What am I doing wrong? Or is this a bug?

**Comment by morvael** [comment]
It doesn't crash when the input is a JPEG file (created from PNG in IrfanView). TwelveMonkeys writer creates an output file which looks like normal file, Sun's writer creates a file that looks like negative.

**Comment by morvael** [comment]
I guess it has trouble with alpha channel? Can't it convert it by discarding that channel in one go?

**Comment by haraldk** [comment]
Hi,

The exception message:
```
Exception in thread "main" java.lang.ArrayIndexOutOfBoundsException: Index 4 out of bounds for length 4
```

...indicates that you are trying to write a CMYK+Alpha image, ie. 5 channels. The native code used for reading/writing JPEG (libJPEG or Oracle modified libJPEG) does not support more than 4 channels, unfortunately. I may add support at some time, but that requires either a different native lib or completely rewriting the encoder in Java... I won't fix this now. :-)

When you first convert your input to a normal JPEG, the input will be plain RGB without alpha, and this makes things work as it should.

> I guess it has trouble with alpha channel? Can it convert the image by discarding that channel in one go?

This is spot on I think.

The easy way would probably be to convert the RGBA image to RGB up front. This should make the result from `ColorConvertOp.filter` CMYK instead of "CMYKA". 

If you want to do it in one go, I think you could probably also replace:

    BufferedImage cmykImage = cco.filter(rgbImage, null);

With:

    BufferedImage cmykImage = cco.filter(rgbImage, new BufferedImage(/*4 channels, based on CMYK ICC profile */));

Or:

    BufferedImage cmykImage = cco.filter(rgbImage, cco.createCompatibleDestImage(rgbImage, /*ComponentColorModel based on CMYK ICC profile*/);

I don't have the time to try it out right now. It might complain about band count mismatch (ie. the destination does not have bands to keep the alpha component from the source). In that case, you could try the `ColorConvertOp.filter(Raster src, Raster dst)` method instead, after creating a child raster from the source without the alpha component and the raster from the CMYK image as destination.

Good luck!

Let me know if it worked out, otherwise I'll see if I can make it work later.

-- 
Harald K

**Comment by morvael** [comment]
Problem solved by drawing RGBA image over RGB image first using Graphics2D. It's a necessary step to add printing bleed (drawing original centered over this larger image with black background), so it's not a waste of CPU power :)
