### ISSUE TITLE
Are the TwelveMonkey plugins (eg. TiffImageWriter) thread-safe? 

### ISSUE THREAD

**Issue by breathermachine** [haraldk/TwelveMonkeys#583]

**Comment by Schmidor** [comment]
No, parallel reads to the same reader cause conflicts in the underlying InputStreams.
You can however create multiple readers and InputStreams.

**Comment by haraldk** [comment]
No, the `ImageReader`,  `ImageWriter` and the various `ImageInput/OutputStream` *instances* are are by design NOT thread-safe. You can however, as @Schmidor says, create multiple instances in separate threads, so the library plays nicely in a multi-threaded environment. 

See [Non-Goals](https://docs.oracle.com/javase/8/docs/technotes/guides/imageio/spec/goals.fm2.html) from the ImageIO API documentation for details and rationale on this design.

-- 
Harald K
