### ISSUE TITLE
Add module for Jakarta Servlet

### ISSUE THREAD

**Issue by Thihup** [haraldk/TwelveMonkeys#589]
After the Java EE has been donated to Eclipse Foundation, they had to rename it from javax.servlet to jakarta.servlet.

I guess it would be really great if this project adds a module for supporting the Jakarta namespace.

It's a matter of renaming the package, but as this breaks compatibility, it would be great to add a new module for supporting the new namespace.

**Comment by haraldk** [comment]
Hi Thiago,

Sounds reasonable...  😀 

Are you up for the task to create a PR? 

Yes, we need to keep the old module, or at least its JAR artifact as-is. I would suggest some way of automatic handling of one of the modules, as I don't want to maintain two identical codebases (apart from the imports). It's probably best to move the actual code to the new module, so that we can simply delete the old module once the new package name is adopted. 

I suggest using the following Maven coordinates for the new module, but I'm open to other well-reasoned alternatives. :-)

```xml
    <groupId>com.twelvemonkeys.servlet</groupId>
    <artifactId>jakarta-servlet</artifactId>
    <name>TwelveMonkeys :: Servlet (Jakarta EE)</name>
```

Best regards,

-- 
Harald K

**Comment by Thihup** [comment]
Hi!

In Piranha we did the replacement in build time, what do you think of this? 
https://github.com/piranhacloud/piranha/blob/master/extension/apache-fileupload/pom.xml#L85-L108

Maybe we could move all the code to the new namespace and in build time replace from jakarta to javax

**Comment by haraldk** [comment]
Sounds like a good plan to me! 😀 

-- 
Harald K

**Comment by astappiev** [comment]
Instead of using `<artifactId>jakarta-servlet</artifactId>` I suggest to use `<classifier>jakarta</classifier>` and keep the old package id.

An example is [Primefaces ](https://github.com/primefaces/primefaces/blob/master/README.md?plain=1#L50-L65) and [this is how they implemented that](https://github.com/primefaces/primefaces/blob/10.0.0/pom.xml#L1183-L1287).

I will try to create a PR

**Comment by alfonx** [comment]
`Could not find artifact com.twelvemonkeys.servlet:servlet:jar:3.8.1-jakarta`
Shouldn't the classifier be available on maven central?
https://mvnrepository.com/artifact/com.twelvemonkeys.servlet/servlet/3.8.1

**Comment by haraldk** [comment]
A quick look at the docs for Maven shade plugin, I believe the problem is the usage of `finalName` instead of `shadedClassifierName`. I believe adding this to the configuration of the maven-shade-plugin will fix it:

```xml
<shadedClassifierName>jakarta</shadedClassifierName>
```

**Comment by haraldk** [comment]
If all worked well, there should now be a 3.9-SNAPSHOT artifact out, with the correct classifier. The contents of the JAR is virtually identical to 3.8.1, except for the version numbers.  Not sure when I find time to make a new release (3.8.2 or 3.9.0), but it will be in there at some point.
