### ISSUE TITLE
imageio-jpeg seemingly not registered when using Executors.newWorkStealingPool vs Executors.newFixedThreadPool

### ISSUE THREAD

**Issue by ldeck** [haraldk/TwelveMonkeys#605]
I recently made a change to our app, configuring its ExecutorService bean to return a new work-stealing pool instead of the previously used fixed-thread pool.

With that change we then started seeing the following exception for JPGs with CMYK color encoding.
```
Caused by: javax.imageio.IIOException: Unsupported Image Type
	at java.desktop/com.sun.imageio.plugins.jpeg.JPEGImageReader.readInternal(Unknown Source)
	at java.desktop/com.sun.imageio.plugins.jpeg.JPEGImageReader.read(Unknown Source)
	at java.desktop/javax.imageio.ImageIO.read(Unknown Source)
	at java.desktop/javax.imageio.ImageIO.read(Unknown Source)
```

Any ideas why this might be the case? 
Is there something special about the initialisation of work-stealing thread-pool's threads?

I've got the following dependencies:
```
            <dependency>
                <groupId>com.twelvemonkeys.imageio</groupId>
                <artifactId>imageio-jpeg</artifactId>
                <version>3.7.0</version>
            </dependency>
            <dependency>
                <groupId>com.twelvemonkeys.servlet</groupId>
                <artifactId>servlet</artifactId>
                <version>3.7.0</version>
            </dependency>
```

And 
```
public class OurApplication extends SpringBootServletInitializer {
...
    @Override
    public void onStartup(ServletContext servletContext) throws ServletException {
        super.onStartup(servletContext);
        servletContext.addListener(IIOProviderContextListener.class);
    }
```

**Comment by haraldk** [comment]
Hi,

Thanks for reporting! 

The reason for the exception is quite straight forward. You are using the standard JDK JPEG plugin, which does not support CMYK JPEGs. But I guess the real issue here is why are we not using the TwelveMonkeys ImageIO JPEG plugin here?

I don't have much experience with wok stealing thread pools, so I don't know if they add something special... But I have to ask the common questions: 

What JDK are you compiling/running on? Do you see the same behavior with TwelveMonkeys ImageIO 3.6.4, or was this introduced with 3.7.0? There's a chance that the inclusion of automatic module names messed up something for the automatic discovery/registration. 

Do you see the same behavior with 3.7.0 and the old thread pool implementation or was this introduced by the thread pool change?


Best regards,

-- 
Harald K

**Comment by haraldk** [comment]
Hi again,

I did some more testing on my side, and things seems to work fine with Java 11/13/15, module-path and the automatic module names, as well with Java 8 and later using normal class path. 

Did you have a chance to look into this, figure out why plugins wasn't registered?


-- 
Harald K

**Comment by haraldk** [comment]
No new input, closing for now. Feel free to reopen if you have more information or report back if you solved this issue.
