### ISSUE TITLE
java.lang.NullPointerException: Cannot enter synchronized block because "p" is null

### ISSUE THREAD

**Issue by momomo** [haraldk/TwelveMonkeys#614]
Expect to see JDK-6986863 in action, and consider filing a bug report to your JRE provider.
java.lang.NullPointerException: Cannot enter synchronized block because "p" is null
	at java.desktop/sun.java2d.cmm.lcms.LCMS.getProfileSize(LCMS.java:67)
	at java.desktop/java.awt.color.ICC_Profile.getData(ICC_Profile.java:1298)
	at com.twelvemonkeys.imageio.color.ColorSpaces.<clinit>(ColorSpaces.java:109)
	at com.twelvemonkeys.imageio.plugins.jpeg.JPEGImageReader.readICCProfileSafe(JPEGImageReader.java:1035)
	at com.twelvemonkeys.imageio.plugins.jpeg.JPEGImageReader.getEmbeddedICCProfile(JPEGImageReader.java:961)
	at com.twelvemonkeys.imageio.plugins.jpeg.JPEGImageReader.read(JPEGImageReader.java:330)
	at java.desktop/javax.imageio.ImageReader.read(ImageReader.java:938)
	at m.instance.Images.fetch(Images.java:86)
	

![image](https://user-images.githubusercontent.com/9274346/126479989-cb8c33c5-c78a-4cba-a446-a72165e75792.png)

**Comment by haraldk** [comment]
As can be seen from the stack trace, the is a JRE/JDK issue. JDK-6986863 is a known issue, that's been around for long, but seems to have been fixed in recent JVMs.

-- 
Harald K

**Comment by momomo** [comment]
@haraldk You could avoid it by checking for null prior to calling that method. Also, We are on  Java 16.

**Comment by haraldk** [comment]
Obviously, yes. But `p` in this case is the built-in Java sRGB profile. If it's `null`, the entire Java color management module is in a bad state. I can't fix that, unfortunately... 

As mentioned, please refer to [JDK-6986863](https://bugs.openjdk.java.net/browse/JDK-6986863) for background and details. 

-- 
Harald K

**Comment by momomo** [comment]
Can't you throw before at least? I can not even catch this annoying exception to retry downloading. Some auto logging is happening prior to this being thrown I think. Maybe you could throw a better suited exception?

**Comment by haraldk** [comment]
The code block that causes the stack trace you see is this (`com.twelvemonkeys.imageio.color.ColorSpaces:106` and on):

```java
    static {
        try {
            // Force invocation of ProfileDeferralMgr.activateProfiles() to avoid JDK-6986863
            ICC_Profile.getInstance(ColorSpace.CS_sRGB).getData();
        }
        catch (Throwable disasters) {
            System.err.println("ICC Color Profile not properly activated due to the exception below.");
            System.err.println("Expect to see JDK-6986863 in action, and consider filing a bug report to your JRE provider.");

            disasters.printStackTrace();
        }
    }
```

The problem here is that if this breaks, the entire Java CMM is in a bad state, and  there is no known way to recover (other than JVM restart). I'm just trying to be nice, and tell you this.

There's no exception propagating to your code or any chance of retry here. It's just a plain message on the console, telling you that the CMM is broken. Things may still work if you are lucky, but most likely not. 

I could add a flag, to *not* perform this test. But all it would help you, is to not get this message. *Random weird things would still happen later on*, possibly just more frequent...

Best regards,

-- 
Harald K

**Comment by momomo** [comment]
Yes, this code does not look great. Static block and system.err? 

For us, this issues seems to occur only occasionally, when we are downloading images concurrently and then calling something on the downloaded file. I don't remember what. Other times when we are  downloading images it appears this does not happen, and I think in development we are always doing this on the same set of urls. So it is my understanding that this p is null, happens when there is something wrong with the downloaded image, and the bytes are incomplete or something, because most of the time no issues occurs. 

I have not noticed that this requires a JDK restart. Other images are able to be processed fine, even after. I think perhaps even multiple exceptions could happen in the same started instance, but it does not look like that should be possible from this code. 

I could retry later  to confirm.

**Comment by momomo** [comment]
Ok, I think I got what you mean. My exception will occur for several images which have this color profile basically? I would say it would be better to propagate on startup in this instance, or not have it in a static block if another invocation might later load it properly?

**Comment by momomo** [comment]
Of check if p is null and retry loading it if so.

**Comment by haraldk** [comment]
I'm sorry, but I don't think it's of any use to discuss this further unless you have a very good understanding of JDK-6986863, the profile deferral/activation mechanism in the JDK, and see how the code block above attempts to fix it (by forcing activation). 

Removing the stack trace you see, would only remove one symptom of the problem. You would still have exceptions when trying to read images because of the JDK bug. 

Finally, the `p` you keep referring to is a *JDK internal variable*, and nothing I can check for. And the reason it is `null` is the JDK bug (the deferral mechanism should have activated and loaded the profile prior to the call, but for some reason, it didn't).  

To get a better understanding of the problem, see the `java.awt.color.ICC_Profile` class, and the `sun.java2d.cmm` and `sun.java2d.cmm.lcms` packages.

-- 
Harald K
