### ISSUE TITLE
Add support for BigTIFF in TIFFImageWriter

### ISSUE THREAD

**Issue by ebremer** [haraldk/TwelveMonkeys#617]
I see TIFFImageReader supports BigTIFF.  Any plans to support BigTIFF in TIFFImageWriter?

**Comment by haraldk** [comment]
Hi Erich,

I don't have any plans to add support for BigTIFF just now, mostly because nobody has asked for it yet. 😀  It's also not super-useful, until we get better support for `BufferedImage`s > 4 GB. But of course, if you need it it shouldn't be too hard to add.

The `com.twelvemonkeys.imageio.metadata.tiff.TIFFWriter` class needs to be rewritten to handle BigTIFF magic and long offsets. This is the main part. Also `TIFFImageWriter` needs some small changes to allow writing the long offsets (should probably delegate offset writing to `TIFFWriter` to keep things clean in plugin). And of course add the necessary Spi machinery for ImageIO happiness.

If you're up to the task, I'll happily accept a PR for this! 

-- 
Harald K

**Comment by ebremer** [comment]
Although I would love to see BufferedImage support greater than 4GB (or is it 2GB?) and 64-bit support in arrays and such, most of the bigtiffs I deal with are accessed by tile and only seen in their entirety by stitching them together dynamically in a web browser using something like OpenSeadragon or a local multi-scale viewer that accesses the internal image pyramid of the bigtiff (assuming there is one).  The images are just too large to decode into memory unless you have > 32GB of RAM for just 100,000x100,000pixel image.  

That said, I wasn't trying to get you to add the bigtiff support, but, if you were, how you were handling JPEG compressed tiles in the BigTIFF. The writer I do use, Bioformat's TIFFWriter is having issues.  When the JPEG compression is turned on, libtiff-based readers complain about "Improper JPEG sampling factors".  Bioformats uses ImageIO to write the tile to an byte[] array (rather than a file) and then store the tile in the TIFF.  I've logged the issue with them, but they are quite busy with the 100+ file formats they deal with so I began to work on it myself.  The life I save may be my own. ;-)

That said, I attempted to swap out the stock IOImage JPEG writer with TwelveMonkeys, but the issue was the same.  What I did notice is that your BigTiff reader can actually load the image generated by Bioformats (where libtiff reader throw and error and die), however, the image's color isn't correct.  I would appreciate any insight you might have.  I was going to look at your code to see what your BigTIFF reader expected when loading JPEG compressed tiles.

**Comment by haraldk** [comment]
Interesting.. 🤔 

However, as the writer currently doesn't support either BigTIFF *or* tiling (see #500), how I would handle it is very hypothetical.. I don't think there are any difference in handling JPEG compressed tiles in TIFF vs BigTIFF. BigTIFF is basically just a slightly modified container format, that allows for larger files, due to using 64 bit offsets instead of 32 bit.

The reader should support BigTIFF, tiling and JPEG compression, but of course, juggling all the various aspects and specifications is complex, so errors may occur. If you send me a sample file, I could look into it and see if I figure out what's wrong (and perhaps a BigTIFF sample using tiles and JPEG that works with libtiff for reference).

PS: While interesting, this discussion deviates quite a bit from the original feature request, perhaps we should move it to StackOverflow, to attract a broader audience?


-- 
Harald K

**Comment by ebremer** [comment]
I'll open a StackOverflow for the image reading JPEG issue, but I would still love to see a 12 Monkeys BigTiff writer with tiling :-)

**Comment by haraldk** [comment]
Added BigTIFF write support.

**Comment by ebremer** [comment]
is tiling supported as well?

**Comment by haraldk** [comment]
Sorry, no. 

Only read-support for tiling. #500 is still open.

-- 
Harald K
