### ISSUE TITLE
TIFF: the image becomes brighter

### ISSUE THREAD

**Issue by shenqiangbin** [haraldk/TwelveMonkeys#621]
Hi, I have an image named gmarbles.tif, I handle it with twelvemonkeys, the result image is gmarbles-12-1-monkey.tif.
but it have some difference with gmarbles2.tif that handled by some online tool. but intersting, the difference only happen on Mac,
image opened by IDEA or on Windows will be ok

the code is here:
https://github.com/shenqiangbin/sample/blob/main/demo/src/main/java/ImageDemo/ImageTest03_1.java

the video that can see some difference is here:
https://github.com/shenqiangbin/sample/blob/main/demo/img/video%20on%20mac.mp4

you can clone this demo:
https://github.com/shenqiangbin/sample

the last, please ignore my bad English

**Comment by haraldk** [comment]
I see what you mean. The image does indeed appear brighter on MacOS. 

I think I understand the problem. The TIFF plugin by default embeds an ICC color profile, it the image does not use sRGB. In this case, the original image is gray scale, so this will be the built-in gray profile. 

For IDEA (which actually uses the TwelveMonkeys TIFF plugin to read...) and other Java applications this should be fine, as the gray profile should match the default gray. The Windows application you used probably disregarded the profile altogether. Preview on MacOS tries to do the right thing and apply the profile, but it seems to be incorrect somehow. 

There's always been problems with gray scale profile handling in Java, as the ICC profile is linear gray, but in many cases it is treated as sRGB response curve. I think probably the best choice would be for the writer to not embed an ICC profile for the case of gray scale... 

If you have the time to suggest a PR, that would be great! Otherwise, I will try to look into it at some point.


Best regards,

-- 
Harald K

**Comment by haraldk** [comment]
Added a fix for this, will make it to the next release. 

-- 
Harald K

**Comment by shenqiangbin** [comment]
Thanks
