### ISSUE TITLE
OutOfMemoryError while reading tif

### ISSUE THREAD

**Issue by jan-pesta** [haraldk/TwelveMonkeys#652]
Hi, 
we were getting following OOME while reading one of our tif images:

```
Exception in thread "main" java.lang.OutOfMemoryError: Java heap space
	at com.twelvemonkeys.imageio.metadata.tiff.TIFFReader.readValue(TIFFReader.java:461)
	at com.twelvemonkeys.imageio.metadata.tiff.TIFFReader.readValueAt(TIFFReader.java:372)
	at com.twelvemonkeys.imageio.metadata.tiff.TIFFReader.readEntry(TIFFReader.java:345)
	at com.twelvemonkeys.imageio.metadata.tiff.TIFFReader.readIFD(TIFFReader.java:178)
	at com.twelvemonkeys.imageio.metadata.tiff.TIFFReader.readSubIFDs(TIFFReader.java:229)
	at com.twelvemonkeys.imageio.metadata.tiff.TIFFReader.readIFD(TIFFReader.java:194)
	at com.twelvemonkeys.imageio.metadata.tiff.TIFFReader.readLinkedIFDs(TIFFReader.java:151)
	at com.twelvemonkeys.imageio.metadata.tiff.TIFFReader.read(TIFFReader.java:132)
	at com.twelvemonkeys.imageio.plugins.tiff.TIFFImageReader.readMetadata(TIFFImageReader.java:187)
	at com.twelvemonkeys.imageio.plugins.tiff.TIFFImageReader.readIFD(TIFFImageReader.java:380)
	at com.twelvemonkeys.imageio.plugins.tiff.TIFFImageReader.read(TIFFImageReader.java:916)
	at javax.imageio.ImageIO.read(ImageIO.java:1462)
```

I suppose that the image metadata are corrupted as I was able to get rid of this error by altering the image (e.q. by opening the image and saving again in graphical editor or manually just with the text editor). 
Would be nice if you could improve the twelvemonkeys implementation and skip loading of metadata to prevent OOME in such case as other tools can read the image without crash.

Code to read image:
`BufferedImage image = ImageIO.read(new URL(wrong));`
Tested with imageio 3.7.0 and 3.8.1.

The problematic image is attached in .zip as tif format is not supported as attachment.
[P07.61-3863-76_M178-Farbe.zip](https://github.com/haraldk/TwelveMonkeys/files/7788647/P07.61-3863-76_M178-Farbe.zip)

**Comment by haraldk** [comment]
Hi,

This is a bit tricky... 

The TIFF data structure mixes "meta data" and essential image data needed for decoding. So we can't simply "skip loading of metadata" to prevent this. Also, there are already measures in place to prevent reading data outside the file limits, but due to technicalities in the ImageIO API/implementation, the file length is not known for streams originating from a `URL`...

So, if possible, don't read the image using `URL`. Instead, use a `File` (as we then have a known file length). If the URL points to a remote resource, it's usually better to first download the file, and then use `ImageIO.read` on the file after download. As TIFF files are not "streamable" anyway, there's not much overhead in this. 

It would probably also be possible to create some code that would open the stream to the remote resource similarly to `ImageIO.read(URL)`, but that also takes the `Content-Length` header into account, to specify stream length.

PS: Yes, there seems to be something with the TIFF data that is corrupted. I can't open it in MacOS Preview or other standard applications. The file will open, and renders fine using `ImageIO` and the TwelveMonkeys TIFF plugin, when reading from file (or using URL, with a large enough heap to actually create array for the bogus value...).

**Comment by jan-pesta** [comment]
Hi Harald,
thanks for the quick response. Your hint with the file will help us. The image is still not loaded, but now it's throwing IOException 
`Exception in thread "main" javax.imageio.IIOException: Can't read input file!
	at javax.imageio.ImageIO.read(ImageIO.java:1302)` 
which can be at least caught in our code. 


Btw. I was able to open the image with all tools on Windows.

**Comment by haraldk** [comment]
Odd... I don't have any trouble reading your file here, with either 3.7.1, 3.8.1 or the latest master... 

I believe the exception you see with the file has to do with file access rights (ie. `File.canRead()` returns `false` for the file, as can also be seen from the stack trace and JDK source).

**Comment by jan-pesta** [comment]
Hi Harald, 
thanks a lot. You're right. The image can be read as a file. The exception above was my fault - I used original URL source with "file:///" protocol prefix at the beginning of the path. Now it works fine.

**Comment by haraldk** [comment]
FIY: I added a small fix that will detect this situation and handle it gracefully, even if reading from URL. Will be included in next release.
