### ISSUE TITLE
Performance degradation in ImageReader#getNumImages for JPEGImageReader (3.6.2 -> 3.6.3)

### ISSUE THREAD

**Issue by der-tkw** [haraldk/TwelveMonkeys#687]
**Describe the bug**
Calling `ImageReader#getNumImages` for JPEGImageReader execution time takes much more time starting with 3.6.3.

**Version information**
1. TwelveMonkeys ImageIO
3.6.2 is fine, 3.6.3 (also checked 3.8.2) are having the issue

2. Java
    openjdk version "1.8.0_302"
    OpenJDK Runtime Environment (Temurin)(build 1.8.0_302-b08)
    OpenJDK 64-Bit Server VM (Temurin)(build 25.302-b08, mixed mode)

**To Reproduce**
Steps to reproduce the behavior: Use below test code

1. Compile the below sample code

**Expected behavior**
Ideally it should be as fast as before.

**Example code**
```
ImageIO.scanForPlugins();
InputStream inputStream = RenditionServiceTest.class.getResourceAsStream("/images/image.jpg");
ImageInputStream iis = ImageIO.createImageInputStream(inputStream);
Iterator<ImageReader> iterator = ImageIO.getImageReaders(iis);
ImageReader reader = iterator.next();
reader.setInput(iis);
reader.getNumImages(true);
```

The above code executes in ~500ms for 3.6.2, ~9000ms for 3.6.3.

**Additional context**
This commit seems to have removed the buffered image input stream (which made it fast):
https://github.com/haraldk/TwelveMonkeys/commit/d5e664cdcc5bc9be0ba3f935e1b99dd3767205d8#diff-6e4d5b2b35650d42a59dfda91a85dbf159787a09272c0c3ffcc00a964c3dfe5aL750

![image](https://user-images.githubusercontent.com/6158940/173577180-84c24159-78b6-4733-b101-74553f39d0b8.jpg)

**Comment by haraldk** [comment]
I reworked your code to a QnD benchmark, and my results were (3 different runs with different order, but similar results):

```
Stream (FileCacheImageInputStream): 5433.2 ms
Stream (MemoryCacheImageInputStream): 38.5 ms
URL (BufferedFileImageInputStream): 14.1 ms

URL (BufferedFileImageInputStream): 11.2 ms
Stream (MemoryCacheImageInputStream): 31.0 ms
Stream (FileCacheImageInputStream): 5379.8 ms

Stream (MemoryCacheImageInputStream): 31.1 ms
URL (BufferedFileImageInputStream): 6.3 ms
Stream (FileCacheImageInputStream): 5371.7 ms
```

`FileCacheImageInputStream` is what `ImageIO` will use by default, `MemoryCacheImageInputStream` is what will be used by setting `ImageIO.setUseCache(false)`. As you can see, this little setting makes things several orders of magnitudes faster. 

For comparison, here's a run with the now deprecated `BufferedImageInputStream`:

```
Stream (BufferedImageInputStream + FileCacheImageInputStream): 16.7 ms
Stream (MemoryCacheImageInputStream): 35.5 ms
URL (BufferedFileImageInputStream): 11.7 ms
```

As you see, we can improve the situation quite a bit with the buffering, but only so much. The new stream implementation is still faster.

**Comment by der-tkw** [comment]
Hi Harald,

thanks a lot for the quick reply, tests and explanation. Since we are kind of forced to use streams at the moment, I think we will go with disabling the cache which is completely fine for us.

I have closed the ticket since this is obviously not a bug.

Thanks,
Tim

**Comment by haraldk** [comment]
👍🏻 

I did actually start looking at new stream classes for the `InputStream` case as well, and it shows promising results so far. It will take some time to finish, but I'll see what I can do.

**Comment by haraldk** [comment]
New stream implementation out in 3.9.0 release, feel free to give it a try and report back! 😀

**Comment by sghpjuikit** [comment]
@haraldk Im trying this out on the lossless webp images. The streams are working, but I suspect there is something wrong with the webp image reader.

Comparisons:
* With setCaches(true), `reader.read` takes 16 seconds to load 8MB lossless webp image wit 2k x 4k resolution.
* With setCaches(false), `reader.read` takes 1.5 second.
* With explorer.exe preview or other image viewers is near instant

Diagnostics:
* Printing the type of stream gives me `BufferedChannelImageInputStream`.
* I also use `reader.setInput(stream, seekForwardOnly = true, ignoreMetadata = true)` to squeeze any speed I can get
* I also use subsampling, but this is where it gets weird - it seems to have noeffect, setting 1 (full quality) or 10 results in same loading time.

I had a look at the code and did some debugging. It seems that the VP8LDecoder.readVP8Lossless fullSizeRaster always contains full size image. I dont know if this is intended for the algorithm or not, so I'm not creating an issue for now.

**Comment by sghpjuikit** [comment]
It seems this IS a stream issue.

Using setCache(false):
* `ImageIO.createImageInputStream(FileInputStream(file).buffered(bufferSize))` // 1.5s (bufferSize 8k vs 124k vs 1M has 0 impact)
* `ImageIO.createImageInputStream(FileInputStream(file))` // 22s
* `ImageIO.createImageInputStream(file)` // 26s
* `ImageIO.createImageInputStream(MemoryCacheImageInputStream(FileInputStream(file)))`  // no output, no error
* `ImageIO.createImageInputStream(FileCacheImageInputStream(FileInputStream(file), File("someDir")))`  // no output, no error

**Comment by haraldk** [comment]
@sghpjuikit Thanks for reporting back!

It would certainly be helpful if you could open a new issue, including all relevant information like Java release, OS, etc., along with the code and sample images you use (if you can use the sample files already in the project, even better). 

I'm _very surprised_ that `ImageIO.createInputStream` with `File` or `FileInputStream` displays this sort of performance... 

Some notes though:

* `ImageIO.setCache(true)` is the same as the default setting, and enables *disk caching* (as opposed to in-memory cache). It will always be slower. So when possible, use `setCache(false)` for better performance.
* The new stream implementations does buffering internally, so changing the buffer size of the `InputStream` is unlikely to have much effect. Instead, using a `File` or `FileInputStream` directly should be faster, as we buffer only in once place.
* `seekForwardOnly` and `ignoreMetadata` is mostly ignored in my readers, should have no impact on performance
* The WebP compression is designed so that you need to decode everything, even if you are subsampling. It might be possible to decrease memory usage a little, but don't expect it to be much faster...
* The two last examples (`ImageIO.createImageInputStream` from an existing `ImageInputStream`) doesn't make any sense, and has never worked (for any reader, regardless of using TwelveMonkeys or not).
