### ISSUE TITLE
Problems with upgrade from version 3.3.2 to latest 3.8.2

### ISSUE THREAD

**Issue by BrandonRiveraGodines** [haraldk/TwelveMonkeys#689]
Hi, I was working with your library with version 3.3.2 everything goes well, but for vulnerabilities topics I decided to upgrade to version 3.8.2, but now, I received this problem: 

`Unsupported stream metadata format, expected com_sun_media_imageio_plugins_tiff_stream_1.0: [com_sun_media_imageio_plugins_tiff_image_1.0, javax_imageio_1.0]"` 

And I saw into your code to see what is happening, I see that this is for:

```java
    static void configureStreamByteOrder(final IIOMetadata streamMetadata, final ImageOutputStream imageOutput) throws IIOInvalidTreeException {
        notNull(imageOutput, "imageOutput");

        if (streamMetadata instanceof TIFFStreamMetadata) {
            imageOutput.setByteOrder(((TIFFStreamMetadata) streamMetadata).byteOrder);
        }
        else if (streamMetadata != null) {
            TIFFStreamMetadata metadata = new TIFFStreamMetadata();

            Validate.isTrue(asList(streamMetadata.getMetadataFormatNames()).contains(metadata.nativeMetadataFormatName),
                            format("Unsupported stream metadata format, expected %s: %s", metadata.nativeMetadataFormatName,
                                   Arrays.toString(streamMetadata.getMetadataFormatNames())));

            // Will throw exception if stream format differs from native
            metadata.mergeTree(metadata.nativeMetadataFormatName, streamMetadata.getAsTree(metadata.nativeMetadataFormatName));
            imageOutput.setByteOrder(metadata.byteOrder);
        }
        // else, leave as-is
    }
```

Looks like the new Object to Metadata is TIFFStreamMetadada instead TIFFImageMetadata, but I don't know how to change from previous version no newer or how to avoid the exception. Can someone support me?

This is my code.

```java
IIOMetadata metadata = getTifMetadata();
writer.prepareWriteSequence(metadata);
```

```java
    private IIOMetadata getTifMetadata() throws IIOInvalidTreeException {
        String now =
                LocalDateTime.now(ZoneId.of("CST", ZoneId.SHORT_IDS)).format(dateTimeFormatter);

        // custom tiff attributes
        List<Entry> ifd = new ArrayList<>();
        ifd.add(new TiffAttribute(TIFF.TAG_X_RESOLUTION, new Rational(RESOLUTION_PERCENT),
                TIFF_RATIONAL_TYPE));
        ifd.add(new TiffAttribute(TIFF.TAG_Y_RESOLUTION, new Rational(RESOLUTION_PERCENT),
                TIFF_RATIONAL_TYPE));
        ifd.add(new TiffAttribute(TIFF.TAG_RESOLUTION_UNIT, RESOLUTION_UNIT_DPI, TIFF_NUMBER_TYPE));
        ifd.add(new TiffAttribute(TIFF.TAG_SOFTWARE, TIFF_SOFTWARE_NAME, TIFF_STRING_TYPE));
        ifd.add(new TiffAttribute(TIFF.TAG_DATE_TIME, now, TIFF_STRING_TYPE));
        ifd.add(new TiffAttribute(TIFF.TAG_MODEL, TIFF_MODEL, TIFF_STRING_TYPE));

        String standardFormat = IIOMetadataFormatImpl.standardMetadataFormatName;
        IIOMetadata metadata = new TIFFImageMetadata(ifd);
        IIOMetadataNode customMeta = new IIOMetadataNode(standardFormat);
        IIOMetadataNode dimension = new IIOMetadataNode("Dimension");
        customMeta.appendChild(dimension);

        IIOMetadataNode xSize = new IIOMetadataNode("HorizontalPixelSize");
        dimension.appendChild(xSize);
        xSize.setAttribute("value", String.valueOf(TIF_DPI));

        IIOMetadataNode ySize = new IIOMetadataNode("VerticalPixelSize");
        dimension.appendChild(ySize);
        ySize.setAttribute("value", String.valueOf(TIF_DPI));

        metadata.mergeTree(standardFormat, customMeta);
        return metadata;
    }
```

Any suggestions? Please.

**Comment by haraldk** [comment]
Answered [here](https://stackoverflow.com/a/72726881/1428606).

**Comment by haraldk** [comment]
If you look at the API docs for [`prepareWriteSequence`](https://docs.oracle.com/javase/8/docs/api/javax/imageio/ImageWriter.html#prepareWriteSequence-javax.imageio.metadata.IIOMetadata-), you will find that the parameter is indeed *stream* metadata (perhaps "global" or "document" metadata would be better names, but that's what it is). And the TIFF format does not have document metadata [1]. This means what you do didn't work as intended in earlier versions either, it was just silently ignored. 

The fix is easy, just pass `null` as stream metadata:

    writer.prepareWriteSequence(null);

To correctly write your TIFF metadata, you need to pass it along with your image (and optional thumbnails) as an `IIOImage` to  the `writeToSequence` method:

    writer.writeToSequence(new IIOImage(image, null, metadata), param);

And finally:

    writer.endWriteSequence();

---

Alternatively, if you only need to write a single image to your TIFF, you can skip all the "sequence" methods, and simply use (again, passing `null` as stream metadata):

    writer.write(null, new IIOImage(image, null, metadata), param);

---

1: For compatibility with the JAI TIFF plugin, the stream metadata is used for is specifying the byte order of the TIFF, as this is the only "global" setting. But you can do that more easily by just setting the byte order on the stream you write to.
