### ISSUE TITLE
Bad colors while reading multipage tiff when imageio-jpeg-3.8.1.jar is used

### ISSUE THREAD

**Issue by eruiz0** [haraldk/TwelveMonkeys#690]
If imageio-jpeg-3.8.1.jar is used then multipage tiff reading produces different colors. Maybe a conflict with jai-imageio-core.

The attached program reads the first page of a multipage tiff file and shows the color of one pixel. When used with the following command
`java -cp ".;jai-imageio-core-1.4.0.jar;imageio-core-3.8.1.jar;common-image-3.8.1.jar;common-io-3.8.1.jar;common-lang-3.8.1.jar;imageio-metadata-3.8.1.jar" Test multipage_tiff_example.tif`

the output is:
`RGB for 0,0: -1`

But if imageio-jpeg-3.8.1.jar is added to the command line: 
`java -cp ".;jai-imageio-core-1.4.0.jar;imageio-core-3.8.1.jar;common-image-3.8.1.jar;common-io-3.8.1.jar;common-lang-3.8.1.jar;imageio-metadata-3.8.1.jar;imageio-jpeg-3.8.1.jar" Test multipage_tiff_example.ti' Test multipage_tiff_example.tif`

then the output is:
`RGB for 0,0: -34305`
[multipage_tiff_example.zip](https://github.com/haraldk/TwelveMonkeys/files/9013434/multipage_tiff_example.zip)
[Test.java.zip](https://github.com/haraldk/TwelveMonkeys/files/9013436/Test.java.zip)

**Comment by haraldk** [comment]
Thanks for reporting,

I did some digging, and I think I understand the situation. It has nothing to do with the TIFF being multipage, but instead it's   caused by the pages in the TIFF using JPEG (7) compression and RGB (2)  photometric. This is a bit uncommon, normally JPEG compression would be used with YCbCr (6) photometric. 

I changed your code slightly, to get better debug info:

````java
try (ImageInputStream is = ImageIO.createImageInputStream(new File(args[0]))) {
    Iterator<ImageReader> iterator = ImageIO.getImageReaders(is);
    ImageReader reader = iterator.next();

    System.out.println("reader: " + reader + " - " + reader.getOriginatingProvider().getVendorName());

    reader.setInput(is);
    BufferedImage img = reader.read(0);

    System.out.printf("RGB for 0,0: #%08x%n", img.getRGB(0, 0));
}
````

With this, using the TwelveMonkeys TIFF plugin, things work fine using both the JDK JPEG plugin and the TwelveMonkeys JPEG plugin:

```
reader: com.twelvemonkeys.imageio.plugins.tiff.TIFFImageReader@2ef1e4fa - TwelveMonkeys
RGB for 0,0: #ffffffff
```

```
reader: com.twelvemonkeys.imageio.plugins.tiff.TIFFImageReader@3d82c5f3 - TwelveMonkeys
RGB for 0,0: #ffffffff
```

However, I can reproduce your results using both the JAI TIFF plugin and the JEP 262/JDK TIFF plugin (both runs with TwelveMonkeys JPEG plugin):

```
reader: com.github.jaiimageio.impl.plugins.tiff.TIFFImageReader@7a79be86 - https://github.com/jai-imageio/ jai-imageio GitHub group
RGB for 0,0: #ffff79ff
```

```
reader: com.sun.imageio.plugins.tiff.TIFFImageReader@7a7b0070 - Oracle Corporation
RGB for 0,0: #ffff79ff
```

From what I understand you are using the JAI TIFF plugin. While in theory, they could/should work (and I do limited testing to make sure they do), these configurations are completely unsupported and I do not recommend them. 

JPEG-in-TIFF is a quite complex beast in itself... For ImageIO, things are even more complex, as a TIFF plugin typically (this is the case for all the plugins tested above) delegates the JPEG decoding to an "external" JPEG plugin determined at run-time. 

The difference in the green channel (`ff79ff` vs `ffffff`) is likely due to incorrectly interpreting the RGB as YCbCr or vice versa... As it's the TIFF plugin in the end that has to make the choice of how to interpret the data (often based on conflicting values from the TIFF and the JPEG stream inside it), my conclusion is that the bug here is in the JAI/JDK TIFF plugins. 

I recommend you either switch to the TwelveMonkeys TIFF plugin and use that with our JPEG plugin, or if you prefer, stick to JAI without the TwelveMonkeys TIFF/JPEG plugins. 

If you like to dig more into this subject, and want to look for a way to make this work that is also welcome! In any case, I think you should report the bug to the JAI and OpenJDK projects.

**Comment by eruiz0** [comment]
I have switched to the TwelveMonkeys TIFF plugin and everything seems to be ok now.
