### ISSUE TITLE
Exception when scaling a CMYK-TIFF

### ISSUE THREAD

**Issue by stephancomo** [haraldk/TwelveMonkeys#718]
Hi Harald,

I'm trying to read and scale a CMYK-TIFF. Reading is fine but scaling results in an exception:

Exception in thread "main" java.lang.NullPointerException: Cannot read field "pixel" because "<local14>[<local23>].p[0]" is null
        at com.twelvemonkeys.image.ResampleOp.resample(ResampleOp.java:1614)
        at com.twelvemonkeys.image.ResampleOp.filter(ResampleOp.java:576)
        at ScaleImage.main(ScaleImage.java:49)

I'm using TwelveMonkeys 3.9.3 on Windows 10 with Java 17,
java version "17" 2021-09-14 LTS
Java(TM) SE Runtime Environment (build 17+35-LTS-2724)
Java HotSpot(TM) 64-Bit Server VM (build 17+35-LTS-2724, mixed mode, sharing)
        
I've attached a ZIP archive containing:
- Java source code and class file to reproduce the issue (ScaleImage.java, ScaleImage.class)
- Windows batch files for compiling and running the example (compile.bat, run.bat)
- the twelvemonkeys libraries I'm using
- two sample images, test-LZW-CMYK.tif shows the problem, test-LZW-RGB loads and scales fine

Is there a way to make it working or to circumvent the problem?

Thanks,
Stephan
[scaling-problem.zip](https://github.com/haraldk/TwelveMonkeys/files/10132857/scaling-problem.zip)

**Comment by haraldk** [comment]
There seems to be a bug in the `ResampleOp` when scaling *up* using `FILTER_POINT` and `TYPE_CUSTOM` images... It works with normal RGB, because you get a non-custom image type, and the code skips the internal resampling and instead forwards it to `AffineTransformOp` using `TYPE_NEAREST_NEIGHBOR` (as that is possibly hardware and/or native code optimized). It also seems to work with any other filter than `FILTER_POINT` for some reason... 

So yes, you can work around this problem by either:

1. Converting the input image to a standard `BufferedImage.TYPE_INT_RGB` or `TYPE_3BYTE_BGR` *before* resampling (as a bonus, your JPEG file will be a lot smaller and more compatible as well, as CMYK JPEGs are a bit exotic).
2. Just change to another sampling filter, like `FILTER_BOX` or other more high quality filter (which as a bonus will make your image look smoother).
3. Both of the above.

All at the cost of some computing time, unfortunately...

---

The `ResampleOp` class is really old and unloved, I want to completely rewrite it at some time, making it simpler, more understandable and hopefully more robust at the same time. There's just too many optimizations and odd codepaths to cover all the cases...

**Comment by stephancomo** [comment]
Hi Harald,
wow, you're really fast!
I've changed the filter to FILTER_BOX and that solved the problem.
Thank you very much for this quick solution.
