### ISSUE TITLE
TIFF: Write extremely slow in 3.9.4, working in 3.8.2

### ISSUE THREAD

**Issue by thhart** [haraldk/TwelveMonkeys#744]
**Describe the bug**
Tiff write is extremely slow.

**Version information**
1. The version of the TwelveMonkeys ImageIO library in use.

3.9.4

2. The *exact* output of `java --version` (or `java -version` for older Java releases). 

GraalVM
openjdk version "19.0.2" 2023-01-17
OpenJDK Runtime Environment (build 19.0.2+7-Ubuntu-0ubuntu322.04)
OpenJDK 64-Bit Server VM (build 19.0.2+7-Ubuntu-0ubuntu322.04, mixed mode, sharing)

**To Reproduce**
Please download following project: https://github.com/thhart/FX-IIO
Run the FXBufferedImageTest to see encoding of images.

Check output for different versions (modify in pom.xml): 

3.9.4

standard png generation done in: PT1.184727278S
fx png generation done in: PT2.254707665S
standard tiff generation done in: **PT28.341633161S**
fx tiff generation done in: **PT37.891254997S**

3.8.2

standard png generation done in: PT1.126847053S
fx png generation done in: PT2.225881581S
standard tiff generation done in: **PT0.184286046S**
fx tiff generation done in: **PT0.515416073S**

**Comment by haraldk** [comment]
Thanks for reporting! 

Hmmm.. That is quite a difference. If you are able to work this into working test case inside TwelveMonkeys or simple standalone program without external dependencies, I will be able to look into this a lot quicker. 

Anyway, I have a hunch that 8c85c4ca is the culprit here... While that change simplifies writing, it also relies on buffering in the output to avoid a lot of short writes to the output. 

You could try disabling the disk cache (through `ImageIO.setUseCache(false)`), and use a buffered output stream, and see if that helps.

**Comment by haraldk** [comment]
Just pushed a potential fix for this regression (which should be a bit faster than the 3.8.2 version too, on a good day). Feel free to try the latest snapshot and re-run your tests. 😀

**Comment by thhart** [comment]
Cool, it is working very good. Thanks.
