### ISSUE TITLE
WMF images using imageio-batik

### ISSUE THREAD

**Issue by p4paul** [haraldk/TwelveMonkeys#783]
I'm using the imageio-batik to read .wmf images, however I have tried several .wmf images and they all seem to be cropped (bottom corner) and upside down?

For example: https://github.com/kareldonk/WMFPreview/blob/master/Test/bird.wmf

I'm using:... 
```
    implementation 'com.twelvemonkeys.imageio:imageio-batik:3.9.4'
    implementation 'org.apache.xmlgraphics:batik-all:1.16'
```

openjdk 17.0.5 2022-10-18 LTS
OpenJDK Runtime Environment Corretto-17.0.5.8.1 (build 17.0.5+8-LTS)
OpenJDK 64-Bit Server VM Corretto-17.0.5.8.1 (build 17.0.5+8-LTS, mixed mode, sharing)

On OS X 13.4.1

```java
    File file = new File("src/test/resources/files/vector/bird.wmf");
    BufferedImage img = ImageIO.read(file);
    ImageIO.write(img, "jpeg", new File(TMP, "bird.wmf-preview.jpeg"));
```

**Comment by haraldk** [comment]
Hi Paul,

What happens if you read these files directly via Batik? 

The TwelveMonkeys imageio-batik plugin basically just feeds the WMF file to Batik's `WMFTranscoder` which converts the WMF to an SVG, then use the `SVGImageReader` to read the resulting SVG and rasterize it. 

The intermediate SVG from the `WMFTranscoder` looks like this: 

![foo16656711504246595905](https://github.com/haraldk/TwelveMonkeys/assets/110299/916eb3f0-c375-4fe1-ab4e-339de552d5df)

So I'm afraid the bug needs to be reported against and fixed in Batik. 

Also, I don't think you really use TwelveMonkeys 4.0.0.. 😉 

-- 
Harald K

**Comment by p4paul** [comment]
Hi Harald, 
Thank you for getting back to me.  As you say it would seem to be an issue with Batik.  There are several open issues with rendering WMF.  [BATIK-889](https://issues.apache.org/jira/browse/BATIK-889) looks the closest to what I'm seeing.

Kind regards,
Paul
