### ISSUE TITLE
jakarta.servlet support

### ISSUE THREAD

**Issue by EXEC-CSM** [haraldk/TwelveMonkeys#804]
Hey. 👋
Is there any planning for support of jakarta.servlet instead of javax.servlet support?
Perhaps you could create an seperate release for javax and one for jakarta.servlet?

**Comment by haraldk** [comment]
Hi, this should be implemented already since 3.9.0, See #636 for details.

You need to depend on the same artifact, with an extra `jakarta` "classifier". The built JAR can be found [here](https://repo1.maven.org/maven2/com/twelvemonkeys/servlet/servlet/3.9.4/servlet-3.9.4-jakarta.jar). 
Let me know if that works for you. 😀
