### ISSUE TITLE
Features stopped working after upgrading to JDK 17

### ISSUE THREAD

**Issue by kunalbarchha** [haraldk/TwelveMonkeys#825]
Hi, 

I have been using this library from almost a year in one of my projects, and it was working flawlessly... Very thankful for that. 

Now, recently migrated entire project from Spring 2.1.x to 2.7.x and JDK 11 to JDK 17... Entire application and all EPs are completely tested. 

However, when we started testing the image related features, one of the feature relation to PPM files isn't working anymore. Below is the stack trace. 

````
Caused by: java.lang.IllegalAccessError: class com.sun.media.imageioimpl.plugins.pnm.PNMImageReader (in unnamed module @0x48524010) cannot access class sun.security.action.GetPropertyAction (in module java.base) because module java.base does not export sun.security.action to unnamed module @0x48524010
````

Here's the dependency that we have and updated to latest version : 

````
		<dependency>
			<groupId>com.twelvemonkeys.imageio</groupId>
			<artifactId>imageio-jpeg</artifactId>
			<version>3.9.4</version>
		</dependency>
		<dependency>
			<groupId>com.twelvemonkeys.imageio</groupId>
			<artifactId>imageio-tiff</artifactId>
			<version>3.9.4</version>
		</dependency>
		<dependency>
			<groupId>com.twelvemonkeys.imageio</groupId>
			<artifactId>imageio-pnm</artifactId>
			<version>3.9.4</version>
		</dependency>
````

**Comment by haraldk** [comment]
> com.sun.media.imageioimpl.plugins.pnm.PNMImageReader

I believe this is the JAI ImageIO PNM plugin from Sun/Oracle.

**Comment by kunalbarchha** [comment]
Any idea how to resolve it ? @haraldk it's a blocker currently.

**Comment by rmuller** [comment]
This error has nothing to do with TwelveMonkeys or the sun plugin itself. The error gives the answer: 

`Caused by: java.lang.IllegalAccessError: class com.sun.media.imageioimpl.plugins.pnm.PNMImageReader (in unnamed module @0x48524010) cannot access class sun.security.action.GetPropertyAction (in module java.base) because module java.base does not export sun.security.action to unnamed module @0x48524010`

This is caused by the Java Module System (introduced in Java 9) which became more strict in Java 17. Your code access an internal class, `com.sun.media.imageioimpl.plugins.pnm.PNMImageReader` which you never should do.

For details and how to fix it, see https://blogs.oracle.com/javamagazine/post/a-peek-into-java-17-continuing-the-drive-to-encapsulate-the-java-runtime-internals

**Comment by kunalbarchha** [comment]
@rmuller I somewhat understand that, but the error was thrown specifically at the line ImageIO.read(inputStream).... but what's stranger is that I didn't change anytime, and now the code runs fine on my local. Will test it out on the server... but it's more scary as a developer that something fails, and it automatically starts working fine the next day, without any change :-)

**Comment by haraldk** [comment]
@rmuller Thanks!

You are correct about this (and that it is not a TwelveMonkeys issue):

> This is caused by the Java Module System (introduced in Java 9) which became more strict in Java 17. 

For the record, TwelveMonkeys is tested with all Java LTS versions plus the current latest version (8, 11, 17 and 20, soon replaced by 21). 

However, I don't this is the case:

> Your code access an internal class, `com.sun.media.imageioimpl.plugins.pnm.PNMImageReader` which you never should do.

I don't think @kunalbarchha does, that class is just used by `ImageIO` (as it should). It *is* the `com.sun...PNMImageReader` that is the culprit, because it accesses `sun.security.action` and which is not allowed. This is a problem using old, outdated and discontinued products like JAI (Java Advanced Imaging)...

The issue with the code suddenly running fine on your local machine is actually related*. Because you have both JAI ImageIO and the TwelveMonkeys ImageIO PNM plugin in your dependencies (on class path), you have two plugins that are capable of reading the PNM format. When you attempt to read a PNM file using `ImageIO.read(..)`, `ImageIO` will pick the first PNM plugin. If you don't add specific code to order these, the *order is undefined*. It might work when you run the program once, and fail the next, even with no changes in code. 

The easy fix is to remove any dependency on JAI ImageIO. If you don't have an explicit dependency, you might need to exclude it (consult Maven documentation as needed) or remove it from class path. If you need JAI ImageIO for other formats/functionality you can also work around the issue by setting the order so that the TwelveMonkeys PNM reader is picked first, as described [in this SO answer](https://stackoverflow.com/a/38198991/1428606). 

*) Could of course also be that you don't have JAI ImageIO on your local machine, only on the server you tested. In either case, getting rid of JAI ImageIO will fix the problem.

**Comment by kunalbarchha** [comment]
@haraldk Ah yes, this could definitely be the reason. I am not using anything else except TwelveMonkey, but there might some depencency having PNM related functionalities. I will check it out.. Thanks a lot.

**Comment by haraldk** [comment]
Even if unintentional, the error message you first posted indicate you are using JAI ImageIO.

**Comment by kunalbarchha** [comment]
Actually, I ran mvn dependency tree, and I got to know that I use geotools
library which is eventually using JAI image IO.
