### ISSUE TITLE
Troubleshooting with ImageIO plugin registry issue (NoClassDefFoundErrors) without web.xml file

### ISSUE THREAD

**Issue by bms82** [haraldk/TwelveMonkeys#868]
Tag the question with `javax-imageio` and/or `twelvemonkeys` and we'll find them there.

I wanted to add that Spring Framework users who are not willing to use web.xml file, there is an alternative.
I added the following code for ServletInitializer class (which extends SpringBootServletInitializer).

import com.twelvemonkeys.servlet.image.IIOProviderContextListener; 
`	
	@Override
	public void onStartup(ServletContext servletContext) throws ServletException {
		servletContext.addListener(IIOProviderContextListener.class);
		super.onStartup(servletContext);
	}`

I hope this helps.

**Comment by haraldk** [comment]
Hi @bms82 ! 

Thank you for the information. I believe this is the programmatically equivalent in Spring to adding the class to the `web.xml`. Do you think it should be added to the readme? If so, would you create a PR for that? Otherwise it might be better to ask a question on StackOverflow, as I'm not sure if people will find this issue once I have closed it. 

Closing for now, as there is no action to be taken.
