### ISSUE TITLE
WebP plugin stops working when other plugins are enabled too

### ISSUE THREAD

**Issue by rob93c** [haraldk/TwelveMonkeys#885]
**Describe the bug**
The WebP plugin works fine when it's the only ImageIO plugin in use but stops working if I add the BMP, PSD, or JPEG one.

**Version information**
1. The version of the TwelveMonkeys ImageIO library in use.
3.10.1

2. The *exact* output of `java --version` (or `java -version` for older Java releases). 
> openjdk 21.0.1 2023-10-17 LTS
OpenJDK Runtime Environment Temurin-21.0.1+12 (build 21.0.1+12-LTS)
OpenJDK 64-Bit Server VM Temurin-21.0.1+12 (build 21.0.1+12-LTS, mixed mode, sharing)

3. Extra information about OS version, server version, standalone program or web application packaging, executable wrapper, etc. Please state exact version numbers where applicable.
I notice this issue only when the project is deployed (using a Docker image) in a Linux environment.

**Expected behavior**
ImageIO should be able to read WebP images even if other plugins are enabled too.

**Stak trace**
ImageIO doesn't break but `ImageIO.read(file)` returns `null` when a WebP is passed to it.

**Additional context**
The project affected is a Telegram bot used to convert medias in Telegram stickers, it was capable of processing WebPs until I added other plugins (BMP, PSD, and JPEG) with the pull request https://github.com/Stickerifier/Stickerify/pull/191

I can't reproduce via unit tests since they are still working properly (I also have a Github action running them against Windows, Linux and Mac).
Launching the bot locally (via the [Main class](https://github.com/Stickerifier/Stickerify/blob/main/src/main/java/com/github/stickerifier/stickerify/runner/Main.java)) shows no issues and it can process those images.

**Comment by haraldk** [comment]
I can verify that the WebP ImageIO plugin does indeed work, even when all the other mentioned plugins are also enabled. I cannot reproduce your issue here. Probably the same reason you can't reproduce using unit tests.

The symptoms seems to match a classic packaging issue. Do you re-package the TwelveMonkeys JAR files in any way? If so, make sure you read and follow the recommendations in [the ReadMe](https://github.com/haraldk/TwelveMonkeys/#including-the-plugins-in-a-fat-jar). Whatever bundling tool you use, It is important that the contents of the `META-INF/services` folder of each JAR is properly _merged_ and that the various files don't just overwrite each other (there are files with the exact same path in all of the JAR files).

**Comment by rob93c** [comment]
> The symptoms seems to match a classic packaging issue.

That was it, nice catch! I was creating a fat jar using the ShadowJar plugin for Gradle, I just had to add `mergeServiceFiles()` to its configuration and now everything is working as expected ([PR reference](https://github.com/Stickerifier/Stickerify/pull/195)).

Many thanks for your help and thank you for your work, the WebP plugin has been super useful since I added it to my project.
