### ISSUE TITLE
JPEGImageReader read invalid image without throwing exception

### ISSUE THREAD

**Issue by joeydaowang** [haraldk/TwelveMonkeys#907]
![invalid_image](https://github.com/haraldk/TwelveMonkeys/assets/6657624/48f46a93-ebea-4d90-a1f1-61f59f6c5eb6)
With version 3.10.1, JPEGImageReader can read above image without problem, though that is an invalid image. Meanwhile version 3.1.2 has exception IIOException("No SOF segment in stream") thrown.

**Comment by haraldk** [comment]
Hi @joeydaowang!

If I understand correctly, the bug report is that we now read a (non-spec) JPEG that we didn't before? I don't see the problem in that. If you add a warning listener while reading, you will get a lot of warnings though. 

The problem seems to be that the APP1/XMP segment (before the first APP2/ICC_PROFILE) has a size much larger (19392) than the actual segment, so that the first ICC Profile segment is missed (and thus the entire ICC Profile is unreadable). If I manually fix the segment to its correct size (12662), the file seems entirely fine. 

I believe the new behavior is fine (and desirable). Why do you think it's a bug?

**Comment by joeydaowang** [comment]
Hi @haraldk,

Thanks for replying so quickly.
I am not sure whether it is a bug. I would argue that if the image can't be opened by image viewer, then reader should throw exception as it is fatal error instead of warning?

**Comment by haraldk** [comment]
There are so many semi or non-compliant JPEGs that can be read by various software. It's a goal for this plugin to be lenient about such issues. If you only want to read spec-compliant JPEGs, you can use the built-in JPEG plugin, I'm sure it will throw exception for this image.. 

If we can actually read the image, why would you consider that a "fatal error"? I'm happy with the current behavior, so I'm closing this issue for now.

**Comment by joeydaowang** [comment]
Fair enough. I will use build-in JPEG reader for additional validation.
Thanks.
