### ISSUE TITLE
NPE in JPEGImageReader.getSourceCSType in case of mime mixup

### ISSUE THREAD

**Issue by huxi** [haraldk/TwelveMonkeys#96]
This is a followup to my comment in issue #22.

The exception is thrown with the following stack trace:
```
com.twelvemonkeys.imageio.plugins.jpeg.JPEGImageReader.getSourceCSType(Unknown Source)
com.twelvemonkeys.imageio.plugins.jpeg.JPEGImageReader.read(Unknown Source)
javax.imageio.ImageReader.read(ImageReader.java:939)
```

The code causing the issue looks like this:
```java
ImageInputStream iis = ImageIO.createImageInputStream(new BufferedInputStream(inputStream));
Iterator readers = ImageIO.getImageReadersByMIMEType(mimeType);
ImageReader imageReader = (ImageReader) readers.next();
imageReader.setInput(iis, false);
BufferedImage bufferedImage = imageReader.read(0);
```

The `mimeType` is resolved by us based on the file extension so this is essentially our fault.

I thought I'd file this issue anyway so that other people hitting a similar problem can find it.

Is there a better way to create a `BufferedImage` from an `InputStream`, i.e. one that would resolve the actual mime type instead of using an inferred one to resolve the proper `ImageReader`?

**Comment by haraldk** [comment]
Hi Jörn,

Thanks for reporting!

I think the recommended way of obtaining an `ImageReader` is as follows:

    ImageInputStream input = ImageIO.createInputStream(...);
    Iterator<ImageReader> readers = ImageIO.getImageReaders(input);

    if (readers.hasNext()) {
        ImageReader reader = readers.next();
        reader.setInput(input);
        
        // etc...
    }

This way, each plugin provider (`ImageReaderSpi` instance) will be passed the actual payload (`input` in the example above), to see if this is a format it understands, and if so, it can create an `ImageReader` instance to read it.

I prefer this way, because file extensions can be wrong and there are often multiple extensions for each format. MIME types from browsers can also not be fully trusted. Inspecting the actual payload is just safer and more reliable (although there can be false positives here as well). 


Best regards,

-- 
Harald K

**Comment by huxi** [comment]
Thanks a lot!
