### ISSUE TITLE
Warning system custom messages

### ISSUE THREAD

**Issue by JacobGreen082** [haraldk/TwelveMonkeys#967]
I'm having a problem with twelve monkeys, we repeatedly get this error message, 
      - The valueCount field for ENTRY:=270:ImageDescription differ between stream parsing (valueCount:=##) and twelvemonkeys API (valueCount:=1)

I want to add more to the warning message to better explain it, how can I adjust it?

**Comment by haraldk** [comment]
Hi Jacob,

I'm afraid I don't understand the question... Are you saying you get this message from the library? In that case, please include the stack trace, library version and more detail on how to reproduce. I really don't recognize this message and can't find it anywhere in our code... 

Or are you asking about how to create better warning message in your own code? For that, please use Stack Overflow, Code Review or other Q & A/forum type site.

**Comment by JacobGreen082** [comment]
@haraldk I'm new to this project so bare with me. I found the code we are using to trigger this warning but still looking for a possible solution 
![image](https://github.com/haraldk/TwelveMonkeys/assets/141251457/52479350-79f1-445b-bf7a-dc4c03700685)
This is an example of the data its having trouble with 
![image](https://github.com/haraldk/TwelveMonkeys/assets/141251457/1fe3d0c3-845d-4cfc-8ce1-e8a40c3b7af5)

**Comment by haraldk** [comment]
I'm still not exactly sure what your question is (other how you can adjust your warning message, which is not something I can help with)... The screenshot above does not contain TwelveMonkeys library code or code I am familiar with. 

But here are some general tips on how to get better help:

1. Ask specific questions about specific problems (this requires an understanding of your own code or the code you are asking about)
2. Don't post code as images, that is just annoying. Post as *text with proper formatting* (Github MD has Java code style support). Also, don't just post your full code, post only the code relevant to the issue.
3. Don't post log excerpts as images, that is just annoying. Again, post as *text with proper formatting*.

---

That said, my *guess* about what your issue is, is that you are somehow using the TwelveMonkeys low-level TIFF metadata library to extract metadata, and see that the `valueCount` field is 1 for string values (if the entry contains a single string). This differs from the native "value count" inside the TIFF structure, which for `ASCII` type fields is the number of characters (bytes), including null-term. 

But why this is a problem or what I can do to help is still unclear, as I don't know what you use this value for (other than comparing with some other value...).

**Comment by haraldk** [comment]
Closing, no feedback received.
