### ISSUE TITLE
Expose PSDLayerInfo?

### ISSUE THREAD

**Issue by JavadocMD** [haraldk/TwelveMonkeys#98]
I find myself in a use-case where I need more info about PSD-file layers. I see that it is currently stored in PSDLayerInfo: things like top, bottom, and name. However this appears to be access-restricted info. Would it be possible to expose this data (even if we have to use unsafe casts to get at it), or am I missing a good reason to hide it?

I would be happy to submit a pull request if that would be helpful. Thanks!

**Comment by haraldk** [comment]
Hi Tyler,

This is interesting! I don't think anyone has asked for this before. Can you please tell me a little more about the use case?

The idea has been to expose the data from the `PSDLayerInfo` (and image resource blocks) through the meta data class `PSDMetadata`, using the standard ImageIO metadata API. However, the current state of the `PSDMetadata` and `PSDMetadataFormat` classes is a little... sad. Lots of TODOs, including the layer info and other stuff you probably want. :-/

The main reason I haven't made the classes you ask for public, is that once you have published an API it's kind of stuck.. And I'd rather expose it in a standardized way, such as the meta data, so that I can freely rearrange and optimize the classes I use internally.

I'm also thinking about creating a completely new metadata API that's a little more programmer-friendly than the weird DOM-hybrid thing that is `IIOMetadata`. But that's a little further down the road.

Do you think you could create a PR with the information you need in the `PSDMetadata` (the data is already there, it's just not added to the meta data tree)? 


Best regards,

-- 
Harald K

**Comment by haraldk** [comment]
Hi again,

Had some spare time on the subway today, and looking at all those TODOs in the `PSDMetadata` class, I decided to actually do something about it. :-) 

There's not much that needs to be done to be able to pass the information from the `PSDLayerInfo` using the metadata, so I might be able to push something in the next few days.

But it would still be useful to know if this would cover your use case. The plan is to include the top/left/bottom/right + layer name. Do you need anything else (blend mode,  channel info, layer mask data or layer blending ranges)?


-- 
Harald K

**Comment by JavadocMD** [comment]
Thanks for the quick response! (Even before I could get back around to it.)  :)

Yes, I think top/left/bottom/right and name would be sufficient for what I want to do. Photoshop's animation tools seemed a little clumsy to me, so I'm creating a "viewer" app that will load the layers as I'm working on them and display them as an animated graphic. At the moment each frame tends to register as a different height and width because of varying transparent pixels (I'm assuming), so the animated image jitters back and forth. If I know the correct offsets to apply I can position each frame correctly. And I'd like to do some optional filtering on layer name.

In any case, this library is a real life-saver. Thanks for all the great work!

**Comment by haraldk** [comment]
Fixed in c3cafc63d82476c1853b21195c45138edcb8e8dd. 

Metadata is available from the `PSDImageReader` for image index 0, you should be able to obtain it like this:

    IIOMetadata metadata = imageReader.getImageMetadata(0);
    IIOMetadataNode root = (IIOMetadataNode) metadata.getAsTree(PSDMetadata.NATIVE_METADATA_FORMAT_NAME);
    NodeList layers = root.getElementsByTagName("Layers");
    // ... get the info you want...

The native PSD meta data looks something like this:

    <com_twelvemonkeys_imageio_psd_image_1.0>
	<Header type="PSD" version="1" channels="3" height="512" width="341" bits="8" mode="RGB"/>
	<ImageResources>
        
	</ImageResources>
	<Layers>
		<LayerInfo name="Layer 0" top="0" left="0" bottom="512" right="341" blendMode="norm" opacity="255" clipping="base" flags="40"/>
		<LayerInfo name="Invert 1" top="0" left="0" bottom="0" right="0" blendMode="norm" opacity="255" clipping="base" flags="56" pixelDataIrrelevant="true"/>
		<LayerInfo name="Layer 1" top="114" left="86" bottom="321" right="250" blendMode="norm" opacity="255" clipping="base" flags="40"/>
		<LayerInfo name="A text object created in PS7.0" top="33" left="95" bottom="94" right="317" blendMode="norm" opacity="255" clipping="base" flags="40"/>
	</Layers>
	<GlobalLayerMask colorSpace="0" colors="-1, 0, 0, 0" opacity="50" kind="layer"/>
    </com_twelvemonkeys_imageio_psd_image_1.0>

The fix will be released as part of 3.1 very soon. If you can't wait, you can use the latest version and build from source. :-)

PS: Feel free to reopen, should you have any questions regarding this issue.


Best regards,

-- 
Harald K

**Comment by JavadocMD** [comment]
I submitted a pull request to make PSDMetadata.NATIVE_METADATA_FORMAT_NAME public so as to match your sample code here. Other than that, I was able to build and test 3.1-SNAPSHOT and it's performing exactly as hoped. Thanks!
