### ISSUE TITLE
Please make BufferedChannelImageInputStream public

### ISSUE THREAD

**Issue by rmuller** [haraldk/TwelveMonkeys#986]
I want to use `BufferedChannelImageInputStream` in a custom `PathInputStreamSpi` to support `Path` objects as input for `ImageIO#createImageInputStream()`.

 `BufferedChannelImageInputStream`  has a constructor with `Path` as parameter. The class is only package-private :(

**Comment by haraldk** [comment]
Hi Ronald,

The class you mention is package protected by design and to be considered an implementation detail. I don't want to expose it as public API, as that makes things harder to change later. However, there are at least two possible options for you:

* Copy the entire class into your project, and use the copy. You can do this as long as you follow the BSD license (in the header of the file). 
* Create a PR  in the TwelveMonkeys project where you add the `PathInputStreamSpi` into the same package. I will accept such a PR, as long as you follow the code style and add the necessary tests.

**Comment by haraldk** [comment]
Closing for now
